# Generated by Django 4.0.4 on 2022-06-22 12:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('video', '0015_alter_video_options'),
        ('references', '0006_teamstatus_userteam_clubteam'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField(default=datetime.timedelta(0), help_text='The duration of the match in the format 00:00:00', verbose_name='duration match')),
                ('goals', models.SmallIntegerField(default=0, help_text='Number of goals scored by the team.', verbose_name='goals')),
                ('penalty', models.SmallIntegerField(default=0, help_text='Number of team penalties per match.', verbose_name='penalty')),
                ('opponent', models.CharField(max_length=255)),
                ('o_goals', models.SmallIntegerField(default=0, help_text='Number of goals scored by the opponent team.', verbose_name='opponent goals')),
                ('o_penalty', models.SmallIntegerField(default=0, help_text='Number of opponent team penalties per match.', verbose_name='opponent penalty')),
                ('estimation', models.SmallIntegerField(help_text='Rating of the match on the scale.', verbose_name='estimation')),
                ('place', models.CharField(help_text='Venue of the match.', max_length=80, verbose_name='place')),
                ('tournament', models.CharField(help_text='Tournament name.', max_length=80, verbose_name='tournament')),
                ('scheme_data', models.JSONField(blank=True, null=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.userevent')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.userteam')),
                ('trainer_user_id', models.ForeignKey(blank=True, help_text='Coach tied to the match', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='trainer')),
                ('video_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='video.video')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClubMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField(default=datetime.timedelta(0), help_text='The duration of the match in the format 00:00:00', verbose_name='duration match')),
                ('goals', models.SmallIntegerField(default=0, help_text='Number of goals scored by the team.', verbose_name='goals')),
                ('penalty', models.SmallIntegerField(default=0, help_text='Number of team penalties per match.', verbose_name='penalty')),
                ('opponent', models.CharField(max_length=255)),
                ('o_goals', models.SmallIntegerField(default=0, help_text='Number of goals scored by the opponent team.', verbose_name='opponent goals')),
                ('o_penalty', models.SmallIntegerField(default=0, help_text='Number of opponent team penalties per match.', verbose_name='opponent penalty')),
                ('estimation', models.SmallIntegerField(help_text='Rating of the match on the scale.', verbose_name='estimation')),
                ('place', models.CharField(help_text='Venue of the match.', max_length=80, verbose_name='place')),
                ('tournament', models.CharField(help_text='Tournament name.', max_length=80, verbose_name='tournament')),
                ('scheme_data', models.JSONField(blank=True, null=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.clubevent')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.clubteam')),
                ('trainer_user_id', models.ForeignKey(blank=True, help_text='Coach tied to the match', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='trainer')),
                ('video_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='video.video')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
