# Generated by Django 4.0.4 on 2022-07-12 09:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField(default=datetime.timedelta(0), help_text='The duration of the match in the format 00:00:00', verbose_name='duration match')),
                ('goals', models.SmallIntegerField(default=0, help_text='Number of goals scored by the team.', verbose_name='goals')),
                ('penalty', models.SmallIntegerField(default=0, help_text='Number of team penalties per match.', verbose_name='penalty')),
                ('opponent', models.CharField(max_length=255)),
                ('o_goals', models.SmallIntegerField(default=0, help_text='Number of goals scored by the opponent team.', verbose_name='opponent goals')),
                ('o_penalty', models.SmallIntegerField(default=0, help_text='Number of opponent team penalties per match.', verbose_name='opponent penalty')),
                ('estimation', models.SmallIntegerField(help_text='Rating of the match on the scale.', verbose_name='estimation')),
                ('place', models.CharField(help_text='Venue of the match.', max_length=80, verbose_name='place')),
                ('tournament', models.CharField(help_text='Tournament name.', max_length=80, verbose_name='tournament')),
                ('scheme_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField(default=datetime.timedelta(0), help_text='The duration of the match in the format 00:00:00', verbose_name='duration match')),
                ('goals', models.SmallIntegerField(default=0, help_text='Number of goals scored by the team.', verbose_name='goals')),
                ('penalty', models.SmallIntegerField(default=0, help_text='Number of team penalties per match.', verbose_name='penalty')),
                ('opponent', models.CharField(max_length=255)),
                ('o_goals', models.SmallIntegerField(default=0, help_text='Number of goals scored by the opponent team.', verbose_name='opponent goals')),
                ('o_penalty', models.SmallIntegerField(default=0, help_text='Number of opponent team penalties per match.', verbose_name='opponent penalty')),
                ('estimation', models.SmallIntegerField(help_text='Rating of the match on the scale.', verbose_name='estimation')),
                ('place', models.CharField(help_text='Venue of the match.', max_length=80, verbose_name='place')),
                ('tournament', models.CharField(help_text='Tournament name.', max_length=80, verbose_name='tournament')),
                ('scheme_data', models.JSONField(blank=True, null=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.userevent')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
