# Generated by Django 4.0.4 on 2022-07-12 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matches', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermatch',
            name='trainer_user_id',
            field=models.ForeignKey(blank=True, help_text='Coach tied to the match', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='trainer'),
        ),
    ]
