# Generated by Django 4.0.4 on 2022-10-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_userprotocol_clubprotocol'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubprotocol',
            name='p_num',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprotocol',
            name='p_num',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
