# Generated by Django 4.0.4 on 2022-10-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_clubprotocol_p_num_userprotocol_p_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubprotocol',
            name='is_opponent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprotocol',
            name='is_opponent',
            field=models.BooleanField(default=False),
        ),
    ]
