# Generated by Django 4.0.4 on 2022-07-21 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_clubevent_notes_alter_userevent_notes'),
        ('matches', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubmatch',
            name='id',
        ),
        migrations.RemoveField(
            model_name='usermatch',
            name='id',
        ),
        migrations.AlterField(
            model_name='clubmatch',
            name='event_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='events.clubevent'),
        ),
        migrations.AlterField(
            model_name='usermatch',
            name='event_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='events.userevent'),
        ),
    ]
