# Generated by Django 4.0.4 on 2022-09-28 08:31

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_remove_clubmatch_id_remove_usermatch_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmatch',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 28, 11, 31, 7, 919035)),
        ),
        migrations.AddField(
            model_name='clubmatch',
            name='m_format',
            field=models.CharField(blank=True, help_text='Match format.', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='clubmatch',
            name='m_type',
            field=models.IntegerField(default=0, help_text='Match type, 0 - not official, 1 - official.', validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='usermatch',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 28, 11, 31, 7, 919035)),
        ),
        migrations.AddField(
            model_name='usermatch',
            name='m_format',
            field=models.CharField(blank=True, help_text='Match format.', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='usermatch',
            name='m_type',
            field=models.IntegerField(default=0, help_text='Match type, 0 - not official, 1 - official.', validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='clubmatch',
            name='place',
            field=models.CharField(blank=True, help_text='Venue of the match.', max_length=80, null=True, verbose_name='place'),
        ),
        migrations.AlterField(
            model_name='clubmatch',
            name='tournament',
            field=models.CharField(blank=True, help_text='Tournament name.', max_length=80, null=True, verbose_name='tournament'),
        ),
        migrations.AlterField(
            model_name='usermatch',
            name='place',
            field=models.CharField(blank=True, help_text='Venue of the match.', max_length=80, null=True, verbose_name='place'),
        ),
        migrations.AlterField(
            model_name='usermatch',
            name='tournament',
            field=models.CharField(blank=True, help_text='Tournament name.', max_length=80, null=True, verbose_name='tournament'),
        ),
    ]
