# Generated by Django 4.0.4 on 2022-10-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_clubprotocol_p_status_userprotocol_p_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubprotocol',
            name='in_reserve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clubprotocol',
            name='is_captain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clubprotocol',
            name='is_goalkeeper',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprotocol',
            name='in_reserve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprotocol',
            name='is_captain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprotocol',
            name='is_goalkeeper',
            field=models.BooleanField(default=False),
        ),
    ]
