# Generated by Django 4.0.4 on 2022-09-28 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_clubmatch_datetime_clubmatch_m_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmatch',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 28, 11, 59, 19, 138640)),
        ),
        migrations.AlterField(
            model_name='usermatch',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 28, 11, 59, 19, 138640)),
        ),
    ]
