# Generated by Django 4.0.4 on 2022-10-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_clubprotocol_in_reserve_clubprotocol_is_captain_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubprotocol',
            options={'ordering': ['order', 'player__surname', 'player__name']},
        ),
        migrations.AlterModelOptions(
            name='userprotocol',
            options={'ordering': ['order', 'player__surname', 'player__name']},
        ),
        migrations.AddField(
            model_name='clubprotocol',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprotocol',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
