# Generated by Django 4.0.4 on 2022-09-28 11:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_alter_clubmatch_datetime_alter_usermatch_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmatch',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='clubmatch',
            name='estimation',
            field=models.SmallIntegerField(default=0, help_text='Rating of the match on the scale.', verbose_name='estimation'),
        ),
        migrations.AlterField(
            model_name='usermatch',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usermatch',
            name='estimation',
            field=models.SmallIntegerField(default=0, help_text='Rating of the match on the scale.', verbose_name='estimation'),
        ),
    ]
