# Generated by Django 4.0.4 on 2022-09-29 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_clubevent_options_alter_userevent_options'),
        ('matches', '0008_alter_clubmatch_datetime_alter_clubmatch_estimation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmatch',
            name='sync_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_event', to='events.clubevent'),
        ),
        migrations.AddField(
            model_name='usermatch',
            name='sync_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_event', to='events.userevent'),
        ),
    ]
