# Generated by Django 4.0.4 on 2022-10-12 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_clubprotocol_border_black_clubprotocol_border_red_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubprotocol',
            name='in_reserve',
        ),
        migrations.RemoveField(
            model_name='userprotocol',
            name='in_reserve',
        ),
    ]
