# Generated by Django 4.0.4 on 2022-10-14 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0009_remove_clubprotocol_in_reserve_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprotocol',
            options={'ordering': ['p_status__order', 'order', 'player__surname', 'player__name']},
        ),
    ]
