# Generated by Django 4.0.4 on 2022-10-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0009_clubmatch_sync_event_usermatch_sync_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubmatch',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='usermatch',
            name='datetime',
        ),
        migrations.AlterField(
            model_name='clubmatch',
            name='opponent',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='usermatch',
            name='opponent',
            field=models.CharField(default='', max_length=255),
        ),
    ]
