# Generated by Django 4.0.4 on 2022-10-18 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_eventvideolink_clubevent_video_link_and_more'),
        ('matches', '0010_alter_userprotocol_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubprotocol',
            name='video_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.eventvideolink'),
        ),
        migrations.AddField(
            model_name='userprotocol',
            name='video_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.eventvideolink'),
        ),
    ]
