# Generated by Django 4.0.4 on 2022-10-28 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0011_clubprotocol_video_link_userprotocol_video_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubmatch',
            options={'ordering': ['-event_id__date']},
        ),
        migrations.AlterModelOptions(
            name='usermatch',
            options={'ordering': ['-event_id__date']},
        ),
    ]
