# Generated by Django 4.0.4 on 2022-11-28 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0012_alter_clubmatch_options_alter_usermatch_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubmatch',
            options={'ordering': ['-event_id__date'], 'permissions': [('analytics_clubmatch', 'Access to the section "Analytics" for ClubMatch')]},
        ),
        migrations.AlterModelOptions(
            name='usermatch',
            options={'ordering': ['-event_id__date'], 'permissions': [('analytics_usermatch', 'Access to the section "Analytics" for UserMatch')]},
        ),
    ]
