# Generated by Django 4.0.4 on 2023-01-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0013_alter_clubmatch_options_alter_usermatch_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubprotocol',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprotocol',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
