# Generated by Django 4.0.4 on 2023-02-20 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_litemicrocycles_liteevent'),
        ('matches', '0014_clubprotocol_note_userprotocol_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiteMatch',
            fields=[
                ('event_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='events.liteevent')),
                ('team_name', models.CharField(blank=True, help_text='Name of the team being match', max_length=100, null=True, verbose_name='Team name')),
                ('sync_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_event', to='events.liteevent')),
            ],
            options={
                'ordering': ['-event_id__date'],
                'abstract': False,
            },
        ),
    ]
