# Generated by Django 4.0.4 on 2023-02-20 10:52

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0014_video_favourites'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matches', '0015_litematch'),
    ]

    operations = [
        migrations.AddField(
            model_name='litematch',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0), help_text='The duration of the match in the format 00:00:00', verbose_name='duration match'),
        ),
        migrations.AddField(
            model_name='litematch',
            name='estimation',
            field=models.SmallIntegerField(default=0, help_text='Rating of the match on the scale.', verbose_name='estimation'),
        ),
        migrations.AddField(
            model_name='litematch',
            name='goals',
            field=models.SmallIntegerField(default=0, help_text='Number of goals scored by the team.', verbose_name='goals'),
        ),
        migrations.AddField(
            model_name='litematch',
            name='m_format',
            field=models.CharField(blank=True, help_text='Match format.', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='litematch',
            name='m_type',
            field=models.IntegerField(default=0, help_text='Match type, 0 - not official, 1 - official.', validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='litematch',
            name='o_goals',
            field=models.SmallIntegerField(default=0, help_text='Number of goals scored by the opponent team.', verbose_name='opponent goals'),
        ),
        migrations.AddField(
            model_name='litematch',
            name='o_penalty',
            field=models.SmallIntegerField(default=0, help_text='Number of opponent team penalties per match.', verbose_name='opponent penalty'),
        ),
        migrations.AddField(
            model_name='litematch',
            name='opponent',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='litematch',
            name='penalty',
            field=models.SmallIntegerField(default=0, help_text='Number of team penalties per match.', verbose_name='penalty'),
        ),
        migrations.AddField(
            model_name='litematch',
            name='place',
            field=models.CharField(blank=True, help_text='Venue of the match.', max_length=80, null=True, verbose_name='place'),
        ),
        migrations.AddField(
            model_name='litematch',
            name='scheme_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='litematch',
            name='tournament',
            field=models.CharField(blank=True, help_text='Tournament name.', max_length=80, null=True, verbose_name='tournament'),
        ),
        migrations.AddField(
            model_name='litematch',
            name='trainer_user_id',
            field=models.ForeignKey(blank=True, help_text='Coach tied to the match', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='trainer'),
        ),
        migrations.AddField(
            model_name='litematch',
            name='video_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='video.video'),
        ),
    ]
