# Generated by Django 4.0.4 on 2023-03-06 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0017_remove_litematch_team_name_litematch_team_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubprotocol',
            options={'ordering': ['p_status__order', 'order', 'player__surname', 'player__name']},
        ),
    ]
