# Generated by Django 4.0.4 on 2023-03-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0018_alter_clubprotocol_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmatch',
            name='field_labels_opponent',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubmatch',
            name='field_labels_team',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='litematch',
            name='field_labels_opponent',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='litematch',
            name='field_labels_team',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermatch',
            name='field_labels_opponent',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermatch',
            name='field_labels_team',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
