# Generated by Django 4.0.4 on 2024-05-22 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0019_clubmatch_field_labels_opponent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubmatch',
            options={'ordering': ['event_id__date'], 'permissions': [('analytics_clubmatch', 'Access to the section "Analytics" for ClubMatch')]},
        ),
        migrations.AlterModelOptions(
            name='litematch',
            options={'ordering': ['event_id__date']},
        ),
        migrations.AlterModelOptions(
            name='usermatch',
            options={'ordering': ['event_id__date'], 'permissions': [('analytics_usermatch', 'Access to the section "Analytics" for UserMatch')]},
        ),
    ]
