# Generated by Django 4.0.4 on 2022-09-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_api_access',
            field=models.BooleanField(default=0),
        ),
    ]
