# Generated by Django 4.0.4 on 2022-10-20 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0001_initial'),
        ('users', '0003_user_is_api_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpayment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userpersonal',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='p_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='version.version'),
        ),
    ]
