# Generated by Django 4.0.4 on 2022-10-20 10:59

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userpayment_user_remove_userpersonal_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payment',
            field=models.OneToOneField(default=users.models.UserPayment.get_default_pk, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.userpayment'),
        ),
        migrations.AddField(
            model_name='user',
            name='personal',
            field=models.OneToOneField(default=users.models.UserPersonal.get_default_pk, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.userpersonal'),
        ),
    ]
