# Generated by Django 4.0.4 on 2022-10-20 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        ('users', '0005_user_payment_user_personal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='club_id',
            field=models.ForeignKey(default=None, help_text='The club the user is a member of', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.club', verbose_name='Club'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateField(auto_now_add=True, help_text='Date of registration', verbose_name='Date of registration'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_last_login',
            field=models.DateField(auto_now=True, help_text='Last login date', verbose_name='Last login date'),
        ),
    ]
