# Generated by Django 4.0.4 on 2022-05-12 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0002_access_tag_section_tag_alter_version_tag'),
        ('users', '0005_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='p_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='version.version'),
        ),
    ]
