# Generated by Django 4.0.4 on 2022-10-20 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_club_id_alter_user_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='club_id',
        ),
    ]
