# Generated by Django 4.0.4 on 2022-05-12 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_version'),
    ]

    operations = [
    ]
