# Generated by Django 4.0.4 on 2022-10-21 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_club_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='payment',
            field=models.OneToOneField(default=None, help_text='User Payment Information card', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userpayment', verbose_name='Payment Information'),
        ),
        migrations.AlterField(
            model_name='user',
            name='personal',
            field=models.OneToOneField(default=None, help_text='User Personal Information card', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userpersonal', verbose_name='Personal Information'),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='autopay_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='autopay_version',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='last_invoice_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
