# Generated by Django 4.0.4 on 2022-10-21 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        ('users', '0009_alter_user_payment_alter_user_personal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='club_id',
            field=models.ForeignKey(blank=True, default=None, help_text='The club the user is a member of', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.club', verbose_name='Club'),
        ),
    ]
