# Generated by Django 4.0.4 on 2022-06-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_user_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='club_id',
            field=models.IntegerField(default=0),
        ),
    ]
