# Generated by Django 4.0.4 on 2022-10-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_club_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpersonal',
            name='city',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userpersonal',
            name='country_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userpersonal',
            name='date_birthsday',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userpersonal',
            name='email_2',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userpersonal',
            name='father_name',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userpersonal',
            name='phone',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userpersonal',
            name='phone_2',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userpersonal',
            name='region_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userpersonal',
            name='skype',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
