# Generated by Django 4.0.4 on 2022-10-21 10:47

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_userpayment_autopay_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpayment',
            options={'verbose_name': 'Payment information'},
        ),
        migrations.AlterModelOptions(
            name='userpersonal',
            options={'verbose_name': 'Personal information'},
        ),
        migrations.AlterField(
            model_name='userpersonal',
            name='country_id',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
