# Generated by Django 4.0.4 on 2022-10-31 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_userpersonal_country_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpersonal',
            name='job_title',
            field=models.CharField(blank=True, help_text='User job title', max_length=60, null=True, verbose_name='Job title'),
        ),
    ]
