# Generated by Django 4.0.4 on 2022-11-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_userpersonal_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpersonal',
            name='region',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='userpersonal',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
    ]
