# Generated by Django 4.0.4 on 2022-11-17 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_userpersonal_region_alter_userpersonal_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='personal',
            field=models.OneToOneField(default=None, help_text='User Personal Information card', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userpersonal', verbose_name='Personal Information'),
        ),
    ]
