# Generated by Django 4.0.4 on 2022-12-09 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0003_limitations_clublimitations_version_limits'),
        ('users', '0018_alter_user_personal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='p_version',
            field=models.ForeignKey(blank=True, help_text='User version', null=True, on_delete=django.db.models.deletion.SET_NULL, to='version.version', verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='user',
            name='payment',
            field=models.OneToOneField(blank=True, default=None, help_text='User Payment Information card', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userpayment', verbose_name='Payment Information'),
        ),
        migrations.AlterField(
            model_name='user',
            name='personal',
            field=models.OneToOneField(blank=True, default=None, help_text='User Personal Information card', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userpersonal', verbose_name='Personal Information'),
        ),
    ]
