# Generated by Django 4.0.4 on 2023-02-09 09:27

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_userpersonal_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpersonal',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.user_directory_path),
        ),
    ]
