# Generated by Django 4.0.4 on 2023-02-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_userpersonal_date_birthsday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpersonal',
            name='region',
            field=models.CharField(default=None, max_length=60, null=True),
        ),
    ]
