# Generated by Django 4.0.4 on 2023-02-28 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_userpersonal_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_to',
            field=models.DateField(default=datetime.date.today, help_text='Version expiration date', verbose_name='Expiration version'),
        ),
        migrations.AddField(
            model_name='userpersonal',
            name='license_date',
            field=models.DateField(default=None, help_text='Date of birth', null=True, verbose_name='Birthday'),
        ),
    ]
