# Generated by Django 4.0.4 on 2023-02-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_user_registration_to_userpersonal_license_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpersonal',
            name='job_title',
            field=models.CharField(help_text='User job title', max_length=30, null=True, verbose_name='Job title'),
        ),
        migrations.AlterField(
            model_name='userpersonal',
            name='license',
            field=models.CharField(help_text="Trainer's License", max_length=30, null=True, verbose_name='License'),
        ),
        migrations.AlterField(
            model_name='userpersonal',
            name='skype',
            field=models.CharField(default=None, max_length=30, null=True, verbose_name='Skype'),
        ),
    ]
