# Generated by Django 4.0.4 on 2023-02-28 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_userpersonal_job_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpersonal',
            name='license_date',
            field=models.DateField(default=datetime.date.today, help_text='Date of birth', null=True, verbose_name='Birthday'),
        ),
    ]
