# Generated by Django 4.0.4 on 2023-03-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_userpersonal_license_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpersonal',
            name='email_2',
            field=models.CharField(blank=True, default=None, help_text='Spare email', max_length=60, null=True, verbose_name='Spare email'),
        ),
        migrations.AlterField(
            model_name='userpersonal',
            name='father_name',
            field=models.CharField(blank=True, default=None, help_text='Father name', max_length=50, null=True, verbose_name='Patronymic'),
        ),
        migrations.AlterField(
            model_name='userpersonal',
            name='phone_2',
            field=models.CharField(blank=True, default=None, help_text='Spare phone number', max_length=25, null=True, verbose_name='Spare phone'),
        ),
        migrations.AlterField(
            model_name='userpersonal',
            name='skype',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Skype'),
        ),
    ]
