# Generated by Django 4.0.4 on 2023-04-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_userpersonal_license_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_demo_mode',
            field=models.BooleanField(default=1),
        ),
    ]
