# Generated by Django 4.0.4 on 2023-05-25 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_userpersonal_job_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPaymentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.DecimalField(decimal_places=2, default=0.0, help_text='Payment in foreign currency', max_digits=8, verbose_name='Payment')),
                ('discount', models.PositiveSmallIntegerField(default=0, help_text='Percent discount (0-100%)', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Discount')),
                ('date', models.DateField(help_text='Date when the user paid', verbose_name='Date of payment')),
            ],
        ),
        migrations.AddField(
            model_name='userpersonal',
            name='my_contacts',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='payment_information',
            field=models.ManyToManyField(blank=True, help_text='Payment information for accounting', to='users.userpaymentinformation', verbose_name='Payment Information'),
        ),
    ]
