# Generated by Django 4.0.4 on 2023-05-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_userpaymentinformation_userpersonal_my_contacts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpersonal',
            name='club_title',
            field=models.CharField(blank=True, help_text='User club title', max_length=60, null=True, verbose_name='Club title'),
        ),
    ]
