# Generated by Django 4.0.4 on 2023-06-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_userpersonal_club_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_last_login',
            field=models.DateField(help_text='Last login date', verbose_name='Last login date'),
        ),
    ]
