# Generated by Django 4.0.4 on 2023-06-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_alter_user_date_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_last_login',
            field=models.DateField(help_text='Last login date', null=True, verbose_name='Last login date'),
        ),
    ]
