# Generated by Django 4.0.4 on 2023-06-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_trainerlicense_alter_userpersonal_license_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='distributor',
            field=models.CharField(blank=True, default=None, help_text='User distributor', max_length=20, null=True, verbose_name='Distributor'),
        ),
    ]
