# Generated by Django 4.0.4 on 2023-06-21 11:59

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_user_distributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registration_to',
            field=models.DateField(default=users.models.get_default_date, help_text='Version expiration date', verbose_name='Expiration version'),
        ),
    ]
