# Generated by Django 4.0.4 on 2023-06-21 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_alter_user_registration_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registration_to',
            field=models.DateField(default=datetime.date.today, help_text='Version expiration date', verbose_name='Expiration version'),
        ),
    ]
