# Generated by Django 4.0.4 on 2023-07-01 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('federations', '0001_initial'),
        ('users', '0039_alter_user_registration_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='federation_id',
            field=models.ForeignKey(blank=True, default=None, help_text='The federation the user is a member of', null=True, on_delete=django.db.models.deletion.SET_NULL, to='federations.federation', verbose_name='Federation'),
        ),
    ]
