# Generated by Django 4.0.4 on 2023-09-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_alter_user_date_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='player_limit',
            field=models.IntegerField(default=25, help_text='limit on the number of players in a team', verbose_name='number of players'),
        ),
        migrations.AddField(
            model_name='user',
            name='team_limit',
            field=models.IntegerField(default=2, help_text='limit on the number of teams', verbose_name='number of teams'),
        ),
    ]
