# Generated by Django 4.0.4 on 2023-12-04 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_user_player_limit_user_team_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='payment_information',
        ),
        migrations.DeleteModel(
            name='UserPaymentInformation',
        ),
    ]
