# Generated by Django 4.0.4 on 2024-05-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_user_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='marks',
            field=models.JSONField(null=True),
        ),
    ]
