# Generated by Django 4.0.4 on 2024-07-30 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_user_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_last_exs_req_reset',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 12, 45, 21, 55327)),
        ),
        migrations.AddField(
            model_name='user',
            name='exs_requests_counter',
            field=models.IntegerField(default=0),
        ),
    ]
