# Generated by Django 4.0.4 on 2024-07-30 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_user_date_last_exs_req_reset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_last_exs_req_reset',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
