# Generated by Django 4.0.4 on 2022-06-22 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the event. The maximum length is 80 characters', max_length=80, verbose_name='name')),
                ('short_name', models.CharField(help_text='The short name of the event. The maximum length is 10 characters', max_length=10, verbose_name='short name')),
                ('notes', models.JSONField(help_text='Notes to the event.', verbose_name='notes')),
                ('date', models.DateTimeField(help_text='Date and time of this event', verbose_name='date')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClubEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the event. The maximum length is 80 characters', max_length=80, verbose_name='name')),
                ('short_name', models.CharField(help_text='The short name of the event. The maximum length is 10 characters', max_length=10, verbose_name='short name')),
                ('notes', models.JSONField(help_text='Notes to the event.', verbose_name='notes')),
                ('date', models.DateTimeField(help_text='Date and time of this event', verbose_name='date')),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
    ]
