# Generated by Django 4.0.4 on 2022-07-12 09:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the event. The maximum length is 80 characters', max_length=80, verbose_name='name')),
                ('short_name', models.CharField(help_text='The short name of the event. The maximum length is 10 characters', max_length=10, verbose_name='short name')),
                ('notes', models.JSONField(help_text='Notes to the event.', verbose_name='notes')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of this event', verbose_name='date')),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClubMicrocycles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Microcycle', help_text='Name of the microcycle. The maximum length is 80 characters', max_length=80, verbose_name='title')),
                ('date_with', models.DateField(help_text='Start date of the microcycle.', verbose_name='start date')),
                ('date_by', models.DateField(help_text='End date of the microcycle.', verbose_name='end date')),
            ],
            options={
                'ordering': ['date_with'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the event. The maximum length is 80 characters', max_length=80, verbose_name='name')),
                ('short_name', models.CharField(help_text='The short name of the event. The maximum length is 10 characters', max_length=10, verbose_name='short name')),
                ('notes', models.JSONField(help_text='Notes to the event.', verbose_name='notes')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of this event', verbose_name='date')),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserMicrocycles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Microcycle', help_text='Name of the microcycle. The maximum length is 80 characters', max_length=80, verbose_name='title')),
                ('date_with', models.DateField(help_text='Start date of the microcycle.', verbose_name='start date')),
                ('date_by', models.DateField(help_text='End date of the microcycle.', verbose_name='end date')),
            ],
            options={
                'ordering': ['date_with'],
                'abstract': False,
            },
        ),
    ]
