# Generated by Django 4.0.4 on 2022-06-27 15:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubevent',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of this event', verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of this event', verbose_name='date'),
        ),
    ]
