# Generated by Django 4.0.4 on 2022-06-29 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0014_alter_clubseason_date_by_alter_clubseason_date_with_and_more'),
        ('events', '0002_alter_clubevent_date_alter_userevent_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMicrocycles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the microcycle. The maximum length is 60 characters', max_length=60, null=True, verbose_name='title')),
                ('date_with', models.DateField(help_text='Start date of the microcycle.', verbose_name='start date')),
                ('date_by', models.DateField(help_text='End date of the microcycle.', verbose_name='end date')),
                ('team_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.userteam')),
            ],
        ),
    ]
