# Generated by Django 4.0.4 on 2022-07-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubevent',
            name='notes',
            field=models.JSONField(blank=True, help_text='Notes to the event.', null=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='notes',
            field=models.JSONField(blank=True, help_text='Notes to the event.', null=True, verbose_name='notes'),
        ),
    ]
