# Generated by Django 4.0.4 on 2022-06-30 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0014_alter_clubseason_date_by_alter_clubseason_date_with_and_more'),
        ('events', '0004_alter_usermicrocycles_team_id_clubmicrocycles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermicrocycles',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.userteam'),
        ),
        migrations.DeleteModel(
            name='ClubMicrocycles',
        ),
    ]
