# Generated by Django 4.0.4 on 2022-07-21 12:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_clubevent_notes_alter_userevent_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubevent',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userevent',
            name='name',
        ),
        migrations.AlterField(
            model_name='clubevent',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of this event', verbose_name='Date and time'),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of this event', verbose_name='Date and time'),
        ),
    ]
