# Generated by Django 4.0.4 on 2022-07-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_clubevent_name_remove_userevent_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubevent',
            name='short_name',
            field=models.CharField(help_text='The short name of the event. The maximum length is 4 characters', max_length=4, verbose_name='short name'),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='short_name',
            field=models.CharField(help_text='The short name of the event. The maximum length is 4 characters', max_length=4, verbose_name='short name'),
        ),
    ]
