# Generated by Django 4.0.4 on 2022-07-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_clubevent_short_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubevent',
            name='short_name',
            field=models.CharField(blank=True, help_text='The short name of the event. The maximum length is 4 characters', max_length=4, null=True, verbose_name='short name'),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='short_name',
            field=models.CharField(blank=True, help_text='The short name of the event. The maximum length is 4 characters', max_length=4, null=True, verbose_name='short name'),
        ),
    ]
