# Generated by Django 4.0.4 on 2022-07-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_clubmicrocycles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubmicrocycles',
            options={'ordering': ['date_with']},
        ),
        migrations.AlterModelOptions(
            name='usermicrocycles',
            options={'ordering': ['date_with']},
        ),
        migrations.AlterField(
            model_name='clubmicrocycles',
            name='name',
            field=models.CharField(default='Microcycle', help_text='Name of the microcycle. The maximum length is 80 characters', max_length=80, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='usermicrocycles',
            name='name',
            field=models.CharField(default='Microcycle', help_text='Name of the microcycle. The maximum length is 80 characters', max_length=80, verbose_name='title'),
        ),
    ]
