# Generated by Django 4.0.4 on 2022-07-31 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_clubevent_short_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubevent',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='userevent',
            options={'ordering': ['-date']},
        ),
    ]
