# Generated by Django 4.0.4 on 2022-10-18 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0012_alter_video_taggit'),
        ('events', '0008_alter_clubevent_options_alter_userevent_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventVideoLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_link', models.JSONField(blank=True, null=True)),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='video.video')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='clubevent',
            name='video_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.eventvideolink'),
        ),
        migrations.AddField(
            model_name='userevent',
            name='video_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.eventvideolink'),
        ),
    ]
