# Generated by Django 4.0.4 on 2022-10-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_eventvideolink_clubevent_video_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventvideolink',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
