# Generated by Django 4.0.4 on 2022-10-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_eventvideolink_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventvideolink',
            name='description',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
