# Generated by Django 4.0.4 on 2023-01-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_eventvideolink_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventvideolink',
            name='name',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
