# Generated by Django 4.0.4 on 2023-09-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_alter_clubmicrocycles_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmicrocycles',
            name='goal',
            field=models.CharField(blank=True, default='', help_text='Goal of the microcycle. The maximum length is 80 characters', max_length=80, verbose_name='М.Ц. 2'),
        ),
        migrations.AlterField(
            model_name='litemicrocycles',
            name='goal',
            field=models.CharField(blank=True, default='', help_text='Goal of the microcycle. The maximum length is 80 characters', max_length=80, verbose_name='М.Ц. 2'),
        ),
        migrations.AlterField(
            model_name='usermicrocycles',
            name='goal',
            field=models.CharField(blank=True, default='', help_text='Goal of the microcycle. The maximum length is 80 characters', max_length=80, verbose_name='М.Ц. 2'),
        ),
    ]
