# Generated by Django 4.0.4 on 2023-09-25 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_alter_clubmicrocycles_goal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubmicrocycles',
            options={'ordering': ['-date_with']},
        ),
        migrations.AlterModelOptions(
            name='litemicrocycles',
            options={'ordering': ['-date_with']},
        ),
        migrations.AlterModelOptions(
            name='usermicrocycles',
            options={'ordering': ['-date_with']},
        ),
    ]
