# Generated by Django 4.0.4 on 2023-12-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_alter_clubmicrocycles_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubmicrocycles',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='litemicrocycles',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='usermicrocycles',
            name='goal',
        ),
        migrations.AddField(
            model_name='clubmicrocycles',
            name='short_key',
            field=models.CharField(blank=True, default='', help_text='Microcycle short code', max_length=20, verbose_name='Short key'),
        ),
        migrations.AddField(
            model_name='litemicrocycles',
            name='short_key',
            field=models.CharField(blank=True, default='', help_text='Microcycle short code', max_length=20, verbose_name='Short key'),
        ),
        migrations.AddField(
            model_name='usermicrocycles',
            name='short_key',
            field=models.CharField(blank=True, default='', help_text='Microcycle short code', max_length=20, verbose_name='Short key'),
        ),
    ]
