# Generated by Django 4.0.4 on 2024-01-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_remove_clubmicrocycles_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmicrocycles',
            name='block',
            field=models.CharField(blank=True, default='', help_text='Block of the microcycle. The maximum length is 100 characters', max_length=100, verbose_name='Block'),
        ),
        migrations.AddField(
            model_name='clubmicrocycles',
            name='block_key',
            field=models.CharField(blank=True, default='', help_text='Microcycle block code', max_length=20, verbose_name='Block key'),
        ),
        migrations.AddField(
            model_name='litemicrocycles',
            name='block',
            field=models.CharField(blank=True, default='', help_text='Block of the microcycle. The maximum length is 100 characters', max_length=100, verbose_name='Block'),
        ),
        migrations.AddField(
            model_name='litemicrocycles',
            name='block_key',
            field=models.CharField(blank=True, default='', help_text='Microcycle block code', max_length=20, verbose_name='Block key'),
        ),
        migrations.AddField(
            model_name='usermicrocycles',
            name='block',
            field=models.CharField(blank=True, default='', help_text='Block of the microcycle. The maximum length is 100 characters', max_length=100, verbose_name='Block'),
        ),
        migrations.AddField(
            model_name='usermicrocycles',
            name='block_key',
            field=models.CharField(blank=True, default='', help_text='Microcycle block code', max_length=20, verbose_name='Block key'),
        ),
    ]
