# Generated by Django 4.0.4 on 2023-04-07 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0005_remove_club_limits_club_player_limit_club_team_limit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('order', models.IntegerField(default=0, help_text='Индекс сортировки')),
                ('visible', models.BooleanField(default=True, help_text='Показывать статью пользователю или нет')),
                ('completed', models.BooleanField(default=False, help_text='Статья завершена')),
                ('drafted', models.BooleanField(default=False, help_text='Статья в черновике')),
                ('title', models.JSONField(blank=True, null=True)),
                ('content', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdminFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Название папки', max_length=255, null=True)),
                ('translations_name', models.JSONField(blank=True, null=True)),
                ('parent', models.IntegerField(blank=True, help_text='Ид папки родителя', null=True)),
                ('visible', models.BooleanField(default=True, help_text='Показывать папку пользователю или нет')),
                ('short_name', models.CharField(help_text='Короткий ключ для поиска', max_length=10)),
                ('order', models.IntegerField(default=0, help_text='Индекс сортировки')),
                ('active', models.BooleanField(default=True, help_text='Показывать папку любому пользователю на релизе, неактивные папки доступны администрации.')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClubArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('order', models.IntegerField(default=0, help_text='Индекс сортировки')),
                ('visible', models.BooleanField(default=True, help_text='Показывать статью пользователю или нет')),
                ('completed', models.BooleanField(default=False, help_text='Статья завершена')),
                ('drafted', models.BooleanField(default=False, help_text='Статья в черновике')),
                ('title', models.JSONField(blank=True, null=True)),
                ('content', models.JSONField(blank=True, null=True)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='helper_site_clubarticle_club', to='clubs.club')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('order', models.IntegerField(default=0, help_text='Индекс сортировки')),
                ('visible', models.BooleanField(default=True, help_text='Показывать статью пользователю или нет')),
                ('completed', models.BooleanField(default=False, help_text='Статья завершена')),
                ('drafted', models.BooleanField(default=False, help_text='Статья в черновике')),
                ('title', models.JSONField(blank=True, null=True)),
                ('content', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Название папки', max_length=255, null=True)),
                ('translations_name', models.JSONField(blank=True, null=True)),
                ('parent', models.IntegerField(blank=True, help_text='Ид папки родителя', null=True)),
                ('visible', models.BooleanField(default=True, help_text='Показывать папку пользователю или нет')),
                ('short_name', models.CharField(help_text='Короткий ключ для поиска', max_length=10)),
                ('order', models.IntegerField(default=0, help_text='Индекс сортировки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helper_site_userfolder_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserArticleParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.BooleanField(default=False)),
                ('article_club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='helper_site.clubarticle')),
                ('article_nfb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='helper_site.adminarticle')),
                ('article_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='helper_site.userarticle')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='helper_site_userarticleparam_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userarticle',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper_site.userfolder'),
        ),
        migrations.AddField(
            model_name='userarticle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helper_site_userarticle_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ClubFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Название папки', max_length=255, null=True)),
                ('translations_name', models.JSONField(blank=True, null=True)),
                ('parent', models.IntegerField(blank=True, help_text='Ид папки родителя', null=True)),
                ('visible', models.BooleanField(default=True, help_text='Показывать папку пользователю или нет')),
                ('short_name', models.CharField(help_text='Короткий ключ для поиска', max_length=10)),
                ('order', models.IntegerField(default=0, help_text='Индекс сортировки')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='helper_site_clubfolder_club', to='clubs.club')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='clubarticle',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper_site.clubfolder'),
        ),
        migrations.AddField(
            model_name='clubarticle',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='helper_site_clubarticle_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminarticle',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper_site.adminfolder'),
        ),
    ]
