# Generated by Django 4.0.4 on 2024-10-20 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_club_image'),
        ('references', '0041_alter_clubseason_date_by_alter_clubseason_date_with_and_more'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubtablemarkers',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='references.clubteam'),
        ),
        migrations.AddField(
            model_name='usertablemarkers',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='references.userteam'),
        ),
        migrations.AlterField(
            model_name='clubtablemarkers',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club'),
        ),
    ]
