# Generated by Django 4.0.4 on 2024-10-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_clubtablemarkers_team_usertablemarkers_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubtablemarkers',
            name='season',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertablemarkers',
            name='season',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
