# Generated by Django 4.0.4 on 2024-10-20 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0041_alter_clubseason_date_by_alter_clubseason_date_with_and_more'),
        ('analytics', '0003_clubtablemarkers_season_usertablemarkers_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubtablemarkers',
            name='season_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertablemarkers',
            name='season_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clubtablemarkers',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='references.clubseason'),
        ),
        migrations.AlterField(
            model_name='usertablemarkers',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='references.userseason'),
        ),
    ]
