# Generated by Django 4.0.4 on 2024-10-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_clubtablemarkers_season_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubtablemarkers',
            name='table_blocks',
            field=models.CharField(blank=True, default='', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='clubtablemarkers',
            name='table_default',
            field=models.CharField(blank=True, default='', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='clubtablemarkers',
            name='table_teams_folders',
            field=models.CharField(blank=True, default='', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='usertablemarkers',
            name='table_blocks',
            field=models.CharField(blank=True, default='', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='usertablemarkers',
            name='table_default',
            field=models.CharField(blank=True, default='', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='usertablemarkers',
            name='table_teams_folders',
            field=models.CharField(blank=True, default='', max_length=2048, null=True),
        ),
    ]
