# Generated by Django 4.0.4 on 2024-10-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_alter_clubtablemarkers_table_blocks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubtablemarkers',
            name='table_blocks',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='clubtablemarkers',
            name='table_default',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='clubtablemarkers',
            name='table_teams_folders',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='usertablemarkers',
            name='table_blocks',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='usertablemarkers',
            name='table_default',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='usertablemarkers',
            name='table_teams_folders',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
