# Generated by Django 4.0.4 on 2023-07-01 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('version', '0006_section_translation_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Federation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_limit', models.IntegerField(default=10, help_text='limit on the number of clubs', verbose_name='number of clubs')),
                ('name', models.CharField(help_text='Federation title. Maximum length of 100 characters.', max_length=100, verbose_name='title')),
                ('subdomain', models.CharField(help_text='The domain that will be displayed. The maximum length is 10 characters.', max_length=10, verbose_name='subdomain')),
                ('date_registration', models.DateField(auto_now_add=True, help_text='Date of registration of the federation in the program.', verbose_name='date registration')),
                ('date_registration_to', models.DateField(default=datetime.date.today, help_text='License expiration date.', verbose_name='License termination')),
                ('block', models.BooleanField(default=False, help_text='Is the federation blocked?', verbose_name='block')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this federation belongs to. A club will get all permissions granted to each of their groups.', to='auth.group', verbose_name='groups')),
                ('permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this federation.', to='auth.permission', verbose_name='permissions')),
                ('versions', models.ManyToManyField(blank=True, help_text='Versions available to the federation for issuance', to='version.version', verbose_name='Versions')),
            ],
            options={
                'verbose_name': 'Federation card',
                'verbose_name_plural': 'Federation cards',
                'permissions': [('federation_admin', 'Access to the federation admin panel')],
            },
        ),
    ]
