# Generated by Django 4.0.4 on 2025-07-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminarticle',
            name='completed',
            field=models.BooleanField(default=False, help_text='Турнир завершена'),
        ),
        migrations.AlterField(
            model_name='adminarticle',
            name='drafted',
            field=models.BooleanField(default=False, help_text='Турнир в черновике'),
        ),
        migrations.AlterField(
            model_name='adminarticle',
            name='visible',
            field=models.BooleanField(default=True, help_text='Показывать турнир пользователю или нет'),
        ),
        migrations.AlterField(
            model_name='clubarticle',
            name='completed',
            field=models.BooleanField(default=False, help_text='Турнир завершена'),
        ),
        migrations.AlterField(
            model_name='clubarticle',
            name='drafted',
            field=models.BooleanField(default=False, help_text='Турнир в черновике'),
        ),
        migrations.AlterField(
            model_name='clubarticle',
            name='visible',
            field=models.BooleanField(default=True, help_text='Показывать турнир пользователю или нет'),
        ),
        migrations.AlterField(
            model_name='userarticle',
            name='completed',
            field=models.BooleanField(default=False, help_text='Турнир завершена'),
        ),
        migrations.AlterField(
            model_name='userarticle',
            name='drafted',
            field=models.BooleanField(default=False, help_text='Турнир в черновике'),
        ),
        migrations.AlterField(
            model_name='userarticle',
            name='visible',
            field=models.BooleanField(default=True, help_text='Показывать турнир пользователю или нет'),
        ),
    ]
