# Generated by Django 4.0.4 on 2025-12-29 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0035_playercard_name_playercard_patronymic_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time of this test', verbose_name='Date and time')),
                ('parameters', models.JSONField(default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='trainer')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserPlayerResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('values', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='players.userplayer')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_results', to='testing.test')),
            ],
            options={
                'abstract': False,
                'unique_together': {('test', 'player', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ClubPlayerResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('values', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='players.clubplayer')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_results', to='testing.test')),
            ],
            options={
                'abstract': False,
                'unique_together': {('test', 'player', 'date')},
            },
        ),
    ]
