# Generated by Django 4.0.4 on 2022-09-21 13:06

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IconsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Название иконки', max_length=255, null=True)),
                ('color', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=18, samples=None)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='system_icons/icons')),
            ],
        ),
    ]
