# Generated by Django 4.0.4 on 2022-09-21 14:19

from django.db import migrations, models
import django.db.models.deletion
import system_icons.models


class Migration(migrations.Migration):

    dependencies = [
        ('system_icons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iconslist',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='iconslist',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='system_icons/icons', validators=[system_icons.models.validate_image]),
        ),
        migrations.CreateModel(
            name='UIElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Название UI элемента', max_length=255, null=True)),
                ('text_id', models.CharField(blank=True, help_text='Текст.ID для идентификации элемента на сайте', max_length=20, null=True)),
                ('category', models.CharField(blank=True, help_text='категория UI элемента, для упрощенного поиска.', max_length=255, null=True)),
                ('icon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system_icons.iconslist')),
            ],
        ),
    ]
