# Generated by Django 4.0.4 on 2022-09-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_icons', '0002_alter_iconslist_options_alter_iconslist_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uielement',
            name='text_id',
            field=models.CharField(blank=True, help_text='Текст.ID для идентификации элемента на сайте', max_length=255, null=True),
        ),
    ]
