# Generated by Django 4.0.4 on 2022-09-22 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_icons', '0003_alter_uielement_text_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uielement',
            options={'ordering': ['id']},
        ),
    ]
