# Generated by Django 4.0.4 on 2022-10-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_icons', '0004_alter_uielement_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='uielement',
            name='hint',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
