# Generated by Django 4.0.4 on 2022-10-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_icons', '0005_uielement_hint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uielement',
            name='hint',
            field=models.JSONField(blank=True, help_text='JSON Obj. format: {"en": "hint", "ru": "подсказка"}', null=True),
        ),
    ]
