# Generated by Django 4.0.4 on 2022-11-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedlink',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
