# Generated by Django 4.0.4 on 2023-04-25 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_remove_club_limits_club_player_limit_club_team_limit_and_more'),
        ('shared', '0003_sharedlink_match_lite_sharedlink_training_lite'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedlink',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.club'),
        ),
    ]
