# Generated by Django 4.0.4 on 2024-03-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0004_sharedlink_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedlink',
            name='analytics',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
