# Generated by Django 4.0.4 on 2023-06-30 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_remove_club_limits_club_player_limit_club_team_limit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drawer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminBackPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название рисунка (ID)', max_length=255, unique=True)),
                ('img', models.ImageField(upload_to='drawer/img/uploads')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserBackPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название рисунка (ID)', max_length=255, unique=True)),
                ('img', models.ImageField(upload_to='drawer/img/uploads')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClubBackPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название рисунка (ID)', max_length=255, unique=True)),
                ('img', models.ImageField(upload_to='drawer/img/uploads')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.club')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
