# Generated by Django 4.0.4 on 2023-06-30 20:39

from django.db import migrations, models
import drawer.models


class Migration(migrations.Migration):

    dependencies = [
        ('drawer', '0002_adminbackpicture_userbackpicture_clubbackpicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminbackpicture',
            name='img',
            field=models.ImageField(upload_to=drawer.models.upload_location, validators=[drawer.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='clubbackpicture',
            name='img',
            field=models.ImageField(upload_to=drawer.models.upload_location, validators=[drawer.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='userbackpicture',
            name='img',
            field=models.ImageField(upload_to=drawer.models.upload_location, validators=[drawer.models.validate_image]),
        ),
    ]
