# Generated by Django 4.0.4 on 2023-07-02 13:47

from django.db import migrations, models
import drawer.models


class Migration(migrations.Migration):

    dependencies = [
        ('drawer', '0003_alter_adminbackpicture_img_alter_clubbackpicture_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admindraw',
            name='rendered_img',
            field=models.ImageField(blank=True, null=True, upload_to=drawer.models.upload_location_field),
        ),
        migrations.AddField(
            model_name='clubdraw',
            name='rendered_img',
            field=models.ImageField(blank=True, null=True, upload_to=drawer.models.upload_location_field),
        ),
        migrations.AddField(
            model_name='userdraw',
            name='rendered_img',
            field=models.ImageField(blank=True, null=True, upload_to=drawer.models.upload_location_field),
        ),
    ]
