# Generated by Django 4.0.4 on 2022-07-20 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0002_initial'),
        ('references', '0002_initial'),
        ('events', '0004_alter_clubevent_notes_alter_userevent_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.clubevent')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.clubteam')),
            ],
        ),
        migrations.CreateModel(
            name='UserTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.userevent')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.userteam')),
            ],
        ),
        migrations.CreateModel(
            name='UserTrainingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.PositiveSmallIntegerField(choices=[(1, 'Group A'), (2, 'Group B'), (3, 'Group C')], help_text='The group to which the exercise belongs', verbose_name='group')),
                ('duration', models.PositiveSmallIntegerField(default=0, help_text='Duration of the exercise', verbose_name='duration')),
                ('order', models.IntegerField(default=0, help_text='Sorting index', verbose_name='order')),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.userexercise')),
                ('training_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.usertraining')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClubTrainingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.PositiveSmallIntegerField(choices=[(1, 'Group A'), (2, 'Group B'), (3, 'Group C')], help_text='The group to which the exercise belongs', verbose_name='group')),
                ('duration', models.PositiveSmallIntegerField(default=0, help_text='Duration of the exercise', verbose_name='duration')),
                ('order', models.IntegerField(default=0, help_text='Sorting index', verbose_name='order')),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.clubexercise')),
                ('training_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.clubtraining')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
