# Generated by Django 4.0.4 on 2022-07-20 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '0005_exsaddition'),
        ('exercises', '0005_adminexercise_players_ages_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_alter_clubevent_notes_alter_userevent_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubTraining',
            fields=[
                ('objectives', models.JSONField(blank=True, help_text='Objectives for training groups', null=True, verbose_name='purposes')),
                ('event_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='events.clubevent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserTraining',
            fields=[
                ('objectives', models.JSONField(blank=True, help_text='Objectives for training groups', null=True, verbose_name='purposes')),
                ('event_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='events.userevent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserTrainingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.PositiveSmallIntegerField(choices=[(1, 'Group A'), (2, 'Group B'), (3, 'Group C')], help_text='The group to which the exercise belongs', verbose_name='group')),
                ('duration', models.PositiveSmallIntegerField(default=0, help_text='Duration of the exercise', verbose_name='duration')),
                ('order', models.IntegerField(default=0, help_text='Sorting index', verbose_name='order')),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.userexercise')),
                ('training_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.usertraining')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='usertraining',
            name='exercises',
            field=models.ManyToManyField(through='trainings.UserTrainingExercise', to='exercises.userexercise'),
        ),
        migrations.AddField(
            model_name='usertraining',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.userteam'),
        ),
        migrations.AddField(
            model_name='usertraining',
            name='trainer_user_id',
            field=models.ForeignKey(blank=True, help_text='Coach tied to the training', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='trainer'),
        ),
        migrations.CreateModel(
            name='ClubTrainingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.PositiveSmallIntegerField(choices=[(1, 'Group A'), (2, 'Group B'), (3, 'Group C')], help_text='The group to which the exercise belongs', verbose_name='group')),
                ('duration', models.PositiveSmallIntegerField(default=0, help_text='Duration of the exercise', verbose_name='duration')),
                ('order', models.IntegerField(default=0, help_text='Sorting index', verbose_name='order')),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.clubexercise')),
                ('training_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.clubtraining')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='clubtraining',
            name='exercises',
            field=models.ManyToManyField(through='trainings.ClubTrainingExercise', to='exercises.clubexercise'),
        ),
        migrations.AddField(
            model_name='clubtraining',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.clubteam'),
        ),
        migrations.AddField(
            model_name='clubtraining',
            name='trainer_user_id',
            field=models.ForeignKey(blank=True, help_text='Coach tied to the training', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='trainer'),
        ),
    ]
