# Generated by Django 4.0.4 on 2022-07-20 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubtrainingexercise',
            name='exercise_id',
        ),
        migrations.RemoveField(
            model_name='clubtrainingexercise',
            name='training_id',
        ),
        migrations.RemoveField(
            model_name='usertraining',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='usertraining',
            name='exercises',
        ),
        migrations.RemoveField(
            model_name='usertraining',
            name='team_id',
        ),
        migrations.RemoveField(
            model_name='usertraining',
            name='trainer_user_id',
        ),
        migrations.RemoveField(
            model_name='usertrainingexercise',
            name='exercise_id',
        ),
        migrations.RemoveField(
            model_name='usertrainingexercise',
            name='training_id',
        ),
        migrations.DeleteModel(
            name='ClubTraining',
        ),
        migrations.DeleteModel(
            name='ClubTrainingExercise',
        ),
        migrations.DeleteModel(
            name='UserTraining',
        ),
        migrations.DeleteModel(
            name='UserTrainingExercise',
        ),
    ]
