# Generated by Django 4.0.4 on 2022-08-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubtrainingexercise',
            name='favourites',
            field=models.BooleanField(default=False, help_text='Favorites training', verbose_name='favourites'),
        ),
        migrations.AddField(
            model_name='usertrainingexercise',
            name='favourites',
            field=models.BooleanField(default=False, help_text='Favorites training', verbose_name='favourites'),
        ),
    ]
