# Generated by Django 4.0.4 on 2022-08-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0004_clubtrainingexercise_favourites_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubtrainingexercise',
            name='favourites',
        ),
        migrations.RemoveField(
            model_name='usertrainingexercise',
            name='favourites',
        ),
        migrations.AddField(
            model_name='clubtraining',
            name='favourites',
            field=models.BooleanField(default=False, help_text='Favorites training', verbose_name='favourites'),
        ),
        migrations.AddField(
            model_name='usertraining',
            name='favourites',
            field=models.BooleanField(default=False, help_text='Favorites training', verbose_name='favourites'),
        ),
    ]
