# Generated by Django 4.0.4 on 2022-09-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0005_remove_clubtrainingexercise_favourites_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubtrainingexercise',
            name='group',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Group A'), (2, 'Group B'), (3, 'Group C'), (4, 'Group D')], help_text='The group to which the exercise belongs', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='usertrainingexercise',
            name='group',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Group A'), (2, 'Group B'), (3, 'Group C'), (4, 'Group D')], help_text='The group to which the exercise belongs', verbose_name='group'),
        ),
    ]
