# Generated by Django 4.0.4 on 2022-09-14 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0012_playerfoot_playerlevel_playerplayerstatus_and_more'),
        ('trainings', '0006_alter_clubtrainingexercise_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingExerciseAdditionalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(help_text='Note to the reference book', max_length=255, verbose_name='note')),
                ('additional_data_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.exsadditionaldata')),
            ],
        ),
        migrations.AddField(
            model_name='clubtrainingexercise',
            name='additional_data',
            field=models.ManyToManyField(help_text='Additional information for the exercise in the training card', to='trainings.trainingexerciseadditionaldata', verbose_name='additional information'),
        ),
        migrations.AddField(
            model_name='usertrainingexercise',
            name='additional_data',
            field=models.ManyToManyField(help_text='Additional information for the exercise in the training card', to='trainings.trainingexerciseadditionaldata', verbose_name='additional information'),
        ),
    ]
