# Generated by Django 4.0.4 on 2022-09-14 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0008_clubtrainingexerciseadditionaldata_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubtrainingexercise',
            old_name='additional_data',
            new_name='additional',
        ),
        migrations.RenameField(
            model_name='clubtrainingexerciseadditionaldata',
            old_name='additional_data_id',
            new_name='additional_id',
        ),
        migrations.RenameField(
            model_name='clubtrainingexerciseadditionaldata',
            old_name='training_exercise_id',
            new_name='training_exercise',
        ),
        migrations.RenameField(
            model_name='usertrainingexercise',
            old_name='additional_data',
            new_name='additional',
        ),
        migrations.RenameField(
            model_name='usertrainingexerciseadditionaldata',
            old_name='additional_data_id',
            new_name='additional_id',
        ),
        migrations.RenameField(
            model_name='usertrainingexerciseadditionaldata',
            old_name='training_exercise_id',
            new_name='training_exercise',
        ),
    ]
