# Generated by Django 4.0.4 on 2022-09-14 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0012_playerfoot_playerlevel_playerplayerstatus_and_more'),
        ('trainings', '0009_rename_additional_data_clubtrainingexercise_additional_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClubTrainingExerciseAdditionalData',
            new_name='ClubTrainingExerciseAdditional',
        ),
        migrations.RenameModel(
            old_name='UserTrainingExerciseAdditionalData',
            new_name='UserTrainingExerciseAdditional',
        ),
    ]
