# Generated by Django 4.0.4 on 2022-09-14 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0010_rename_clubtrainingexerciseadditionaldata_clubtrainingexerciseadditional_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertrainingexerciseadditional',
            name='additional_id',
        ),
        migrations.RemoveField(
            model_name='usertrainingexerciseadditional',
            name='training_exercise',
        ),
        migrations.RemoveField(
            model_name='clubtrainingexercise',
            name='additional',
        ),
        migrations.RemoveField(
            model_name='usertrainingexercise',
            name='additional',
        ),
        migrations.DeleteModel(
            name='ClubTrainingExerciseAdditional',
        ),
        migrations.DeleteModel(
            name='UserTrainingExerciseAdditional',
        ),
    ]
