# Generated by Django 4.0.4 on 2022-09-14 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0012_playerfoot_playerlevel_playerplayerstatus_and_more'),
        ('trainings', '0011_remove_usertrainingexerciseadditional_additional_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubTrainingExerciseAdditional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(help_text='Note to the reference book', max_length=255, verbose_name='note')),
                ('additional_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.exsadditionaldata')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserTrainingExerciseAdditional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(help_text='Note to the reference book', max_length=255, verbose_name='note')),
                ('additional_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.exsadditionaldata')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='clubtrainingexercise',
            name='additional',
            field=models.ManyToManyField(through='trainings.ClubTrainingExerciseAdditional', to='references.exsadditionaldata'),
        ),
        migrations.AddField(
            model_name='usertrainingexercise',
            name='additional',
            field=models.ManyToManyField(through='trainings.UserTrainingExerciseAdditional', to='references.exsadditionaldata'),
        ),
        migrations.AddField(
            model_name='usertrainingexerciseadditional',
            name='training_exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.usertrainingexercise'),
        ),
        migrations.AddField(
            model_name='clubtrainingexerciseadditional',
            name='training_exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.clubtrainingexercise'),
        ),
    ]
