# Generated by Django 4.0.4 on 2022-09-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0012_clubtrainingexerciseadditional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubtrainingexerciseadditional',
            name='note',
            field=models.CharField(blank=True, help_text='Note to the reference book', max_length=255, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='usertrainingexerciseadditional',
            name='note',
            field=models.CharField(blank=True, help_text='Note to the reference book', max_length=255, verbose_name='note'),
        ),
    ]
