# Generated by Django 4.0.4 on 2022-09-14 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0013_alter_clubtrainingexerciseadditional_note_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubtrainingexerciseadditional',
            old_name='training_exercise',
            new_name='training_exercise_id',
        ),
        migrations.RenameField(
            model_name='usertrainingexerciseadditional',
            old_name='training_exercise',
            new_name='training_exercise_id',
        ),
    ]
