# Generated by Django 4.0.4 on 2022-09-14 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0012_playerfoot_playerlevel_playerplayerstatus_and_more'),
        ('trainings', '0014_rename_training_exercise_clubtrainingexerciseadditional_training_exercise_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubtrainingexerciseadditional',
            name='additional_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='references.exsadditionaldata'),
        ),
        migrations.AlterField(
            model_name='usertrainingexerciseadditional',
            name='additional_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='references.exsadditionaldata'),
        ),
    ]
