# Generated by Django 4.0.4 on 2022-09-14 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0012_playerfoot_playerlevel_playerplayerstatus_and_more'),
        ('trainings', '0015_alter_clubtrainingexerciseadditional_additional_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubtrainingexerciseadditional',
            name='additional_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.exsadditionaldata'),
        ),
        migrations.AlterField(
            model_name='clubtrainingexerciseadditional',
            name='note',
            field=models.CharField(blank=True, help_text='Note to the reference book', max_length=255, null=True, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='usertrainingexerciseadditional',
            name='additional_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.exsadditionaldata'),
        ),
        migrations.AlterField(
            model_name='usertrainingexerciseadditional',
            name='note',
            field=models.CharField(blank=True, help_text='Note to the reference book', max_length=255, null=True, verbose_name='note'),
        ),
    ]
