# Generated by Django 4.0.4 on 2022-09-22 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0013_playerprotocolstatus'),
        ('players', '0015_playerquestionnairesrows_playerquestionnaireuser_and_more'),
        ('trainings', '0016_alter_clubtrainingexerciseadditional_additional_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTrainingProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimation', models.PositiveSmallIntegerField(choices=[(0, 'No'), (1, 'Like'), (2, 'Dislike')], default=0, help_text='Player rating like/dislike', verbose_name='estimation')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.userplayer')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.playerprotocolstatus')),
                ('training_exercise_check', models.ManyToManyField(to='trainings.usertrainingexercise')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='usertraining',
            name='protocol',
            field=models.ManyToManyField(through='trainings.UserTrainingProtocol', to='players.userplayer'),
        ),
        migrations.AddField(
            model_name='usertrainingprotocol',
            name='training_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.usertraining'),
        ),
    ]
