# Generated by Django 4.0.4 on 2022-09-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0017_usertrainingprotocol_usertraining_protocol_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubtrainingexercise',
            options={'ordering': ['group', 'order']},
        ),
        migrations.AlterModelOptions(
            name='usertrainingexercise',
            options={'ordering': ['group', 'order']},
        ),
        migrations.AlterField(
            model_name='usertrainingprotocol',
            name='training_exercise_check',
            field=models.ManyToManyField(blank=True, to='trainings.usertrainingexercise'),
        ),
    ]
