# Generated by Django 4.0.4 on 2022-10-03 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0015_playerquestionnairesrows_playerquestionnaireuser_and_more'),
        ('trainings', '0018_alter_clubtrainingexercise_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertrainingprotocol',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.userplayer', unique=True),
        ),
    ]
