# Generated by Django 4.0.4 on 2022-10-12 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0020_alter_usertrainingprotocol_player_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertrainingprotocol',
            options={'ordering': ['status__order']},
        ),
    ]
