# Generated by Django 4.0.4 on 2022-11-17 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0016_alter_playercard_ref_foot_alter_playercard_ref_level_and_more'),
        ('references', '0018_alter_clubteam_users'),
        ('trainings', '0023_alter_usertrainingprotocol_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubTrainingProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimation', models.PositiveSmallIntegerField(choices=[(0, 'No'), (1, 'Like'), (2, 'Dislike')], default=0, help_text='Player rating like/dislike', verbose_name='estimation')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.clubplayer')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.playerprotocolstatus')),
                ('training_exercise_check', models.ManyToManyField(blank=True, to='trainings.clubtrainingexercise')),
                ('training_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.clubtraining')),
            ],
            options={
                'ordering': ['status__order', 'player_id__card__ref_position__order'],
            },
        ),
    ]
