# Generated by Django 4.0.4 on 2022-11-28 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0024_clubtrainingprotocol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubtraining',
            options={'permissions': [('analytics_clubtraining', 'Access to the section "Analytics" for ClubTraining')]},
        ),
        migrations.AlterModelOptions(
            name='usertraining',
            options={'permissions': [('analytics_usertraining', 'Access to the section "Analytics" for UserTraining')]},
        ),
    ]
