# Generated by Django 4.0.4 on 2023-01-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0027_clubtrainingexercise_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubtraining',
            name='favourites',
            field=models.SmallIntegerField(default=0, help_text='Favorites training', verbose_name='favourites'),
        ),
        migrations.AlterField(
            model_name='usertraining',
            name='favourites',
            field=models.SmallIntegerField(default=0, help_text='Favorites training', verbose_name='favourites'),
        ),
    ]
