# Generated by Django 4.0.4 on 2023-01-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0028_alter_clubtraining_favourites_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubtraining',
            name='additional',
            field=models.JSONField(blank=True, help_text='Additional training data', null=True, verbose_name='additional'),
        ),
        migrations.AddField(
            model_name='usertraining',
            name='additional',
            field=models.JSONField(blank=True, help_text='Additional training data', null=True, verbose_name='additional'),
        ),
    ]
