# Generated by Django 4.0.4 on 2023-01-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0029_clubtraining_additional_usertraining_additional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubtraining',
            name='space',
        ),
        migrations.RemoveField(
            model_name='usertraining',
            name='space',
        ),
        migrations.AddField(
            model_name='clubtraining',
            name='field_size',
            field=models.CharField(blank=True, help_text='The size of the field in training', max_length=255, null=True, verbose_name='field size'),
        ),
        migrations.AddField(
            model_name='clubtraining',
            name='keywords_1',
            field=models.CharField(blank=True, help_text='Keywords in training', max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='clubtraining',
            name='keywords_2',
            field=models.CharField(blank=True, help_text='Keywords in training', max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='clubtraining',
            name='load_type',
            field=models.CharField(blank=True, help_text='Type of training load', max_length=255, null=True, verbose_name='load type'),
        ),
        migrations.AddField(
            model_name='usertraining',
            name='field_size',
            field=models.CharField(blank=True, help_text='The size of the field in training', max_length=255, null=True, verbose_name='field size'),
        ),
        migrations.AddField(
            model_name='usertraining',
            name='keywords_1',
            field=models.CharField(blank=True, help_text='Keywords in training', max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='usertraining',
            name='keywords_2',
            field=models.CharField(blank=True, help_text='Keywords in training', max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='usertraining',
            name='load_type',
            field=models.CharField(blank=True, help_text='Type of training load', max_length=255, null=True, verbose_name='load type'),
        ),
    ]
