# Generated by Django 4.0.4 on 2023-01-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0030_remove_clubtraining_space_remove_usertraining_space_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubtraining',
            name='video_href',
            field=models.CharField(blank=True, help_text='Link to the training video', max_length=255, null=True, verbose_name='link to the video'),
        ),
        migrations.AddField(
            model_name='usertraining',
            name='video_href',
            field=models.CharField(blank=True, help_text='Link to the training video', max_length=255, null=True, verbose_name='link to the video'),
        ),
        migrations.AlterField(
            model_name='clubtraining',
            name='keywords_1',
            field=models.CharField(blank=True, help_text='Keywords in training', max_length=255, null=True, verbose_name='keywords'),
        ),
        migrations.AlterField(
            model_name='clubtraining',
            name='keywords_2',
            field=models.CharField(blank=True, help_text='Keywords in training', max_length=255, null=True, verbose_name='keywords'),
        ),
        migrations.AlterField(
            model_name='usertraining',
            name='keywords_1',
            field=models.CharField(blank=True, help_text='Keywords in training', max_length=255, null=True, verbose_name='keywords'),
        ),
        migrations.AlterField(
            model_name='usertraining',
            name='keywords_2',
            field=models.CharField(blank=True, help_text='Keywords in training', max_length=255, null=True, verbose_name='keywords'),
        ),
    ]
