# Generated by Django 4.0.4 on 2023-01-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0031_clubtraining_video_href_usertraining_video_href_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubtraining',
            name='objectives',
            field=models.JSONField(blank=True, help_text='Objectives for training groups', null=True, verbose_name='objectives'),
        ),
        migrations.AlterField(
            model_name='usertraining',
            name='objectives',
            field=models.JSONField(blank=True, help_text='Objectives for training groups', null=True, verbose_name='objectives'),
        ),
    ]
