# Generated by Django 4.0.4 on 2023-01-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0032_alter_clubtraining_objectives_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubtraining',
            name='keywords_1',
        ),
        migrations.RemoveField(
            model_name='clubtraining',
            name='keywords_2',
        ),
        migrations.RemoveField(
            model_name='clubtraining',
            name='objectives',
        ),
        migrations.RemoveField(
            model_name='usertraining',
            name='keywords_1',
        ),
        migrations.RemoveField(
            model_name='usertraining',
            name='keywords_2',
        ),
        migrations.RemoveField(
            model_name='usertraining',
            name='objectives',
        ),
        migrations.AddField(
            model_name='clubtraining',
            name='goal',
            field=models.CharField(blank=True, help_text='Goal in training', max_length=255, null=True, verbose_name='goal'),
        ),
        migrations.AddField(
            model_name='clubtraining',
            name='notes',
            field=models.JSONField(blank=True, help_text='Notes for training groups', null=True, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='clubtraining',
            name='objective_1',
            field=models.CharField(blank=True, help_text='Objective in training', max_length=255, null=True, verbose_name='objective'),
        ),
        migrations.AddField(
            model_name='clubtraining',
            name='objective_2',
            field=models.CharField(blank=True, help_text='Objective in training', max_length=255, null=True, verbose_name='objective'),
        ),
        migrations.AddField(
            model_name='usertraining',
            name='goal',
            field=models.CharField(blank=True, help_text='Goal in training', max_length=255, null=True, verbose_name='goal'),
        ),
        migrations.AddField(
            model_name='usertraining',
            name='notes',
            field=models.JSONField(blank=True, help_text='Notes for training groups', null=True, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='usertraining',
            name='objective_1',
            field=models.CharField(blank=True, help_text='Objective in training', max_length=255, null=True, verbose_name='objective'),
        ),
        migrations.AddField(
            model_name='usertraining',
            name='objective_2',
            field=models.CharField(blank=True, help_text='Objective in training', max_length=255, null=True, verbose_name='objective'),
        ),
    ]
