# Generated by Django 4.0.4 on 2023-01-27 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0033_remove_clubtraining_keywords_1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubtrainingprotocol',
            options={'ordering': ['status__order', '-player_id__card__is_goalkeeper', 'player_id__card__ref_position__order']},
        ),
        migrations.AlterModelOptions(
            name='usertrainingprotocol',
            options={'ordering': ['status__order', '-player_id__card__is_goalkeeper', 'player_id__card__ref_position__order']},
        ),
    ]
