# Generated by Django 4.0.4 on 2023-02-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0024_alter_playerstablecolumns_short_name_and_more'),
        ('trainings', '0034_alter_clubtrainingprotocol_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubtraining',
            name='protocol',
            field=models.ManyToManyField(through='trainings.ClubTrainingProtocol', to='players.clubplayer'),
        ),
    ]
