# Generated by Django 4.0.4 on 2023-02-17 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_litemicrocycles_liteevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0074_adminexercise_field_physical_qualities_and_more'),
        ('references', '0028_alter_exsphysicalqualities_options_and_more'),
        ('trainings', '0035_clubtraining_protocol'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiteTraining',
            fields=[
                ('favourites', models.SmallIntegerField(default=0, help_text='Favorites training', verbose_name='favourites')),
                ('field_size', models.CharField(blank=True, help_text='The size of the field in training', max_length=255, null=True, verbose_name='field size')),
                ('load_type', models.CharField(blank=True, help_text='Type of training load', max_length=255, null=True, verbose_name='load type')),
                ('goal', models.CharField(blank=True, help_text='Goal in training', max_length=255, null=True, verbose_name='goal')),
                ('objective_1', models.CharField(blank=True, help_text='Objective in training', max_length=255, null=True, verbose_name='objective')),
                ('objective_2', models.CharField(blank=True, help_text='Objective in training', max_length=255, null=True, verbose_name='objective')),
                ('video_href', models.CharField(blank=True, help_text='Link to the training video', max_length=255, null=True, verbose_name='link to the video')),
                ('additional', models.JSONField(blank=True, help_text='Additional training data', null=True, verbose_name='additional')),
                ('notes', models.JSONField(blank=True, help_text='Notes for training groups', null=True, verbose_name='notes')),
                ('event_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='events.liteevent')),
                ('team_name', models.CharField(blank=True, help_text='Name of the team being trained', max_length=100, null=True, verbose_name='Team name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LiteTrainingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.PositiveSmallIntegerField(choices=[(1, 'Group A'), (2, 'Group B'), (3, 'Group C'), (4, 'Group D')], help_text='The group to which the exercise belongs', verbose_name='group')),
                ('duration', models.PositiveSmallIntegerField(default=0, help_text='Duration of the exercise', verbose_name='duration')),
                ('description', models.TextField(blank=True, help_text='Description of the exercise inside the training', null=True, verbose_name='description')),
                ('order', models.IntegerField(default=0, help_text='Sorting index', verbose_name='order')),
            ],
            options={
                'ordering': ['group', 'order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LiteTrainingExerciseAdditional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, help_text='Note to the reference book', max_length=255, null=True, verbose_name='note')),
                ('additional_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.exsadditionaldata')),
                ('training_exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.litetrainingexercise')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='litetrainingexercise',
            name='additional',
            field=models.ManyToManyField(through='trainings.LiteTrainingExerciseAdditional', to='references.exsadditionaldata'),
        ),
        migrations.AddField(
            model_name='litetrainingexercise',
            name='exercise_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.userexercise'),
        ),
        migrations.AddField(
            model_name='litetrainingexercise',
            name='training_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.litetraining'),
        ),
        migrations.AddField(
            model_name='litetraining',
            name='exercises',
            field=models.ManyToManyField(through='trainings.LiteTrainingExercise', to='exercises.userexercise'),
        ),
        migrations.AddField(
            model_name='litetraining',
            name='trainer_user_id',
            field=models.ForeignKey(blank=True, help_text='Coach tied to the training', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='trainer'),
        ),
    ]
