# Generated by Django 4.0.4 on 2023-03-20 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0030_userexsadditionaldata_clubexsadditionaldata'),
        ('trainings', '0038_litetraining_goalkeepers_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubtrainingexercise',
            name='additional',
            field=models.ManyToManyField(through='trainings.ClubTrainingExerciseAdditional', to='references.clubexsadditionaldata'),
        ),
        migrations.AlterField(
            model_name='clubtrainingexerciseadditional',
            name='additional_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.clubexsadditionaldata'),
        ),
        migrations.AlterField(
            model_name='litetrainingexercise',
            name='additional',
            field=models.ManyToManyField(through='trainings.LiteTrainingExerciseAdditional', to='references.userexsadditionaldata'),
        ),
        migrations.AlterField(
            model_name='litetrainingexerciseadditional',
            name='additional_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.userexsadditionaldata'),
        ),
        migrations.AlterField(
            model_name='usertrainingexercise',
            name='additional',
            field=models.ManyToManyField(through='trainings.UserTrainingExerciseAdditional', to='references.userexsadditionaldata'),
        ),
        migrations.AlterField(
            model_name='usertrainingexerciseadditional',
            name='additional_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.userexsadditionaldata'),
        ),
    ]
