# Generated by Django 4.0.4 on 2023-03-23 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0039_alter_clubtrainingexercise_additional_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubtrainingexerciseadditional',
            options={'ordering': ['additional_id__order']},
        ),
        migrations.AlterModelOptions(
            name='litetrainingexerciseadditional',
            options={'ordering': ['additional_id__order']},
        ),
        migrations.AlterModelOptions(
            name='usertrainingexerciseadditional',
            options={'ordering': ['additional_id__order']},
        ),
    ]
