# Generated by Django 4.0.4 on 2023-04-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0040_alter_clubtrainingexerciseadditional_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubtrainingexercise',
            name='additional_json',
            field=models.JSONField(blank=True, help_text='Additional training exercise data', null=True, verbose_name='additional'),
        ),
        migrations.AddField(
            model_name='litetrainingexercise',
            name='additional_json',
            field=models.JSONField(blank=True, help_text='Additional training exercise data', null=True, verbose_name='additional'),
        ),
        migrations.AddField(
            model_name='usertrainingexercise',
            name='additional_json',
            field=models.JSONField(blank=True, help_text='Additional training exercise data', null=True, verbose_name='additional'),
        ),
    ]
