# Generated by Django 4.0.4 on 2023-09-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0041_clubtrainingexercise_additional_json_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubtraining',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='litetraining',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='usertraining',
            name='goal',
        ),
        migrations.AddField(
            model_name='clubtraining',
            name='objective_3',
            field=models.CharField(blank=True, help_text='Objective in training', max_length=255, null=True, verbose_name='objective'),
        ),
        migrations.AddField(
            model_name='litetraining',
            name='objective_3',
            field=models.CharField(blank=True, help_text='Objective in training', max_length=255, null=True, verbose_name='objective'),
        ),
        migrations.AddField(
            model_name='usertraining',
            name='objective_3',
            field=models.CharField(blank=True, help_text='Objective in training', max_length=255, null=True, verbose_name='objective'),
        ),
    ]
