# Generated by Django 4.0.4 on 2023-12-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0042_remove_clubtraining_goal_remove_litetraining_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubtraining',
            name='inventory',
            field=models.JSONField(blank=True, help_text='Inventory for training', null=True, verbose_name='inventory'),
        ),
        migrations.AddField(
            model_name='litetraining',
            name='inventory',
            field=models.JSONField(blank=True, help_text='Inventory for training', null=True, verbose_name='inventory'),
        ),
        migrations.AddField(
            model_name='usertraining',
            name='inventory',
            field=models.JSONField(blank=True, help_text='Inventory for training', null=True, verbose_name='inventory'),
        ),
    ]
