# Generated by Django 4.0.4 on 2023-12-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0043_clubtraining_inventory_litetraining_inventory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubtraining',
            name='players_json',
            field=models.JSONField(blank=True, help_text='Quick list of players', null=True, verbose_name='players'),
        ),
        migrations.AddField(
            model_name='litetraining',
            name='players_json',
            field=models.JSONField(blank=True, help_text='Quick list of players', null=True, verbose_name='players'),
        ),
        migrations.AddField(
            model_name='usertraining',
            name='players_json',
            field=models.JSONField(blank=True, help_text='Quick list of players', null=True, verbose_name='players'),
        ),
    ]
