# Generated by Django 4.0.4 on 2024-01-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0044_clubtraining_players_json_litetraining_players_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubtraining',
            name='objective_key',
            field=models.CharField(blank=True, help_text='Objective key in training', max_length=20, null=True, verbose_name='objective key'),
        ),
        migrations.AddField(
            model_name='clubtraining',
            name='objectives',
            field=models.JSONField(help_text='Objectives in training', null=True, verbose_name='objectives'),
        ),
        migrations.AddField(
            model_name='litetraining',
            name='objective_key',
            field=models.CharField(blank=True, help_text='Objective key in training', max_length=20, null=True, verbose_name='objective key'),
        ),
        migrations.AddField(
            model_name='litetraining',
            name='objectives',
            field=models.JSONField(help_text='Objectives in training', null=True, verbose_name='objectives'),
        ),
        migrations.AddField(
            model_name='usertraining',
            name='objective_key',
            field=models.CharField(blank=True, help_text='Objective key in training', max_length=20, null=True, verbose_name='objective key'),
        ),
        migrations.AddField(
            model_name='usertraining',
            name='objectives',
            field=models.JSONField(help_text='Objectives in training', null=True, verbose_name='objectives'),
        ),
    ]
