# Generated by Django 4.0.4 on 2024-02-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0046_remove_clubtraining_objective_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubtraining',
            name='objectives',
            field=models.ManyToManyField(help_text='Objective in training', through='trainings.ClubTrainingObjectiveMany', to='trainings.clubtrainingobjectives', verbose_name='objective'),
        ),
    ]
