# Generated by Django 4.0.4 on 2024-02-09 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_club_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainings', '0047_alter_clubtraining_objectives'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubtrainingobjectives',
            name='team',
        ),
        migrations.RemoveField(
            model_name='usertrainingobjectives',
            name='team',
        ),
        migrations.AddField(
            model_name='clubtrainingobjectives',
            name='club',
            field=models.ForeignKey(blank=True, help_text='Club', null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.club', verbose_name='Club'),
        ),
        migrations.AddField(
            model_name='usertrainingobjectives',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
