# Generated by Django 4.0.4 on 2024-03-04 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_club_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainings', '0050_remove_clubtraining_field_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTrainingBlocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(blank=True, help_text='The short key of the training block', max_length=30, null=True, verbose_name='Block key')),
                ('name', models.CharField(blank=True, help_text='The name of the training block', max_length=255, null=True, verbose_name='Block name')),
                ('user', models.ForeignKey(blank=True, help_text='User', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserTrainingBlockMany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.usertrainingblocks')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.usertraining')),
            ],
            options={
                'ordering': ['block__name'],
            },
        ),
        migrations.CreateModel(
            name='ClubTrainingBlocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(blank=True, help_text='The short key of the training block', max_length=30, null=True, verbose_name='Block key')),
                ('name', models.CharField(blank=True, help_text='The name of the training block', max_length=255, null=True, verbose_name='Block name')),
                ('club', models.ForeignKey(blank=True, help_text='Club', null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.club', verbose_name='Club')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClubTrainingBlockMany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.clubtrainingblocks')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.clubtraining')),
            ],
            options={
                'ordering': ['block__name'],
            },
        ),
        migrations.AddField(
            model_name='clubtraining',
            name='blocks',
            field=models.ManyToManyField(help_text='Block in training', through='trainings.ClubTrainingBlockMany', to='trainings.clubtrainingblocks', verbose_name='Block'),
        ),
        migrations.AddField(
            model_name='usertraining',
            name='blocks',
            field=models.ManyToManyField(blank=True, help_text='Block in training', through='trainings.UserTrainingBlockMany', to='trainings.usertrainingblocks', verbose_name='Block'),
        ),
    ]
