# Generated by Django 4.0.4 on 2024-03-04 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0051_usertrainingblocks_usertrainingblockmany_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubtraining',
            name='block',
        ),
        migrations.RemoveField(
            model_name='clubtraining',
            name='block_short_key',
        ),
        migrations.RemoveField(
            model_name='litetraining',
            name='block',
        ),
        migrations.RemoveField(
            model_name='litetraining',
            name='block_short_key',
        ),
        migrations.RemoveField(
            model_name='usertraining',
            name='block',
        ),
        migrations.RemoveField(
            model_name='usertraining',
            name='block_short_key',
        ),
    ]
