# Generated by Django 4.0.4 on 2024-03-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0054_alter_clubtraining_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubtraining',
            name='group',
            field=models.SmallIntegerField(default=0, help_text='Training group', verbose_name='Group'),
        ),
        migrations.AddField(
            model_name='litetraining',
            name='group',
            field=models.SmallIntegerField(default=0, help_text='Training group', verbose_name='Group'),
        ),
        migrations.AddField(
            model_name='usertraining',
            name='group',
            field=models.SmallIntegerField(default=0, help_text='Training group', verbose_name='Group'),
        ),
    ]
