# Generated by Django 4.0.4 on 2024-04-08 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0007_club_image'),
        ('trainings', '0055_clubtraining_group_litetraining_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTrainingLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(blank=True, help_text='The short key of the training load', max_length=30, null=True, verbose_name='Load key')),
                ('name', models.CharField(blank=True, help_text='The name of the training load', max_length=255, null=True, verbose_name='Load name')),
                ('user', models.ForeignKey(blank=True, help_text='User', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClubTrainingLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(blank=True, help_text='The short key of the training load', max_length=30, null=True, verbose_name='Load key')),
                ('name', models.CharField(blank=True, help_text='The name of the training load', max_length=255, null=True, verbose_name='Load name')),
                ('club', models.ForeignKey(blank=True, help_text='Club', null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.club', verbose_name='Club')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='clubtraining',
            name='load',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainings.clubtrainingload'),
        ),
        migrations.AddField(
            model_name='usertraining',
            name='load',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainings.usertrainingload'),
        ),
    ]
