# Generated by Django 4.0.4 on 2024-04-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0056_usertrainingload_clubtrainingload_clubtraining_load_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTrainingBlocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(blank=True, help_text='The short key of the training block', max_length=30, null=True, verbose_name='Block key')),
                ('name', models.CharField(blank=True, help_text='The name of the training block', max_length=255, null=True, verbose_name='Block name')),
                ('variant', models.SmallIntegerField(default=0, help_text='Variant', verbose_name='Variant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdminTrainingObjectives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(blank=True, help_text='Age group of the objective', max_length=30, null=True, verbose_name='Age')),
                ('name', models.CharField(blank=True, help_text='Objective name', max_length=255, null=True, verbose_name='Title')),
                ('variant', models.SmallIntegerField(default=0, help_text='Variant', verbose_name='Variant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
