# Generated by Django 4.0.4 on 2024-05-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0057_admintrainingblocks_admintrainingobjectives'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubtraining',
            name='goalkeepers_count',
            field=models.SmallIntegerField(default=0, help_text='Goalkeepers count', verbose_name='Goalkeepers count'),
        ),
        migrations.AddField(
            model_name='clubtraining',
            name='players_count',
            field=models.SmallIntegerField(default=0, help_text='Players count', verbose_name='Players count'),
        ),
        migrations.AddField(
            model_name='usertraining',
            name='goalkeepers_count',
            field=models.SmallIntegerField(default=0, help_text='Goalkeepers count', verbose_name='Goalkeepers count'),
        ),
        migrations.AddField(
            model_name='usertraining',
            name='players_count',
            field=models.SmallIntegerField(default=0, help_text='Players count', verbose_name='Players count'),
        ),
    ]
