# Generated by Django 4.0.4 on 2024-06-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0058_clubtraining_goalkeepers_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admintrainingblocks',
            name='archive',
            field=models.BooleanField(default=False, help_text='Is it a archive', verbose_name='Archive'),
        ),
        migrations.AddField(
            model_name='admintrainingobjectives',
            name='archive',
            field=models.BooleanField(default=False, help_text='Is it a archive', verbose_name='Archive'),
        ),
        migrations.AddField(
            model_name='clubtrainingblocks',
            name='archive',
            field=models.BooleanField(default=False, help_text='Is it a archive', verbose_name='Archive'),
        ),
        migrations.AddField(
            model_name='clubtrainingload',
            name='archive',
            field=models.BooleanField(default=False, help_text='Is it a archive', verbose_name='Archive'),
        ),
        migrations.AddField(
            model_name='clubtrainingobjectives',
            name='archive',
            field=models.BooleanField(default=False, help_text='Is it a archive', verbose_name='Archive'),
        ),
        migrations.AddField(
            model_name='usertrainingblocks',
            name='archive',
            field=models.BooleanField(default=False, help_text='Is it a archive', verbose_name='Archive'),
        ),
        migrations.AddField(
            model_name='usertrainingload',
            name='archive',
            field=models.BooleanField(default=False, help_text='Is it a archive', verbose_name='Archive'),
        ),
        migrations.AddField(
            model_name='usertrainingobjectives',
            name='archive',
            field=models.BooleanField(default=False, help_text='Is it a archive', verbose_name='Archive'),
        ),
        migrations.AlterField(
            model_name='admintrainingblocks',
            name='name',
            field=models.CharField(blank=True, help_text='Objective name', max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='admintrainingblocks',
            name='short_name',
            field=models.CharField(blank=True, help_text='Age group of the objective', max_length=30, null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='clubtrainingblocks',
            name='name',
            field=models.CharField(blank=True, help_text='Objective name', max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='clubtrainingblocks',
            name='short_name',
            field=models.CharField(blank=True, help_text='Age group of the objective', max_length=30, null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='clubtrainingload',
            name='name',
            field=models.CharField(blank=True, help_text='Objective name', max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='clubtrainingload',
            name='short_name',
            field=models.CharField(blank=True, help_text='Age group of the objective', max_length=30, null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='usertrainingblocks',
            name='name',
            field=models.CharField(blank=True, help_text='Objective name', max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='usertrainingblocks',
            name='short_name',
            field=models.CharField(blank=True, help_text='Age group of the objective', max_length=30, null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='usertrainingload',
            name='name',
            field=models.CharField(blank=True, help_text='Objective name', max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='usertrainingload',
            name='short_name',
            field=models.CharField(blank=True, help_text='Age group of the objective', max_length=30, null=True, verbose_name='Age'),
        ),
    ]
