# Generated by Django 4.0.4 on 2024-06-05 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0041_alter_clubseason_date_by_alter_clubseason_date_with_and_more'),
        ('trainings', '0059_admintrainingblocks_archive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubtrainingblocks',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Team', null=True, on_delete=django.db.models.deletion.CASCADE, to='references.clubteam', verbose_name='Team'),
        ),
        migrations.AddField(
            model_name='clubtrainingobjectives',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Team', null=True, on_delete=django.db.models.deletion.CASCADE, to='references.clubteam', verbose_name='Team'),
        ),
        migrations.AddField(
            model_name='usertrainingblocks',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Team', null=True, on_delete=django.db.models.deletion.CASCADE, to='references.clubteam', verbose_name='Team'),
        ),
        migrations.AddField(
            model_name='usertrainingobjectives',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Team', null=True, on_delete=django.db.models.deletion.CASCADE, to='references.userteam', verbose_name='Team'),
        ),
    ]
