# Generated by Django 4.0.4 on 2024-07-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0061_clubtraining_field_size_litetraining_field_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTrainingLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(blank=True, help_text='Age group of the objective', max_length=30, null=True, verbose_name='Age')),
                ('name', models.CharField(blank=True, help_text='Objective name', max_length=255, null=True, verbose_name='Title')),
                ('archive', models.BooleanField(default=False, help_text='Is it a archive', verbose_name='Archive')),
                ('variant', models.SmallIntegerField(default=0, help_text='Variant', verbose_name='Variant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
