# Generated by Django 4.0.4 on 2024-07-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0064_clubtraining_md_usertraining_md'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubtraining',
            name='objective_1',
            field=models.CharField(blank=True, help_text='The objective 1 in training', max_length=255, null=True, verbose_name='Objective 1'),
        ),
        migrations.AddField(
            model_name='clubtraining',
            name='objective_2',
            field=models.CharField(blank=True, help_text='The objective 2 in training', max_length=255, null=True, verbose_name='Objective 2'),
        ),
        migrations.AddField(
            model_name='litetraining',
            name='objective_1',
            field=models.CharField(blank=True, help_text='The objective 1 in training', max_length=255, null=True, verbose_name='Objective 1'),
        ),
        migrations.AddField(
            model_name='litetraining',
            name='objective_2',
            field=models.CharField(blank=True, help_text='The objective 2 in training', max_length=255, null=True, verbose_name='Objective 2'),
        ),
        migrations.AddField(
            model_name='usertraining',
            name='objective_1',
            field=models.CharField(blank=True, help_text='The objective 1 in training', max_length=255, null=True, verbose_name='Objective 1'),
        ),
        migrations.AddField(
            model_name='usertraining',
            name='objective_2',
            field=models.CharField(blank=True, help_text='The objective 2 in training', max_length=255, null=True, verbose_name='Objective 2'),
        ),
    ]
