# Generated by Django 4.0.4 on 2022-07-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('order', models.IntegerField(default=0, help_text='Индекс сортировки')),
                ('visible', models.BooleanField(default=True, help_text='Показывать упр-ие пользователю или нет')),
                ('completed', models.BooleanField(default=False, help_text='Упражнение завершено')),
                ('completed_time', models.DateField(blank=True, help_text='Когда упр-ие было завершено', null=True)),
                ('title', models.JSONField(blank=True, null=True)),
                ('ref_ball', models.IntegerField(blank=True, null=True)),
                ('ref_goal', models.IntegerField(blank=True, null=True)),
                ('ref_workout_part', models.IntegerField(blank=True, null=True)),
                ('ref_cognitive_load', models.IntegerField(blank=True, null=True)),
                ('ref_age_category', models.IntegerField(blank=True, null=True)),
                ('description', models.JSONField(blank=True, null=True)),
                ('players_amount', models.JSONField(blank=True, null=True)),
                ('keyword', models.JSONField(blank=True, null=True)),
                ('ref_source', models.IntegerField(blank=True, null=True)),
                ('condition', models.JSONField(blank=True, null=True)),
                ('stress_type', models.JSONField(blank=True, null=True)),
                ('purpose', models.JSONField(blank=True, null=True)),
                ('coaching', models.JSONField(blank=True, null=True)),
                ('notes', models.JSONField(blank=True, null=True)),
                ('scheme_data', models.JSONField(blank=True, null=True)),
                ('video_data', models.JSONField(blank=True, null=True)),
                ('animation_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdminFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Импортируемое название источника', max_length=255, null=True)),
                ('parent', models.IntegerField(blank=True, help_text='Ид папки родителя', null=True)),
                ('visible', models.BooleanField(default=True, help_text='Показывать папку пользователю или нет')),
                ('short_name', models.CharField(help_text='Короткий ключ для поиска', max_length=10)),
                ('order', models.IntegerField(default=0, help_text='Индекс сортировки')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClubExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('order', models.IntegerField(default=0, help_text='Индекс сортировки')),
                ('visible', models.BooleanField(default=True, help_text='Показывать упр-ие пользователю или нет')),
                ('completed', models.BooleanField(default=False, help_text='Упражнение завершено')),
                ('completed_time', models.DateField(blank=True, help_text='Когда упр-ие было завершено', null=True)),
                ('title', models.JSONField(blank=True, null=True)),
                ('ref_ball', models.IntegerField(blank=True, null=True)),
                ('ref_goal', models.IntegerField(blank=True, null=True)),
                ('ref_workout_part', models.IntegerField(blank=True, null=True)),
                ('ref_cognitive_load', models.IntegerField(blank=True, null=True)),
                ('ref_age_category', models.IntegerField(blank=True, null=True)),
                ('description', models.JSONField(blank=True, null=True)),
                ('players_amount', models.JSONField(blank=True, null=True)),
                ('keyword', models.JSONField(blank=True, null=True)),
                ('ref_source', models.IntegerField(blank=True, null=True)),
                ('condition', models.JSONField(blank=True, null=True)),
                ('stress_type', models.JSONField(blank=True, null=True)),
                ('purpose', models.JSONField(blank=True, null=True)),
                ('coaching', models.JSONField(blank=True, null=True)),
                ('notes', models.JSONField(blank=True, null=True)),
                ('scheme_data', models.JSONField(blank=True, null=True)),
                ('video_data', models.JSONField(blank=True, null=True)),
                ('animation_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClubFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Импортируемое название источника', max_length=255, null=True)),
                ('parent', models.IntegerField(blank=True, help_text='Ид папки родителя', null=True)),
                ('visible', models.BooleanField(default=True, help_text='Показывать папку пользователю или нет')),
                ('short_name', models.CharField(help_text='Короткий ключ для поиска', max_length=10)),
                ('order', models.IntegerField(default=0, help_text='Индекс сортировки')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('order', models.IntegerField(default=0, help_text='Индекс сортировки')),
                ('visible', models.BooleanField(default=True, help_text='Показывать упр-ие пользователю или нет')),
                ('completed', models.BooleanField(default=False, help_text='Упражнение завершено')),
                ('completed_time', models.DateField(blank=True, help_text='Когда упр-ие было завершено', null=True)),
                ('title', models.JSONField(blank=True, null=True)),
                ('ref_ball', models.IntegerField(blank=True, null=True)),
                ('ref_goal', models.IntegerField(blank=True, null=True)),
                ('ref_workout_part', models.IntegerField(blank=True, null=True)),
                ('ref_cognitive_load', models.IntegerField(blank=True, null=True)),
                ('ref_age_category', models.IntegerField(blank=True, null=True)),
                ('description', models.JSONField(blank=True, null=True)),
                ('players_amount', models.JSONField(blank=True, null=True)),
                ('keyword', models.JSONField(blank=True, null=True)),
                ('ref_source', models.IntegerField(blank=True, null=True)),
                ('condition', models.JSONField(blank=True, null=True)),
                ('stress_type', models.JSONField(blank=True, null=True)),
                ('purpose', models.JSONField(blank=True, null=True)),
                ('coaching', models.JSONField(blank=True, null=True)),
                ('notes', models.JSONField(blank=True, null=True)),
                ('scheme_data', models.JSONField(blank=True, null=True)),
                ('video_data', models.JSONField(blank=True, null=True)),
                ('animation_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Импортируемое название источника', max_length=255, null=True)),
                ('parent', models.IntegerField(blank=True, help_text='Ид папки родителя', null=True)),
                ('visible', models.BooleanField(default=True, help_text='Показывать папку пользователю или нет')),
                ('short_name', models.CharField(help_text='Короткий ключ для поиска', max_length=10)),
                ('order', models.IntegerField(default=0, help_text='Индекс сортировки')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
    ]
