# Generated by Django 4.0.4 on 2022-05-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminfolder',
            name='order',
            field=models.IntegerField(default=0, help_text='Индекс сортировки'),
        ),
        migrations.AlterField(
            model_name='clubfolder',
            name='order',
            field=models.IntegerField(default=0, help_text='Индекс сортировки'),
        ),
        migrations.AlterField(
            model_name='userfolder',
            name='order',
            field=models.IntegerField(default=0, help_text='Индекс сортировки'),
        ),
    ]
