# Generated by Django 4.0.4 on 2022-07-19 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminexercise',
            name='ref_source',
        ),
        migrations.RemoveField(
            model_name='adminexercise',
            name='ref_workout_part',
        ),
        migrations.RemoveField(
            model_name='clubexercise',
            name='ref_source',
        ),
        migrations.RemoveField(
            model_name='clubexercise',
            name='ref_workout_part',
        ),
        migrations.RemoveField(
            model_name='userexercise',
            name='ref_source',
        ),
        migrations.RemoveField(
            model_name='userexercise',
            name='ref_workout_part',
        ),
        migrations.AddField(
            model_name='adminexercise',
            name='players_ages',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.int_list_validator]),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='players_ages',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.int_list_validator]),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='players_ages',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.int_list_validator]),
        ),
        migrations.AlterField(
            model_name='adminexercise',
            name='players_amount',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.int_list_validator]),
        ),
        migrations.AlterField(
            model_name='clubexercise',
            name='players_amount',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.int_list_validator]),
        ),
        migrations.AlterField(
            model_name='userexercise',
            name='players_amount',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.int_list_validator]),
        ),
    ]
