# Generated by Django 4.0.4 on 2022-06-03 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_alter_adminfolder_order_alter_clubfolder_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfolder',
            options={'ordering': ['order', 'id']},
        ),
    ]
