# Generated by Django 4.0.4 on 2022-07-19 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_remove_adminexercise_ref_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminexercise',
            name='players_ages',
        ),
        migrations.RemoveField(
            model_name='adminexercise',
            name='players_amount',
        ),
        migrations.RemoveField(
            model_name='clubexercise',
            name='players_ages',
        ),
        migrations.RemoveField(
            model_name='clubexercise',
            name='players_amount',
        ),
        migrations.RemoveField(
            model_name='userexercise',
            name='players_ages',
        ),
        migrations.RemoveField(
            model_name='userexercise',
            name='players_amount',
        ),
    ]
