# Generated by Django 4.0.4 on 2022-07-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_remove_adminexercise_players_ages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminexercise',
            name='players_ages',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminexercise',
            name='players_amount',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='players_ages',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='players_amount',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='players_ages',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='players_amount',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
