# Generated by Django 4.0.4 on 2022-07-20 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0005_exsaddition'),
        ('exercises', '0005_adminexercise_players_ages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfolder',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='references.userteam'),
        ),
    ]
