# Generated by Django 4.0.4 on 2022-07-21 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0005_exsaddition'),
        ('exercises', '0007_userexerciseparam'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExerciseParamTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addition', models.JSONField(blank=True, null=True)),
                ('purpose', models.JSONField(blank=True, null=True)),
                ('stress_type', models.JSONField(blank=True, null=True)),
                ('coaching', models.JSONField(blank=True, null=True)),
                ('exercise_club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exercises.clubexercise')),
                ('exercise_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exercises.userexercise')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.userteam')),
            ],
        ),
    ]
