# Generated by Django 4.0.4 on 2022-06-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0007_exercises_remove_adminfolder_hide_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisesparams',
            name='ref_focuses',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
