# Generated by Django 4.0.4 on 2022-06-16 10:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0008_alter_exercisesparams_ref_focuses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exercises',
            new_name='Exercise',
        ),
        migrations.RenameModel(
            old_name='ExercisesParams',
            new_name='ExerciseParams',
        ),
        migrations.RenameModel(
            old_name='ExercisesTranslations',
            new_name='ExerciseTranslations',
        ),
        migrations.RenameModel(
            old_name='ExercisesVisual',
            new_name='ExerciseVisual',
        ),
    ]
