# Generated by Django 4.0.4 on 2022-07-27 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0005_exsaddition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0008_userexerciseparamteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexerciseparam',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userexerciseparamteam',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.userteam'),
        ),
    ]
