# Generated by Django 4.0.4 on 2022-06-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0009_rename_exercises_exercise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='completed_time',
            field=models.DateField(help_text='Когда упр-ие было завершено', null=True),
        ),
    ]
