# Generated by Django 4.0.4 on 2022-08-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0010_remove_adminexercise_coaching_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexerciseparam',
            name='animation_1_watched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userexerciseparam',
            name='animation_2_watched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userexerciseparam',
            name='video_1_watched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userexerciseparam',
            name='video_2_watched',
            field=models.BooleanField(default=False),
        ),
    ]
