# Generated by Django 4.0.4 on 2022-06-16 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0011_alter_exercise_folder_club_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseparams',
            name='exercise_id',
        ),
        migrations.RemoveField(
            model_name='exercisetranslations',
            name='exercise_id',
        ),
        migrations.RemoveField(
            model_name='exercisevisual',
            name='exercise_id',
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.DeleteModel(
            name='ExerciseParams',
        ),
        migrations.DeleteModel(
            name='ExerciseTranslations',
        ),
        migrations.DeleteModel(
            name='ExerciseVisual',
        ),
    ]
