# Generated by Django 4.0.4 on 2022-08-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0011_userexerciseparam_animation_1_watched_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userexerciseparamteam',
            name='ball_touch',
        ),
        migrations.RemoveField(
            model_name='userexerciseparamteam',
            name='group',
        ),
        migrations.RemoveField(
            model_name='userexerciseparamteam',
            name='neutral',
        ),
        migrations.RemoveField(
            model_name='userexerciseparamteam',
            name='play_zone',
        ),
        migrations.RemoveField(
            model_name='userexerciseparamteam',
            name='player',
        ),
        migrations.RemoveField(
            model_name='userexerciseparamteam',
            name='t_pause',
        ),
        migrations.RemoveField(
            model_name='userexerciseparamteam',
            name='t_repeat',
        ),
        migrations.AddField(
            model_name='userexerciseparamteam',
            name='additional_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
