# Generated by Django 4.0.4 on 2022-08-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0012_remove_userexerciseparamteam_ball_touch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminexercise',
            name='clone_nfb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminexercise',
            name='old_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='clone_nfb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='old_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='clone_nfb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='old_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
