# Generated by Django 4.0.4 on 2022-06-16 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0012_remove_exerciseparams_exercise_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('order', models.IntegerField(default=0, help_text='Индекс сортировки')),
                ('visible', models.BooleanField(default=True, help_text='Показывать упр-ие пользователю или нет')),
                ('completed', models.BooleanField(default=False, help_text='Упражнение завершено')),
                ('completed_time', models.DateField(help_text='Когда упр-ие было завершено', null=True)),
                ('folder_club_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exercises.clubfolder')),
                ('folder_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exercises.userfolder')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseVisual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_data', models.JSONField()),
                ('video_data', models.JSONField()),
                ('animation_data', models.JSONField()),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseTranslations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(default='en', max_length=6)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_age_a', models.IntegerField(blank=True, null=True)),
                ('ref_age_b', models.IntegerField(blank=True, null=True)),
                ('ref_ball', models.IntegerField(blank=True, null=True)),
                ('ref_goal', models.IntegerField(blank=True, null=True)),
                ('ref_cognitive_load', models.IntegerField(blank=True, null=True)),
                ('ref_workout_part', models.IntegerField(blank=True, null=True)),
                ('ref_stress', models.IntegerField(blank=True, null=True)),
                ('ref_focuses', models.IntegerField(blank=True, null=True)),
                ('partners', models.BooleanField(default=False)),
                ('opponents', models.BooleanField(default=False)),
                ('player_text', models.CharField(blank=True, max_length=255, null=True)),
                ('zone_text', models.CharField(blank=True, max_length=255, null=True)),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise')),
            ],
        ),
    ]
