# Generated by Django 4.0.4 on 2022-08-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0013_adminexercise_clone_nfb_id_adminexercise_old_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminexercise',
            name='filter_favorite',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminexercise',
            name='filter_watched',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='filter_favorite',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='filter_watched',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='filter_favorite',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='filter_watched',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
