# Generated by Django 4.0.4 on 2022-06-16 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0013_exercise_exercisevisual_exercisetranslations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='folder_club_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exercises.clubfolder'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='folder_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exercises.userfolder'),
        ),
    ]
