# Generated by Django 4.0.4 on 2022-08-19 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0014_adminexercise_filter_favorite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminexercise',
            name='filter_favorite',
        ),
        migrations.RemoveField(
            model_name='adminexercise',
            name='filter_watched',
        ),
        migrations.RemoveField(
            model_name='clubexercise',
            name='filter_favorite',
        ),
        migrations.RemoveField(
            model_name='clubexercise',
            name='filter_watched',
        ),
        migrations.RemoveField(
            model_name='userexercise',
            name='filter_favorite',
        ),
        migrations.RemoveField(
            model_name='userexercise',
            name='filter_watched',
        ),
    ]
