# Generated by Django 4.0.4 on 2022-06-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0014_alter_exercise_folder_club_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='completed_time',
            field=models.DateField(blank=True, help_text='Когда упр-ие было завершено', null=True),
        ),
    ]
