# Generated by Django 4.0.4 on 2022-06-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0015_alter_exercise_completed_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseparams',
            name='opponents',
        ),
        migrations.RemoveField(
            model_name='exerciseparams',
            name='partners',
        ),
        migrations.RemoveField(
            model_name='exerciseparams',
            name='player_text',
        ),
        migrations.RemoveField(
            model_name='exerciseparams',
            name='ref_age_a',
        ),
        migrations.RemoveField(
            model_name='exerciseparams',
            name='ref_age_b',
        ),
        migrations.RemoveField(
            model_name='exerciseparams',
            name='zone_text',
        ),
        migrations.AddField(
            model_name='exerciseparams',
            name='neutral',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exerciseparams',
            name='pauses',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exerciseparams',
            name='play_zone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exerciseparams',
            name='players_amount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exerciseparams',
            name='ref_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exerciseparams',
            name='ref_category',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exerciseparams',
            name='ref_exs_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exerciseparams',
            name='ref_folders',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exerciseparams',
            name='ref_infrastructure',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exerciseparams',
            name='ref_players_format',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exerciseparams',
            name='touches_amount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
