# Generated by Django 4.0.4 on 2022-08-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0015_remove_adminexercise_filter_favorite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminexercise',
            name='type',
            field=models.CharField(default='nfb', editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='type',
            field=models.CharField(default='club', editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='type',
            field=models.CharField(default='user', editable=False, max_length=10),
        ),
    ]
