# Generated by Django 4.0.4 on 2022-08-20 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0016_adminexercise_type_clubexercise_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminexercise',
            name='type',
        ),
        migrations.RemoveField(
            model_name='clubexercise',
            name='type',
        ),
        migrations.RemoveField(
            model_name='userexercise',
            name='type',
        ),
    ]
