# Generated by Django 4.0.4 on 2022-06-20 11:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0016_remove_exerciseparams_opponents_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('order', models.IntegerField(default=0, help_text='Индекс сортировки')),
                ('visible', models.BooleanField(default=True, help_text='Показывать упр-ие пользователю или нет')),
                ('completed', models.BooleanField(default=False, help_text='Упражнение завершено')),
                ('completed_time', models.DateField(blank=True, help_text='Когда упр-ие было завершено', null=True)),
                ('ref_ball', models.IntegerField(blank=True, null=True)),
                ('ref_goal', models.IntegerField(blank=True, null=True)),
                ('ref_players_format', models.IntegerField(blank=True, null=True)),
                ('ref_workout_part', models.IntegerField(blank=True, null=True)),
                ('ref_cognitive_load', models.IntegerField(blank=True, null=True)),
                ('ref_category', models.IntegerField(blank=True, null=True)),
                ('age', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.int_list_validator])),
                ('players_amount', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.int_list_validator])),
                ('play_zone', models.CharField(blank=True, max_length=1024, null=True)),
                ('neutral', models.CharField(blank=True, max_length=1024, null=True)),
                ('touches_amount', models.CharField(blank=True, max_length=1024, null=True)),
                ('series', models.CharField(blank=True, max_length=1024, null=True)),
                ('pauses', models.CharField(blank=True, max_length=1024, null=True)),
                ('notes', models.CharField(blank=True, max_length=1024, null=True)),
                ('title', models.CharField(blank=True, max_length=1024, null=True)),
                ('description', models.CharField(blank=True, max_length=2048, null=True)),
                ('coaching', models.CharField(blank=True, max_length=1024, null=True)),
                ('scheme_data', models.JSONField()),
                ('video_data', models.JSONField()),
                ('animation_data', models.JSONField()),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.adminfolder')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClubExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('order', models.IntegerField(default=0, help_text='Индекс сортировки')),
                ('visible', models.BooleanField(default=True, help_text='Показывать упр-ие пользователю или нет')),
                ('completed', models.BooleanField(default=False, help_text='Упражнение завершено')),
                ('completed_time', models.DateField(blank=True, help_text='Когда упр-ие было завершено', null=True)),
                ('ref_ball', models.IntegerField(blank=True, null=True)),
                ('ref_goal', models.IntegerField(blank=True, null=True)),
                ('ref_players_format', models.IntegerField(blank=True, null=True)),
                ('ref_workout_part', models.IntegerField(blank=True, null=True)),
                ('ref_cognitive_load', models.IntegerField(blank=True, null=True)),
                ('ref_category', models.IntegerField(blank=True, null=True)),
                ('age', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.int_list_validator])),
                ('players_amount', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.int_list_validator])),
                ('play_zone', models.CharField(blank=True, max_length=1024, null=True)),
                ('neutral', models.CharField(blank=True, max_length=1024, null=True)),
                ('touches_amount', models.CharField(blank=True, max_length=1024, null=True)),
                ('series', models.CharField(blank=True, max_length=1024, null=True)),
                ('pauses', models.CharField(blank=True, max_length=1024, null=True)),
                ('notes', models.CharField(blank=True, max_length=1024, null=True)),
                ('title', models.CharField(blank=True, max_length=1024, null=True)),
                ('description', models.CharField(blank=True, max_length=2048, null=True)),
                ('coaching', models.CharField(blank=True, max_length=1024, null=True)),
                ('scheme_data', models.JSONField()),
                ('video_data', models.JSONField()),
                ('animation_data', models.JSONField()),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.clubfolder')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('order', models.IntegerField(default=0, help_text='Индекс сортировки')),
                ('visible', models.BooleanField(default=True, help_text='Показывать упр-ие пользователю или нет')),
                ('completed', models.BooleanField(default=False, help_text='Упражнение завершено')),
                ('completed_time', models.DateField(blank=True, help_text='Когда упр-ие было завершено', null=True)),
                ('ref_ball', models.IntegerField(blank=True, null=True)),
                ('ref_goal', models.IntegerField(blank=True, null=True)),
                ('ref_players_format', models.IntegerField(blank=True, null=True)),
                ('ref_workout_part', models.IntegerField(blank=True, null=True)),
                ('ref_cognitive_load', models.IntegerField(blank=True, null=True)),
                ('ref_category', models.IntegerField(blank=True, null=True)),
                ('age', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.int_list_validator])),
                ('players_amount', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.int_list_validator])),
                ('play_zone', models.CharField(blank=True, max_length=1024, null=True)),
                ('neutral', models.CharField(blank=True, max_length=1024, null=True)),
                ('touches_amount', models.CharField(blank=True, max_length=1024, null=True)),
                ('series', models.CharField(blank=True, max_length=1024, null=True)),
                ('pauses', models.CharField(blank=True, max_length=1024, null=True)),
                ('notes', models.CharField(blank=True, max_length=1024, null=True)),
                ('title', models.CharField(blank=True, max_length=1024, null=True)),
                ('description', models.CharField(blank=True, max_length=2048, null=True)),
                ('coaching', models.CharField(blank=True, max_length=1024, null=True)),
                ('scheme_data', models.JSONField()),
                ('video_data', models.JSONField()),
                ('animation_data', models.JSONField()),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.userfolder')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='exerciseparams',
            name='exercise_id',
        ),
        migrations.RemoveField(
            model_name='exercisetranslations',
            name='exercise_id',
        ),
        migrations.RemoveField(
            model_name='exercisevisual',
            name='exercise_id',
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.DeleteModel(
            name='ExerciseParams',
        ),
        migrations.DeleteModel(
            name='ExerciseTranslations',
        ),
        migrations.DeleteModel(
            name='ExerciseVisual',
        ),
    ]
