# Generated by Django 4.0.4 on 2022-06-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0017_adminexercise_clubexercise_userexercise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminexercise',
            name='coaching',
        ),
        migrations.RemoveField(
            model_name='adminexercise',
            name='description',
        ),
        migrations.RemoveField(
            model_name='adminexercise',
            name='neutral',
        ),
        migrations.RemoveField(
            model_name='adminexercise',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='adminexercise',
            name='pauses',
        ),
        migrations.RemoveField(
            model_name='adminexercise',
            name='play_zone',
        ),
        migrations.RemoveField(
            model_name='adminexercise',
            name='series',
        ),
        migrations.RemoveField(
            model_name='adminexercise',
            name='title',
        ),
        migrations.RemoveField(
            model_name='adminexercise',
            name='touches_amount',
        ),
        migrations.RemoveField(
            model_name='clubexercise',
            name='coaching',
        ),
        migrations.RemoveField(
            model_name='clubexercise',
            name='description',
        ),
        migrations.RemoveField(
            model_name='clubexercise',
            name='neutral',
        ),
        migrations.RemoveField(
            model_name='clubexercise',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='clubexercise',
            name='pauses',
        ),
        migrations.RemoveField(
            model_name='clubexercise',
            name='play_zone',
        ),
        migrations.RemoveField(
            model_name='clubexercise',
            name='series',
        ),
        migrations.RemoveField(
            model_name='clubexercise',
            name='title',
        ),
        migrations.RemoveField(
            model_name='clubexercise',
            name='touches_amount',
        ),
        migrations.RemoveField(
            model_name='userexercise',
            name='coaching',
        ),
        migrations.RemoveField(
            model_name='userexercise',
            name='description',
        ),
        migrations.RemoveField(
            model_name='userexercise',
            name='neutral',
        ),
        migrations.RemoveField(
            model_name='userexercise',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='userexercise',
            name='pauses',
        ),
        migrations.RemoveField(
            model_name='userexercise',
            name='play_zone',
        ),
        migrations.RemoveField(
            model_name='userexercise',
            name='series',
        ),
        migrations.RemoveField(
            model_name='userexercise',
            name='title',
        ),
        migrations.RemoveField(
            model_name='userexercise',
            name='touches_amount',
        ),
        migrations.AlterField(
            model_name='adminexercise',
            name='animation_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminexercise',
            name='scheme_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminexercise',
            name='video_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clubexercise',
            name='animation_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clubexercise',
            name='scheme_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clubexercise',
            name='video_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userexercise',
            name='animation_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userexercise',
            name='scheme_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userexercise',
            name='video_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
