# Generated by Django 4.0.4 on 2022-08-24 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0017_remove_adminexercise_type_remove_clubexercise_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexerciseparam',
            name='exercise_nfb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exercises.adminexercise'),
        ),
        migrations.AddField(
            model_name='userexerciseparamteam',
            name='exercise_nfb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exercises.adminexercise'),
        ),
    ]
