# Generated by Django 4.0.4 on 2022-06-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0018_remove_adminexercise_coaching_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminexercise',
            name='coaching',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminexercise',
            name='description',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminexercise',
            name='neutral',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminexercise',
            name='notes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminexercise',
            name='pauses',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminexercise',
            name='play_zone',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminexercise',
            name='series',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminexercise',
            name='title',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminexercise',
            name='touches_amount',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='coaching',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='description',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='neutral',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='notes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='pauses',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='play_zone',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='series',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='title',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='touches_amount',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='coaching',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='description',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='neutral',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='notes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='pauses',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='play_zone',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='series',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='title',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='touches_amount',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
