# Generated by Django 4.0.4 on 2022-09-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0018_userexerciseparam_exercise_nfb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminfolder',
            name='name',
            field=models.CharField(blank=True, help_text='Импортируемое название папки', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clubfolder',
            name='name',
            field=models.CharField(blank=True, help_text='Импортируемое название папки', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userfolder',
            name='name',
            field=models.CharField(blank=True, help_text='Импортируемое название папки', max_length=255, null=True),
        ),
    ]
