# Generated by Django 4.0.4 on 2022-06-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0019_adminexercise_coaching_adminexercise_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminexercise',
            name='coaching',
        ),
        migrations.RemoveField(
            model_name='adminexercise',
            name='neutral',
        ),
        migrations.RemoveField(
            model_name='adminexercise',
            name='ref_players_format',
        ),
        migrations.RemoveField(
            model_name='clubexercise',
            name='coaching',
        ),
        migrations.RemoveField(
            model_name='clubexercise',
            name='neutral',
        ),
        migrations.RemoveField(
            model_name='clubexercise',
            name='ref_players_format',
        ),
        migrations.RemoveField(
            model_name='userexercise',
            name='coaching',
        ),
        migrations.RemoveField(
            model_name='userexercise',
            name='neutral',
        ),
        migrations.RemoveField(
            model_name='userexercise',
            name='ref_players_format',
        ),
        migrations.AddField(
            model_name='adminexercise',
            name='iterations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminexercise',
            name='organization',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminexercise',
            name='ref_coaching',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminexercise',
            name='ref_purpose',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminexercise',
            name='ref_stress_type',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='iterations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='organization',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='ref_coaching',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='ref_purpose',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='ref_stress_type',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='iterations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='organization',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='ref_coaching',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='ref_purpose',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='ref_stress_type',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminexercise',
            name='players_amount',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clubexercise',
            name='players_amount',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userexercise',
            name='players_amount',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
