# Generated by Django 4.0.4 on 2022-10-22 06:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0012_alter_video_taggit'),
        ('exercises', '0021_exercisevideo_animation_1_exercisevideo_animation_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminexercise',
            name='videos',
            field=models.ManyToManyField(through='exercises.ExerciseVideo', to='video.video'),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='videos',
            field=models.ManyToManyField(through='exercises.ExerciseVideo', to='video.video'),
        ),
        migrations.AddField(
            model_name='exercisevideo',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exercisevideo',
            name='type',
            field=models.IntegerField(default=0, help_text='0 - видео, 1 - анимация', validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='exercisevideo',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video', to='video.video'),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='videos',
            field=models.ManyToManyField(through='exercises.ExerciseVideo', to='video.video'),
        ),
    ]
