# Generated by Django 4.0.4 on 2022-06-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0021_remove_adminexercise_players_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminexercise',
            name='players_amount',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='players_amount',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='players_amount',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
