# Generated by Django 4.0.4 on 2022-06-29 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0022_adminexercise_players_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userexercise',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='userfolder',
            name='user_id',
        ),
        migrations.AddField(
            model_name='userexercise',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userfolder',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
