# Generated by Django 4.0.4 on 2022-10-22 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0023_alter_exercisevideo_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminexercise',
            name='videos',
        ),
        migrations.RemoveField(
            model_name='clubexercise',
            name='videos',
        ),
        migrations.RemoveField(
            model_name='userexercise',
            name='videos',
        ),
    ]
