# Generated by Django 4.0.4 on 2022-10-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0012_alter_video_taggit'),
        ('exercises', '0024_remove_adminexercise_videos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminexercise',
            name='videos',
            field=models.ManyToManyField(through='exercises.ExerciseVideo', to='video.video'),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='videos',
            field=models.ManyToManyField(through='exercises.ExerciseVideo', to='video.video'),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='videos',
            field=models.ManyToManyField(through='exercises.ExerciseVideo', to='video.video'),
        ),
    ]
