# Generated by Django 4.0.4 on 2022-10-22 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0025_adminexercise_videos_clubexercise_videos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminexercise',
            name='videos',
        ),
        migrations.RemoveField(
            model_name='clubexercise',
            name='videos',
        ),
        migrations.RemoveField(
            model_name='exercisevideo',
            name='exercise_club',
        ),
        migrations.RemoveField(
            model_name='exercisevideo',
            name='exercise_nfb',
        ),
        migrations.RemoveField(
            model_name='exercisevideo',
            name='exercise_user',
        ),
        migrations.RemoveField(
            model_name='userexercise',
            name='videos',
        ),
    ]
