# Generated by Django 4.0.4 on 2022-10-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0026_remove_adminexercise_videos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminexercise',
            name='videos',
            field=models.ManyToManyField(to='exercises.exercisevideo'),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='videos',
            field=models.ManyToManyField(to='exercises.exercisevideo'),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='videos',
            field=models.ManyToManyField(to='exercises.exercisevideo'),
        ),
    ]
