# Generated by Django 4.0.4 on 2022-10-22 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0027_adminexercise_videos_clubexercise_videos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisevideo',
            name='animation_1',
        ),
        migrations.RemoveField(
            model_name='exercisevideo',
            name='animation_2',
        ),
        migrations.RemoveField(
            model_name='exercisevideo',
            name='video_1',
        ),
        migrations.RemoveField(
            model_name='exercisevideo',
            name='video_2',
        ),
    ]
