# Generated by Django 4.0.4 on 2022-10-26 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0015_alter_clubseason_options_alter_clubteam_options_and_more'),
        ('exercises', '0028_remove_exercisevideo_animation_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminexercise',
            name='ref_age_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.exsagecategory'),
        ),
        migrations.AlterField(
            model_name='adminexercise',
            name='ref_ball',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.exsball'),
        ),
        migrations.AlterField(
            model_name='adminexercise',
            name='ref_cognitive_load',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.exscognitiveload'),
        ),
        migrations.AlterField(
            model_name='adminexercise',
            name='ref_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.exsgoal'),
        ),
        migrations.AlterField(
            model_name='adminexercise',
            name='ref_team_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.exsteamcategory'),
        ),
        migrations.AlterField(
            model_name='adminexercise',
            name='ref_train_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.exstrainpart'),
        ),
        migrations.AlterField(
            model_name='clubexercise',
            name='ref_age_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.exsagecategory'),
        ),
        migrations.AlterField(
            model_name='clubexercise',
            name='ref_ball',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.exsball'),
        ),
        migrations.AlterField(
            model_name='clubexercise',
            name='ref_cognitive_load',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.exscognitiveload'),
        ),
        migrations.AlterField(
            model_name='clubexercise',
            name='ref_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.exsgoal'),
        ),
        migrations.AlterField(
            model_name='clubexercise',
            name='ref_team_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.exsteamcategory'),
        ),
        migrations.AlterField(
            model_name='clubexercise',
            name='ref_train_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.exstrainpart'),
        ),
        migrations.AlterField(
            model_name='userexercise',
            name='ref_age_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.exsagecategory'),
        ),
        migrations.AlterField(
            model_name='userexercise',
            name='ref_ball',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.exsball'),
        ),
        migrations.AlterField(
            model_name='userexercise',
            name='ref_cognitive_load',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.exscognitiveload'),
        ),
        migrations.AlterField(
            model_name='userexercise',
            name='ref_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.exsgoal'),
        ),
        migrations.AlterField(
            model_name='userexercise',
            name='ref_team_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.exsteamcategory'),
        ),
        migrations.AlterField(
            model_name='userexercise',
            name='ref_train_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.exstrainpart'),
        ),
    ]
