# Generated by Django 4.0.4 on 2022-10-27 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0029_alter_adminexercise_ref_age_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminexercise',
            name='videos',
        ),
        migrations.RemoveField(
            model_name='clubexercise',
            name='videos',
        ),
        migrations.RemoveField(
            model_name='userexercise',
            name='videos',
        ),
    ]
