# Generated by Django 4.0.4 on 2022-10-27 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0012_alter_video_taggit'),
        ('exercises', '0030_remove_adminexercise_videos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminexercise',
            name='videos',
            field=models.ManyToManyField(through='exercises.ExerciseVideo', to='video.video'),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='videos',
            field=models.ManyToManyField(through='exercises.ExerciseVideo', to='video.video'),
        ),
        migrations.AddField(
            model_name='exercisevideo',
            name='exercise_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exercises.clubexercise'),
        ),
        migrations.AddField(
            model_name='exercisevideo',
            name='exercise_nfb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exercises.adminexercise'),
        ),
        migrations.AddField(
            model_name='exercisevideo',
            name='exercise_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exercises.userexercise'),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='videos',
            field=models.ManyToManyField(through='exercises.ExerciseVideo', to='video.video'),
        ),
    ]
