# Generated by Django 4.0.4 on 2022-11-25 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0018_alter_clubteam_users'),
        ('exercises', '0034_clubfolder_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubexercise',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='references.clubteam'),
        ),
    ]
