# Generated by Django 4.0.4 on 2022-11-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0035_clubexercise_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminfolder',
            name='active',
            field=models.BooleanField(default=True, help_text='Показывать папку любому пользователю на релизе, неактивные папки доступны администрации.'),
        ),
    ]
