# Generated by Django 4.0.4 on 2022-11-25 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0018_alter_clubteam_users'),
        ('exercises', '0036_adminfolder_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexerciseparamteam',
            name='team_club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.clubteam'),
        ),
    ]
