# Generated by Django 4.0.4 on 2022-12-08 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_alter_club_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0037_userexerciseparamteam_team_club'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Imported source name', max_length=255, null=True, verbose_name='title')),
                ('short_name', models.CharField(default='Empty', help_text='Short name no more than 10 characters', max_length=10, verbose_name='short name')),
                ('order', models.IntegerField(default=0, help_text='Sorting index', verbose_name='order')),
                ('lowercase_name', models.CharField(blank=True, help_text='', max_length=255, null=True, verbose_name='lowercase title')),
                ('is_nfb', models.BooleanField(default=False)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.club')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom tags',
                'verbose_name_plural': 'Custom tags',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='adminexercise',
            name='tags',
            field=models.ManyToManyField(to='exercises.exercisetag'),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='tags',
            field=models.ManyToManyField(to='exercises.exercisetag'),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='tags',
            field=models.ManyToManyField(to='exercises.exercisetag'),
        ),
    ]
