# Generated by Django 4.0.4 on 2022-12-12 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0003_alter_club_options'),
        ('exercises', '0040_alter_exercisetag_lowercase_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminExerciseAdditionalParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.JSONField(blank=True, null=True)),
                ('order', models.IntegerField(default=0, help_text='Индекс сортировки')),
                ('visible', models.BooleanField(default=True, help_text='Показывать параметр пользователю или нет')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='exercisetag',
            name='lowercase_name',
            field=models.CharField(help_text='', max_length=255, unique=True, verbose_name='lowercase title'),
        ),
        migrations.CreateModel(
            name='UserExerciseAdditionalParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='Индекс сортировки')),
                ('visible', models.BooleanField(default=True, help_text='Показывать параметр пользователю или нет')),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.adminexerciseadditionalparams')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ClubExerciseAdditionalParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='Индекс сортировки')),
                ('visible', models.BooleanField(default=True, help_text='Показывать параметр пользователю или нет')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.adminexerciseadditionalparams')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='adminexercise',
            name='additional_params',
            field=models.ManyToManyField(to='exercises.adminexerciseadditionalparams'),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='additional_params',
            field=models.ManyToManyField(to='exercises.clubexerciseadditionalparams'),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='additional_params',
            field=models.ManyToManyField(to='exercises.userexerciseadditionalparams'),
        ),
    ]
