# Generated by Django 4.0.4 on 2022-12-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0043_remove_adminexercise_additional_params_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminexercise',
            name='additional_params',
            field=models.ManyToManyField(through='exercises.ExerciseAdditionalParamValue', to='exercises.adminexerciseadditionalparams'),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='additional_params',
            field=models.ManyToManyField(through='exercises.ExerciseAdditionalParamValue', to='exercises.clubexerciseadditionalparams'),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='additional_params',
            field=models.ManyToManyField(through='exercises.ExerciseAdditionalParamValue', to='exercises.userexerciseadditionalparams'),
        ),
        migrations.AlterField(
            model_name='exercisetag',
            name='lowercase_name',
            field=models.CharField(help_text='', max_length=255, unique=True, verbose_name='lowercase title'),
        ),
    ]
