# Generated by Django 4.0.4 on 2022-12-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0044_adminexercise_additional_params_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminexercise',
            name='additional_params',
        ),
        migrations.RemoveField(
            model_name='clubexercise',
            name='additional_params',
        ),
        migrations.RemoveField(
            model_name='userexercise',
            name='additional_params',
        ),
        migrations.AlterField(
            model_name='exercisetag',
            name='lowercase_name',
            field=models.CharField(help_text='', max_length=255, unique=True, verbose_name='lowercase title'),
        ),
        migrations.DeleteModel(
            name='ExerciseAdditionalParamValue',
        ),
    ]
