# Generated by Django 4.0.4 on 2022-12-21 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0018_alter_clubteam_users'),
        ('exercises', '0054_alter_exercisetag_lowercase_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminexercise',
            name='field_age',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminexercise',
            name='ref_stress_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.exsstresstype'),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='field_age',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='ref_stress_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.exsstresstype'),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='field_age',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='ref_stress_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.exsstresstype'),
        ),
        migrations.AlterField(
            model_name='exercisetag',
            name='lowercase_name',
            field=models.CharField(help_text='', max_length=255, unique=True, verbose_name='lowercase title'),
        ),
    ]
