# Generated by Django 4.0.4 on 2022-12-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0056_alter_exercisetag_lowercase_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisetag',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='exercisetag',
            name='visible',
        ),
        migrations.AlterField(
            model_name='exercisetag',
            name='lowercase_name',
            field=models.CharField(help_text='', max_length=255, unique=True, verbose_name='lowercase title'),
        ),
    ]
