# Generated by Django 4.0.4 on 2022-12-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0059_adminexercise_scheme_1_adminexercise_scheme_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisetag',
            name='lowercase_name',
            field=models.CharField(help_text='lowercase title', max_length=255, unique=True, verbose_name='lowercase title'),
        ),
    ]
