# Generated by Django 4.0.4 on 2022-12-24 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0005_remove_club_limits_club_player_limit_club_team_limit_and_more'),
        ('exercises', '0060_exercisetag_visible_alter_exercisetag_club_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisetag',
            name='lowercase_name',
            field=models.CharField(help_text='', max_length=255, unique=True, verbose_name='lowercase title'),
        ),
        migrations.CreateModel(
            name='ExerciseTagCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Imported source name', max_length=255, null=True, verbose_name='title')),
                ('short_name', models.CharField(default='Empty', help_text='Short name no more than 10 characters', max_length=10, verbose_name='short name')),
                ('order', models.IntegerField(default=0, help_text='Sorting index', verbose_name='order')),
                ('lowercase_name', models.CharField(help_text='', max_length=255, unique=True, verbose_name='lowercase title')),
                ('is_nfb', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=True)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.club')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom tags',
                'verbose_name_plural': 'Custom tags',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='exercisetag',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exercises.exercisetagcategory'),
        ),
        migrations.DeleteModel(
            name='ExerciseTagCategody',
        ),
    ]
