# Generated by Django 4.0.4 on 2022-12-25 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0060_alter_exercisetag_lowercase_name'),
        ('exercises', '0062_remove_exercisetagcategory_lowercase_name_and_more'),
    ]

    operations = [
    ]
