# Generated by Django 4.0.4 on 2022-12-26 10:15

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0063_merge_20221225_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisetagcategory',
            name='color',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=18, samples=None),
        ),
    ]
