# Generated by Django 4.0.4 on 2023-01-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0064_exercisetagcategory_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminexercise',
            name='opt_has_animation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminexercise',
            name='opt_has_description',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminexercise',
            name='opt_has_scheme',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminexercise',
            name='opt_has_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='opt_has_animation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='opt_has_description',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='opt_has_scheme',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='opt_has_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='opt_has_animation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='opt_has_description',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='opt_has_scheme',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='opt_has_video',
            field=models.BooleanField(default=False),
        ),
    ]
