# Generated by Django 4.0.4 on 2023-01-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0065_adminexercise_opt_has_animation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminexercise',
            name='field_age_a',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminexercise',
            name='field_age_b',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminexercise',
            name='field_players_a',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminexercise',
            name='field_players_b',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='field_age_a',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='field_age_b',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='field_players_a',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='field_players_b',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='field_age_a',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='field_age_b',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='field_players_a',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='field_players_b',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
