# Generated by Django 4.0.4 on 2023-01-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0067_adminexercise_field_keyword_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminexercise',
            name='video_links',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='video_links',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='video_links',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
