# Generated by Django 4.0.4 on 2023-02-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0068_adminexercise_video_links_clubexercise_video_links_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminexercise',
            name='field_exs_category_a',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='adminexercise',
            name='field_exs_category_b',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='adminexercise',
            name='field_keyword_c',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='adminexercise',
            name='field_keyword_d',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='field_exs_category_a',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='field_exs_category_b',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='field_keyword_c',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='field_keyword_d',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='field_exs_category_a',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='field_exs_category_b',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='field_keyword_c',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='field_keyword_d',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
