# Generated by Django 4.0.4 on 2023-02-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0072_remove_adminexercise_field_keyword_c_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminexercise',
            name='field_cognitive_loads',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='field_cognitive_loads',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='field_cognitive_loads',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
