# Generated by Django 4.0.4 on 2023-02-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0073_adminexercise_field_cognitive_loads_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminexercise',
            name='field_physical_qualities',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminexercise',
            name='field_types',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='field_physical_qualities',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='field_types',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='field_physical_qualities',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='field_types',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
