# Generated by Django 4.0.4 on 2023-02-17 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0028_alter_exsphysicalqualities_options_and_more'),
        ('clubs', '0005_remove_club_limits_club_player_limit_club_team_limit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0074_adminexercise_field_physical_qualities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubfolder',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises_clubfolder_user', to='clubs.club'),
        ),
        migrations.AlterField(
            model_name='clubfolder',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises_clubfolder_team', to='references.clubteam'),
        ),
        migrations.AlterField(
            model_name='userfolder',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises_userfolder_team', to='references.userteam'),
        ),
        migrations.AlterField(
            model_name='userfolder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises_userfolder_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
