# Generated by Django 4.0.4 on 2023-03-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0075_alter_clubfolder_club_alter_clubfolder_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminexercise',
            name='field_fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='field_fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='field_fields',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
