# Generated by Django 4.0.4 on 2023-07-10 11:45

from django.db import migrations, models
import exercises.models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0079_adminexercise_date_editing_clubexercise_date_editing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminexercise',
            name='scheme_img',
            field=models.ImageField(blank=True, null=True, upload_to=exercises.models.upload_location_scheme),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='scheme_img',
            field=models.ImageField(blank=True, null=True, upload_to=exercises.models.upload_location_scheme),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='scheme_img',
            field=models.ImageField(blank=True, null=True, upload_to=exercises.models.upload_location_scheme),
        ),
    ]
