# Generated by Django 4.0.4 on 2023-08-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0080_adminexercise_scheme_img_clubexercise_scheme_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminexercise',
            name='field_goalkeeper',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='field_goalkeeper',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='field_goalkeeper',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
