# Generated by Django 4.0.4 on 2023-10-10 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0082_alter_clubexercise_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminexercise',
            options={'ordering': ['order'], 'permissions': (('view_category_u_big', 'View exercises with category <U>'), ('view_category_u_small', 'View exercises with category <u>'), ('view_category_u_PRO', 'View exercises with category <PRO>'))},
        ),
        migrations.AlterModelOptions(
            name='clubexercise',
            options={'ordering': ['order'], 'permissions': (('view_category_u_big', 'View exercises with category <U>'), ('view_category_u_small', 'View exercises with category <u>'), ('view_category_u_PRO', 'View exercises with category <PRO>'))},
        ),
        migrations.AlterModelOptions(
            name='userexercise',
            options={'ordering': ['order'], 'permissions': (('view_category_u_big', 'View exercises with category <U>'), ('view_category_u_small', 'View exercises with category <u>'), ('view_category_u_PRO', 'View exercises with category <PRO>'))},
        ),
    ]
