# Generated by Django 4.0.4 on 2023-12-15 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0039_exsfeatures_userexsfeatures_clubexsfeatures'),
        ('exercises', '0084_alter_adminexercise_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_default', to='references.exsfeatures')),
                ('ref_club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_club', to='references.clubexsfeatures')),
                ('ref_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_user', to='references.userexsfeatures')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='adminexercise',
            name='features',
            field=models.ManyToManyField(to='exercises.exercisefeature'),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='features',
            field=models.ManyToManyField(to='exercises.exercisefeature'),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='features',
            field=models.ManyToManyField(to='exercises.exercisefeature'),
        ),
    ]
