# Generated by Django 4.0.4 on 2023-12-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0086_trainerexercise_exercisevideo_exercise_trainer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainerexercise',
            name='user',
        ),
        migrations.AddField(
            model_name='trainerexercise',
            name='user_birthdate',
            field=models.DateField(blank=True, help_text='Date of birth', null=True, verbose_name='Birthday'),
        ),
        migrations.AddField(
            model_name='trainerexercise',
            name='user_name',
            field=models.CharField(blank=True, help_text='Last name', max_length=50, null=True, verbose_name='Surname'),
        ),
    ]
