# Generated by Django 4.0.4 on 2023-12-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0087_remove_trainerexercise_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerexercise',
            name='exs_ref',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
