# Generated by Django 4.0.4 on 2024-01-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0088_trainerexercise_exs_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminexercise',
            name='date_editing_folder',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='date_editing_folder',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainerexercise',
            name='date_editing_folder',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='date_editing_folder',
            field=models.DateField(blank=True, null=True),
        ),
    ]
