# Generated by Django 4.0.4 on 2024-02-21 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0090_trainerexercise_exs_ref_nf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainerexercise',
            old_name='exs_ref_nf',
            new_name='exs_ref_nfb',
        ),
    ]
