# Generated by Django 4.0.4 on 2024-02-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0091_rename_exs_ref_nf_trainerexercise_exs_ref_nfb'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminexercise',
            name='copied_exs_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='copied_exs_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainerexercise',
            name='copied_exs_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='copied_exs_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
