# Generated by Django 4.0.4 on 2024-02-21 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0092_adminexercise_copied_exs_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminexercise',
            old_name='copied_exs_id',
            new_name='clone_archive_id',
        ),
        migrations.RenameField(
            model_name='clubexercise',
            old_name='copied_exs_id',
            new_name='clone_archive_id',
        ),
        migrations.RenameField(
            model_name='trainerexercise',
            old_name='copied_exs_id',
            new_name='clone_archive_id',
        ),
        migrations.RenameField(
            model_name='userexercise',
            old_name='copied_exs_id',
            new_name='clone_archive_id',
        ),
    ]
