# Generated by Django 4.0.4 on 2024-06-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0094_userexerciseparam_admin_rec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userexerciseparam',
            name='admin_rec',
        ),
        migrations.AddField(
            model_name='userexerciseparam',
            name='note_club_admin',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userexerciseparam',
            name='note_trainer',
            field=models.CharField(default='', max_length=255),
        ),
    ]
