# Generated by Django 4.0.4 on 2024-06-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0095_remove_userexerciseparam_admin_rec_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexerciseparam',
            name='note_club_admin',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userexerciseparam',
            name='note_trainer',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
