# Generated by Django 4.0.4 on 2024-07-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0096_alter_userexerciseparam_note_club_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexerciseparam',
            name='note_status',
            field=models.IntegerField(default=0, help_text='0 - нет, 1 - красный, 2 - зелёный'),
        ),
    ]
