# Generated by Django 4.0.4 on 2025-01-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0097_userexerciseparam_note_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminexercise',
            name='scheme_1_old',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='adminexercise',
            name='scheme_2_old',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='scheme_1_old',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='scheme_2_old',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='trainerexercise',
            name='scheme_1_old',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='trainerexercise',
            name='scheme_2_old',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='scheme_1_old',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='scheme_2_old',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
