# Generated by Django 4.0.4 on 2025-03-30 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0008_club_separate_database'),
        ('exercises', '0098_adminexercise_scheme_1_old_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseTagFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Imported source name', max_length=255, null=True, verbose_name='title')),
                ('order', models.IntegerField(default=0, help_text='Sorting index', verbose_name='order')),
                ('lowercase_name', models.CharField(help_text='lowercase title', max_length=255, unique=True, verbose_name='lowercase title')),
                ('is_nfb', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=True)),
                ('short_name', models.CharField(help_text='Короткий ключ для поиска', max_length=10)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom tags',
                'verbose_name_plural': 'Custom tags',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='adminexercise',
            name='tagsFolder',
            field=models.ManyToManyField(to='exercises.exercisetagfolder'),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='tagsFolder',
            field=models.ManyToManyField(to='exercises.exercisetagfolder'),
        ),
        migrations.AddField(
            model_name='trainerexercise',
            name='tagsFolder',
            field=models.ManyToManyField(to='exercises.exercisetagfolder'),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='tagsFolder',
            field=models.ManyToManyField(to='exercises.exercisetagfolder'),
        ),
    ]
