# Generated by Django 4.0.4 on 2025-03-31 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0099_exercisetagfolder_adminexercise_tagsfolder_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminexercise',
            old_name='tagsFolder',
            new_name='tags_folder',
        ),
        migrations.RenameField(
            model_name='clubexercise',
            old_name='tagsFolder',
            new_name='tags_folder',
        ),
        migrations.RenameField(
            model_name='trainerexercise',
            old_name='tagsFolder',
            new_name='tags_folder',
        ),
        migrations.RenameField(
            model_name='userexercise',
            old_name='tagsFolder',
            new_name='tags_folder',
        ),
    ]
