# Generated by Django 4.0.4 on 2025-05-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0100_rename_tagsfolder_adminexercise_tags_folder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexerciseparam',
            name='favorite_2',
            field=models.BooleanField(default=False),
        ),
    ]
