# Generated by Django 4.0.4 on 2025-05-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0101_userexerciseparam_favorite_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminexercise',
            name='field_e_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='field_e_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='trainerexercise',
            name='field_e_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='field_e_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
