# Generated by Django 4.0.4 on 2025-08-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0102_adminexercise_field_e_type_clubexercise_field_e_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminexercise',
            name='scheme_img_show_first',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='scheme_img_show_first',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainerexercise',
            name='scheme_img_show_first',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='scheme_img_show_first',
            field=models.BooleanField(default=False),
        ),
    ]
