# Generated by Django 4.0.4 on 2025-10-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0103_adminexercise_scheme_img_show_first_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminexercise',
            name='opt_has_description_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminexercise',
            name='opt_has_scheme_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='opt_has_description_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='opt_has_scheme_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainerexercise',
            name='opt_has_description_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainerexercise',
            name='opt_has_scheme_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='opt_has_description_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='opt_has_scheme_2',
            field=models.BooleanField(default=False),
        ),
    ]
