# Generated by Django 4.0.4 on 2025-11-01 08:43

from django.db import migrations, models
import exercises.models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0105_exercisetagshortcategories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminexercise',
            name='scheme_img_2',
            field=models.ImageField(blank=True, null=True, upload_to=exercises.models.upload_location_scheme),
        ),
        migrations.AddField(
            model_name='adminexercise',
            name='scheme_img_change_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='scheme_img_2',
            field=models.ImageField(blank=True, null=True, upload_to=exercises.models.upload_location_scheme),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='scheme_img_change_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainerexercise',
            name='scheme_img_2',
            field=models.ImageField(blank=True, null=True, upload_to=exercises.models.upload_location_scheme),
        ),
        migrations.AddField(
            model_name='trainerexercise',
            name='scheme_img_change_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='scheme_img_2',
            field=models.ImageField(blank=True, null=True, upload_to=exercises.models.upload_location_scheme),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='scheme_img_change_order',
            field=models.BooleanField(default=False),
        ),
    ]
