# Generated by Django 4.0.4 on 2025-11-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0106_adminexercise_scheme_img_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminexercise',
            name='language_main',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='adminexercise',
            name='languages_complete',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='language_main',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clubexercise',
            name='languages_complete',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainerexercise',
            name='language_main',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='trainerexercise',
            name='languages_complete',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='language_main',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='languages_complete',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
