# Generated by Django 4.0.4 on 2022-10-21 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'verbose_name': 'Club card', 'verbose_name_plural': 'Club cards'},
        ),
    ]
