# Generated by Django 4.0.4 on 2022-10-25 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_alter_club_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'permissions': [('club_admin', 'Access to the club admin panel')], 'verbose_name': 'Club card', 'verbose_name_plural': 'Club cards'},
        ),
    ]
