# Generated by Django 4.0.4 on 2022-12-09 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0003_limitations_clublimitations_version_limits'),
        ('clubs', '0003_alter_club_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='limits',
            field=models.ForeignKey(blank=True, help_text='Club limits', null=True, on_delete=django.db.models.deletion.SET_NULL, to='version.clublimitations', verbose_name='limits'),
        ),
    ]
