# Generated by Django 4.0.4 on 2022-12-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_club_limits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='limits',
        ),
        migrations.AddField(
            model_name='club',
            name='player_limit',
            field=models.IntegerField(default=25, help_text='limit on the number of players in a team', verbose_name='number of players'),
        ),
        migrations.AddField(
            model_name='club',
            name='team_limit',
            field=models.IntegerField(default=2, help_text='limit on the number of teams', verbose_name='number of teams'),
        ),
        migrations.AddField(
            model_name='club',
            name='user_limit',
            field=models.IntegerField(default=50, help_text='limit on the number of users', verbose_name='number of users'),
        ),
    ]
