# Generated by Django 4.0.4 on 2023-07-01 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('federations', '0001_initial'),
        ('clubs', '0005_remove_club_limits_club_player_limit_club_team_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='federation_id',
            field=models.ForeignKey(blank=True, default=None, help_text='The federation the club is a member of', null=True, on_delete=django.db.models.deletion.SET_NULL, to='federations.federation', verbose_name='Federation'),
        ),
    ]
