# Generated by Django 4.0.4 on 2023-07-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_club_federation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='image',
            field=models.ImageField(blank=True, help_text='Club logo', upload_to='clubs_logo/', verbose_name='logo'),
        ),
    ]
