# Generated by Django 4.0.4 on 2025-02-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_club_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='separate_database',
            field=models.CharField(blank=True, help_text='Settings for separate database check in settings.py -> DATABASES.', max_length=30, null=True, verbose_name='Name of the separate database'),
        ),
    ]
