# Generated by Django 4.0.4 on 2023-08-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_usermedicineaccess_clubmedicineaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmedicinediagnosis',
            name='healthy_date',
            field=models.DateTimeField(blank=True, help_text='Date and time of healthy status', verbose_name='Date and time'),
        ),
        migrations.AlterField(
            model_name='usermedicinediagnosis',
            name='healthy_date',
            field=models.DateTimeField(blank=True, help_text='Date and time of healthy status', verbose_name='Date and time'),
        ),
    ]
