# Generated by Django 4.0.4 on 2023-09-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0006_alter_clubmedicinediagnosis_recovery_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmedicinedocument',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='medicine/docs/uploads'),
        ),
        migrations.AlterField(
            model_name='usermedicinedocument',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='medicine/docs/uploads'),
        ),
    ]
