# Generated by Django 4.0.4 on 2023-10-04 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0037_medicinediseasespecificuser_and_more'),
        ('medicine', '0007_alter_clubmedicinedocument_doc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmedicinediagnosis',
            name='disease_nonspecific',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.medicinediseasenonspecificclub'),
        ),
        migrations.AlterField(
            model_name='clubmedicinediagnosis',
            name='disease_specific',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.medicinediseasespecificclub'),
        ),
        migrations.AlterField(
            model_name='usermedicinediagnosis',
            name='disease_nonspecific',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.medicinediseasenonspecificuser'),
        ),
        migrations.AlterField(
            model_name='usermedicinediagnosis',
            name='disease_specific',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.medicinediseasespecificuser'),
        ),
    ]
