# Generated by Django 4.0.4 on 2023-02-17 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0005_remove_club_limits_club_player_limit_club_team_limit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Импортируемое название папки', max_length=255, null=True)),
                ('translations_name', models.JSONField(blank=True, null=True)),
                ('parent', models.IntegerField(blank=True, help_text='Ид папки родителя', null=True)),
                ('visible', models.BooleanField(default=True, help_text='Показывать папку пользователю или нет')),
                ('short_name', models.CharField(help_text='Короткий ключ для поиска', max_length=10)),
                ('order', models.IntegerField(default=0, help_text='Индекс сортировки')),
                ('active', models.BooleanField(default=True, help_text='Показывать папку любому пользователю на релизе, неактивные папки доступны администрации.')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Импортируемое название папки', max_length=255, null=True)),
                ('translations_name', models.JSONField(blank=True, null=True)),
                ('parent', models.IntegerField(blank=True, help_text='Ид папки родителя', null=True)),
                ('visible', models.BooleanField(default=True, help_text='Показывать папку пользователю или нет')),
                ('short_name', models.CharField(help_text='Короткий ключ для поиска', max_length=10)),
                ('order', models.IntegerField(default=0, help_text='Индекс сортировки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methodology_userfolder_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClubFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Импортируемое название папки', max_length=255, null=True)),
                ('translations_name', models.JSONField(blank=True, null=True)),
                ('parent', models.IntegerField(blank=True, help_text='Ид папки родителя', null=True)),
                ('visible', models.BooleanField(default=True, help_text='Показывать папку пользователю или нет')),
                ('short_name', models.CharField(help_text='Короткий ключ для поиска', max_length=10)),
                ('order', models.IntegerField(default=0, help_text='Индекс сортировки')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='methodology_clubfolder_club', to='clubs.club')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
    ]
