# Generated by Django 4.0.4 on 2023-02-17 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0005_remove_club_limits_club_player_limit_club_team_limit_and_more'),
        ('methodology', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('order', models.IntegerField(default=0, help_text='Индекс сортировки')),
                ('visible', models.BooleanField(default=True, help_text='Показывать статью пользователю или нет')),
                ('completed', models.BooleanField(default=False, help_text='Статья завершена')),
                ('drafted', models.BooleanField(default=False, help_text='Статья в черновике')),
                ('title', models.JSONField(blank=True, null=True)),
                ('content', models.JSONField(blank=True, null=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='methodology.userfolder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClubArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('order', models.IntegerField(default=0, help_text='Индекс сортировки')),
                ('visible', models.BooleanField(default=True, help_text='Показывать статью пользователю или нет')),
                ('completed', models.BooleanField(default=False, help_text='Статья завершена')),
                ('drafted', models.BooleanField(default=False, help_text='Статья в черновике')),
                ('title', models.JSONField(blank=True, null=True)),
                ('content', models.JSONField(blank=True, null=True)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='methodology.clubfolder')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdminArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('order', models.IntegerField(default=0, help_text='Индекс сортировки')),
                ('visible', models.BooleanField(default=True, help_text='Показывать статью пользователю или нет')),
                ('completed', models.BooleanField(default=False, help_text='Статья завершена')),
                ('drafted', models.BooleanField(default=False, help_text='Статья в черновике')),
                ('title', models.JSONField(blank=True, null=True)),
                ('content', models.JSONField(blank=True, null=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='methodology.adminfolder')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
    ]
