# Generated by Django 4.0.4 on 2023-02-24 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('methodology', '0003_alter_adminfolder_name_alter_clubfolder_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserArticleParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.BooleanField(default=False)),
                ('article_club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='methodology.clubarticle')),
                ('article_nfb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='methodology.adminarticle')),
                ('article_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='methodology.userarticle')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
