# Generated by Django 4.0.4 on 2022-07-12 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Section name', max_length=255, verbose_name='title')),
                ('tag', models.CharField(help_text='Section tag', max_length=100, verbose_name='tag')),
            ],
            options={
                'verbose_name': 'section',
                'verbose_name_plural': 'sections',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Version name', max_length=255, verbose_name='title')),
                ('updated_date', models.DateField(auto_now=True, help_text='Version update date', verbose_name='last update')),
                ('is_active', models.BooleanField(default=False, help_text='The version is active for user selection', verbose_name='active')),
                ('tag', models.CharField(help_text='Version tag', max_length=100, verbose_name='tag')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='The cost of the version in the currency', max_digits=8, verbose_name='price')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this version belongs to. A version will get all permissions granted to each of their groups.', to='auth.group', verbose_name='groups')),
                ('permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this version.', to='auth.permission', verbose_name='permissions')),
            ],
            options={
                'verbose_name': 'version',
                'verbose_name_plural': 'versions',
            },
        ),
        migrations.CreateModel(
            name='CustomGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='The cost of the Group in the currency', max_digits=8, verbose_name='price')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'verbose_name': 'Custom group params',
            },
        ),
    ]
