# Generated by Django 4.0.4 on 2022-05-07 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название доступа', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название раздела', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название версии', max_length=255)),
                ('updated_date', models.DateField(help_text='Дата обновления версии')),
                ('is_active', models.BooleanField(default=False)),
                ('tag', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VersionAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version.access')),
                ('version_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version.version')),
            ],
        ),
        migrations.AddField(
            model_name='access',
            name='section_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version.section'),
        ),
    ]
