# Generated by Django 4.0.4 on 2022-05-10 10:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='tag',
            field=models.CharField(default=django.utils.timezone.now, help_text='Ключ доступа', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='tag',
            field=models.CharField(default='test', help_text='Ключ раздела', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='version',
            name='tag',
            field=models.CharField(help_text='Ключ версии', max_length=100),
        ),
    ]
