# Generated by Django 4.0.4 on 2022-12-09 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0002_customgroup_text_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Limitations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_limit', models.IntegerField(default=2, help_text='limit on the number of teams', verbose_name='number of teams')),
                ('player_limit', models.IntegerField(default=25, help_text='limit on the number of players in a team', verbose_name='number of players')),
            ],
        ),
        migrations.CreateModel(
            name='ClubLimitations',
            fields=[
                ('limitations_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='version.limitations')),
                ('user_limit', models.IntegerField(default=10, help_text='limit on the number of users', verbose_name='number of users')),
            ],
            bases=('version.limitations',),
        ),
        migrations.AddField(
            model_name='version',
            name='limits',
            field=models.ForeignKey(blank=True, help_text='User limits', null=True, on_delete=django.db.models.deletion.SET_NULL, to='version.limitations', verbose_name='limits'),
        ),
    ]
