# Generated by Django 4.0.4 on 2022-12-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_remove_club_limits_club_player_limit_club_team_limit_and_more'),
        ('version', '0003_limitations_clublimitations_version_limits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='limits',
        ),
        migrations.AddField(
            model_name='version',
            name='player_limit',
            field=models.IntegerField(default=25, help_text='limit on the number of players in a team', verbose_name='number of players'),
        ),
        migrations.AddField(
            model_name='version',
            name='team_limit',
            field=models.IntegerField(default=2, help_text='limit on the number of teams', verbose_name='number of teams'),
        ),
        migrations.DeleteModel(
            name='ClubLimitations',
        ),
        migrations.DeleteModel(
            name='Limitations',
        ),
    ]
