# Generated by Django 4.0.4 on 2022-05-12 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0003_alter_versionaccess_version_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionaccess',
            name='version_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='version.version'),
        ),
    ]
