# Generated by Django 4.0.4 on 2023-03-07 11:41

from django.db import migrations, models
import django.db.models.deletion
import version.models


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0004_remove_version_limits_version_player_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroup',
            name='order_column',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customgroup',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='version.section'),
        ),
        migrations.AddField(
            model_name='customgroup',
            name='translation_name',
            field=models.JSONField(blank=True, default=version.models.get_default_name_json, help_text='Group translated name', null=True, verbose_name='Group name'),
        ),
        migrations.AddField(
            model_name='customgroup',
            name='tree_depth',
            field=models.IntegerField(default=0),
        ),
    ]
