# Generated by Django 4.0.4 on 2022-05-12 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0004_alter_versionaccess_version_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='versionaccess',
            name='version_id',
        ),
    ]
