# Generated by Django 4.0.4 on 2023-03-07 11:42

from django.db import migrations, models
import version.models


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0005_customgroup_order_column_customgroup_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='translation_name',
            field=models.JSONField(blank=True, default=version.models.get_default_name_json, help_text='Section translated name', null=True, verbose_name='Section name'),
        ),
    ]
