# Generated by Django 4.0.4 on 2022-05-12 14:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0006_versionaccess_version_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
