# Generated by Django 4.0.4 on 2023-10-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0007_remove_customgroup_order_column_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroup',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
