# Generated by Django 4.0.4 on 2022-06-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('version', '0008_alter_version_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='versionaccess',
            name='access_id',
        ),
        migrations.RemoveField(
            model_name='versionaccess',
            name='version_id',
        ),
        migrations.AddField(
            model_name='version',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='auth.permission', verbose_name='permissions'),
        ),
        migrations.AddField(
            model_name='version',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='The cost of the version in the currency', max_digits=8, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(help_text='Section name', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='section',
            name='tag',
            field=models.CharField(help_text='Section tag', max_length=100, verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='version',
            name='is_active',
            field=models.BooleanField(default=False, help_text='The version is active for user selection', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='version',
            name='name',
            field=models.CharField(help_text='Version name', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='version',
            name='tag',
            field=models.CharField(help_text='Version tag', max_length=100, verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='version',
            name='updated_date',
            field=models.DateField(auto_now=True, help_text='Version update date', verbose_name='Last update'),
        ),
        migrations.DeleteModel(
            name='Access',
        ),
        migrations.DeleteModel(
            name='VersionAccess',
        ),
    ]
