# Generated by Django 4.0.4 on 2023-10-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0008_customgroup_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customgroup',
            name='section',
        ),
        migrations.AddField(
            model_name='customgroup',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
