# Generated by Django 4.0.4 on 2022-06-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('version', '0009_remove_versionaccess_access_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this version belongs to. A version will get all permissions granted to each of their groups.', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(help_text='Section name', max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='section',
            name='tag',
            field=models.CharField(help_text='Section tag', max_length=100, verbose_name='tag'),
        ),
        migrations.AlterField(
            model_name='version',
            name='is_active',
            field=models.BooleanField(default=False, help_text='The version is active for user selection', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='version',
            name='name',
            field=models.CharField(help_text='Version name', max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='version',
            name='permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this version.', to='auth.permission', verbose_name='permissions'),
        ),
        migrations.AlterField(
            model_name='version',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='The cost of the version in the currency', max_digits=8, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='version',
            name='tag',
            field=models.CharField(help_text='Version tag', max_length=100, verbose_name='tag'),
        ),
        migrations.AlterField(
            model_name='version',
            name='updated_date',
            field=models.DateField(auto_now=True, help_text='Version update date', verbose_name='last update'),
        ),
    ]
