# Generated by Django 4.0.4 on 2023-10-11 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0009_remove_customgroup_section_customgroup_is_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customgroup',
            options={'ordering': ['order'], 'verbose_name': 'Custom group params'},
        ),
    ]
