# Generated by Django 4.0.4 on 2024-01-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0011_sectioninformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectioninformation',
            name='name',
            field=models.CharField(blank=True, help_text='A note on the section indicates the location', max_length=100, null=True, verbose_name='Note on section'),
        ),
    ]
