# Generated by Django 4.0.4 on 2022-06-09 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0011_customgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customgroup',
            options={'verbose_name': 'Custom group params'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'section', 'verbose_name_plural': 'sections'},
        ),
        migrations.AlterModelOptions(
            name='version',
            options={'verbose_name': 'version', 'verbose_name_plural': 'versions'},
        ),
    ]
