# Generated by Django 4.0.4 on 2022-05-20 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '0001_initial'),
        ('version', '0008_alter_version_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Импортируемое название видео', max_length=255, null=True)),
                ('upload_date', models.DateField()),
                ('duration', models.TimeField(blank=True, help_text='Длительность видео')),
                ('links', models.JSONField()),
                ('shared_access', models.BooleanField(default=False, help_text='Есть ли доступ у всех пользователей')),
                ('section_id', models.ForeignKey(help_text='ID раздела, к которому привязано видео', null=True, on_delete=django.db.models.deletion.CASCADE, to='version.section')),
                ('videosource_id', models.ForeignKey(help_text='ID источника', on_delete=django.db.models.deletion.CASCADE, to='references.videosource')),
            ],
        ),
    ]
