# Generated by Django 4.0.4 on 2022-07-12 09:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
import references.models
import version.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('version', '0001_initial'),
        ('references', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Imported video title', max_length=255, verbose_name='title')),
                ('upload_date', models.DateField(auto_now=True, help_text='Date the video was uploaded or updated', verbose_name='upload date')),
                ('duration', models.DurationField(default=datetime.timedelta(0), help_text='The duration of the video in the format 00:00:00', verbose_name='duration video')),
                ('links', models.JSONField(help_text='Links to videos from various sources', verbose_name='video links')),
                ('shared_access', models.BooleanField(default=False, help_text='Is it available to all users?', verbose_name='shared access')),
                ('old_id', models.IntegerField(blank=True, help_text='ID of the exercise that the video was linked to', null=True, verbose_name='old id')),
                ('section_id', models.ForeignKey(default=version.models.Section.get_default_pk, help_text='The section to which the video is linked', on_delete=django.db.models.deletion.SET_DEFAULT, to='version.section', verbose_name='video source')),
                ('videosource_id', models.ForeignKey(default=references.models.VideoSource.get_default_pk, help_text='The source to which the video is linked', on_delete=django.db.models.deletion.SET_DEFAULT, to='references.videosource', verbose_name='video source')),
            ],
            options={
                'ordering': ['videosource_id', 'section_id'],
                'permissions': (('uploading_files', 'Can upload files to videos'), ('parsing_video', 'Can parse video')),
            },
        ),
    ]
