# Generated by Django 4.0.4 on 2022-08-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tag title', max_length=100, verbose_name='title')),
            ],
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['videosource_id'], 'permissions': (('uploading_files', 'Can upload files to videos'), ('parsing_video', 'Can parse video'))},
        ),
        migrations.RemoveField(
            model_name='video',
            name='section_id',
        ),
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(help_text='Tags linked to the video', to='video.videotags', verbose_name='video tags'),
        ),
    ]
