# Generated by Django 4.0.4 on 2022-05-20 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0008_alter_version_id'),
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='section_id',
            field=models.ForeignKey(help_text='ID раздела, к которому привязано видео', null=True, on_delete=django.db.models.deletion.SET_NULL, to='version.section'),
        ),
    ]
