# Generated by Django 4.0.4 on 2022-05-23 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
        ('version', '0008_alter_version_id'),
        ('video', '0002_alter_video_section_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.DurationField(blank=True, help_text='Длительность видео в формате 00:00:00'),
        ),
        migrations.AlterField(
            model_name='video',
            name='links',
            field=models.JSONField(help_text='Ссылки на видео с разных источников'),
        ),
        migrations.AlterField(
            model_name='video',
            name='section_id',
            field=models.ForeignKey(help_text='Раздел, к которому привязано видео', null=True, on_delete=django.db.models.deletion.SET_NULL, to='version.section'),
        ),
        migrations.AlterField(
            model_name='video',
            name='shared_access',
            field=models.BooleanField(default=False, help_text='Доступно всем пользователям?'),
        ),
        migrations.AlterField(
            model_name='video',
            name='upload_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='videosource_id',
            field=models.ForeignKey(help_text='Источник, к которому привязано видео', on_delete=django.db.models.deletion.CASCADE, to='references.videosource'),
        ),
    ]
