# Generated by Django 4.0.4 on 2022-08-03 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_alter_video_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date the video was created', verbose_name='created date'),
            preserve_default=False,
        ),
    ]
