# Generated by Django 4.0.4 on 2022-05-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_alter_video_duration_alter_video_links_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['videosource_id', 'section_id']},
        ),
        migrations.AddField(
            model_name='video',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
