# Generated by Django 4.0.4 on 2022-05-24 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_alter_video_options_video_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='slug',
        ),
    ]
