# Generated by Django 4.0.4 on 2022-05-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_remove_video_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='old_id',
            field=models.IntegerField(blank=True, help_text='ID видео в старой программе', null=True),
        ),
    ]
