# Generated by Django 4.0.4 on 2022-06-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_video_old_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='old_id',
            field=models.IntegerField(blank=True, help_text='ID упражнения, к которому было привязано видео', null=True),
        ),
    ]
