# Generated by Django 4.0.4 on 2022-08-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_alter_video_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['videosource_id'], 'permissions': (('uploading_files', 'Can upload files to videos'), ('uploading_screensaver', 'Can upload screensaver to videos'), ('parsing_video', 'Can parse video'))},
        ),
        migrations.AddField(
            model_name='video',
            name='screensaver',
            field=models.CharField(blank=True, help_text='Splash screen on the start screen of the video', max_length=255, null=True, verbose_name='screensaver'),
        ),
    ]
