# Generated by Django 4.0.4 on 2022-06-01 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0003_alter_userreference_order_and_more'),
        ('video', '0007_alter_video_old_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(default='No name', help_text='Импортируемое название видео', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='videosource_id',
            field=models.ForeignKey(help_text='Источник, к которому привязано видео', null=True, on_delete=django.db.models.deletion.CASCADE, to='references.videosource'),
        ),
    ]
