# Generated by Django 4.0.4 on 2022-08-30 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_alter_video_options_video_screensaver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='shared_access',
        ),
    ]
