# Generated by Django 4.0.4 on 2022-06-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_alter_video_name_alter_video_videosource_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.DurationField(blank=True, help_text='Длительность видео в формате 00:00:00', null=True),
        ),
    ]
