# Generated by Django 4.0.4 on 2022-06-01 17:56

from django.db import migrations, models
import django.db.models.deletion
import references.models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0003_alter_userreference_order_and_more'),
        ('video', '0009_alter_video_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videosource_id',
            field=models.ForeignKey(default=references.models.VideoSource.get_default_pk, help_text='Источник, к которому привязано видео', on_delete=django.db.models.deletion.SET_DEFAULT, to='references.videosource'),
        ),
    ]
