# Generated by Django 4.0.4 on 2022-06-01 18:13

from django.db import migrations, models
import django.db.models.deletion
import version.models


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0008_alter_version_id'),
        ('video', '0010_alter_video_videosource_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='section_id',
            field=models.ForeignKey(default=version.models.Section.get_default_pk, help_text='Раздел, к которому привязано видео', on_delete=django.db.models.deletion.SET_DEFAULT, to='version.section'),
        ),
    ]
