# Generated by Django 4.0.4 on 2022-08-30 10:07

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('video', '0010_remove_video_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='taggit',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
