# Generated by Django 4.0.4 on 2022-06-01 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0011_alter_video_section_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0), help_text='Длительность видео в формате 00:00:00'),
        ),
    ]
