# Generated by Django 4.0.4 on 2022-12-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0012_alter_video_taggit'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='note',
            field=models.JSONField(blank=True, help_text='Notes in json format', null=True, verbose_name='Notes'),
        ),
    ]
