# Generated by Django 4.0.4 on 2022-06-09 12:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
import references.models
import version.models


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0010_version_groups_alter_section_name_alter_section_tag_and_more'),
        ('references', '0004_abstractuserreference_alter_videosource_link_and_more'),
        ('video', '0013_alter_video_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0), help_text='The duration of the video in the format 00:00:00', verbose_name='duration video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='links',
            field=models.JSONField(help_text='Links to videos from various sources', verbose_name='video links'),
        ),
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(help_text='Imported video title', max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='video',
            name='old_id',
            field=models.IntegerField(blank=True, help_text='ID of the exercise that the video was linked to', null=True, verbose_name='old id'),
        ),
        migrations.AlterField(
            model_name='video',
            name='section_id',
            field=models.ForeignKey(default=version.models.Section.get_default_pk, help_text='The section to which the video is linked', on_delete=django.db.models.deletion.SET_DEFAULT, to='version.section', verbose_name='video source'),
        ),
        migrations.AlterField(
            model_name='video',
            name='shared_access',
            field=models.BooleanField(default=False, help_text='Is it available to all users?', verbose_name='shared access'),
        ),
        migrations.AlterField(
            model_name='video',
            name='upload_date',
            field=models.DateField(auto_now=True, help_text='Date the video was uploaded or updated', verbose_name='upload date'),
        ),
        migrations.AlterField(
            model_name='video',
            name='videosource_id',
            field=models.ForeignKey(default=references.models.VideoSource.get_default_pk, help_text='The source to which the video is linked', on_delete=django.db.models.deletion.SET_DEFAULT, to='references.videosource', verbose_name='video source'),
        ),
    ]
