# Generated by Django 4.0.4 on 2022-06-16 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0014_alter_video_duration_alter_video_links_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['videosource_id', 'section_id'], 'permissions': (('uploading_files', 'Can upload files to videos'), ('parsing_video', 'Can parse video'))},
        ),
    ]
