# Generated by Django 4.0.4 on 2024-09-17 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_club_image'),
        ('video', '0015_video_club_video_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.club'),
        ),
    ]
