# Generated by Django 4.0.4 on 2025-09-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0016_alter_video_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='size'),
        ),
    ]
