# Generated by Django 4.0.4 on 2025-10-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0017_video_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='size_mb',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
