# Generated by Django 4.0.4 on 2022-08-31 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('references', '0011_exstitlename_delete_exstitlenames'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('surname', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('patronymic', models.CharField(max_length=30, null=True)),
                ('citizenship', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='players/static/players/img/uploads')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.userteam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClubPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('surname', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('patronymic', models.CharField(max_length=30, null=True)),
                ('citizenship', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='players/static/players/img/uploads')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.clubteam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
