# Generated by Django 4.0.4 on 2022-08-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubplayer',
            name='photo',
            field=models.ImageField(null=True, upload_to='players/static/players/img/uploads'),
        ),
        migrations.AlterField(
            model_name='userplayer',
            name='photo',
            field=models.ImageField(null=True, upload_to='players/static/players/img/uploads'),
        ),
    ]
