# Generated by Django 4.0.4 on 2022-08-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_clubplayer_photo_alter_userplayer_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubplayer',
            name='patronymic',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='clubplayer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='players/static/players/img/uploads'),
        ),
        migrations.AlterField(
            model_name='userplayer',
            name='patronymic',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userplayer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='players/static/players/img/uploads'),
        ),
    ]
