# Generated by Django 4.0.4 on 2022-08-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_alter_clubplayer_patronymic_alter_clubplayer_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubplayer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/players/img/uploads'),
        ),
        migrations.AlterField(
            model_name='userplayer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/players/img/uploads'),
        ),
    ]
