# Generated by Django 4.0.4 on 2022-09-02 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('players', '0006_alter_clubplayer_options_alter_userplayer_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubplayer',
            name='citizenship',
        ),
        migrations.RemoveField(
            model_name='userplayer',
            name='citizenship',
        ),
        migrations.CreateModel(
            name='PlayerCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizenship', models.CharField(blank=True, max_length=30, null=True)),
                ('club_from', models.CharField(blank=True, max_length=30, null=True)),
                ('growth', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('game_num', models.IntegerField(blank=True, null=True)),
                ('birthsday', models.DateField(blank=True, null=True)),
                ('ref_team_status', models.IntegerField(blank=True, null=True)),
                ('ref_player_status', models.IntegerField(blank=True, null=True)),
                ('ref_level', models.IntegerField(blank=True, null=True)),
                ('ref_position', models.IntegerField(blank=True, null=True)),
                ('ref_foot', models.IntegerField(blank=True, null=True)),
                ('come', models.DateField(blank=True, null=True)),
                ('leave', models.DateField(blank=True, null=True)),
                ('contacts', models.JSONField(blank=True, null=True)),
                ('notes', models.JSONField(blank=True, null=True)),
                ('player_club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.clubplayer')),
                ('player_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.userplayer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
