# Generated by Django 4.0.4 on 2022-09-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_remove_clubplayer_citizenship_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.JSONField(blank=True, null=True)),
                ('text_id', models.CharField(blank=True, max_length=20, null=True)),
                ('parent', models.IntegerField(blank=True, help_text='Ид раздела родителя', null=True)),
                ('visible', models.BooleanField(default=True, help_text='Показывать раздел пользователю или нет')),
                ('short_name', models.CharField(blank=True, help_text='Короткий ключ для поиска', max_length=10, null=True)),
                ('order', models.IntegerField(default=0, help_text='Индекс сортировки')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
