# Generated by Django 4.0.4 on 2022-09-12 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_cardsection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerCard',
        ),
    ]
