# Generated by Django 4.0.4 on 2022-09-12 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_delete_playercard'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizenship', models.CharField(blank=True, max_length=30, null=True)),
                ('club_from', models.CharField(blank=True, max_length=30, null=True)),
                ('growth', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('game_num', models.IntegerField(blank=True, null=True)),
                ('birthsday', models.DateField(blank=True, null=True)),
                ('ref_team_status', models.IntegerField(blank=True, null=True)),
                ('ref_player_status', models.IntegerField(blank=True, null=True)),
                ('ref_level', models.IntegerField(blank=True, null=True)),
                ('ref_position', models.IntegerField(blank=True, null=True)),
                ('ref_foot', models.IntegerField(blank=True, null=True)),
                ('come', models.DateField(blank=True, null=True)),
                ('leave', models.DateField(blank=True, null=True)),
                ('contacts', models.JSONField(blank=True, null=True)),
                ('notes', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='clubplayer',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.playercard'),
        ),
        migrations.AddField(
            model_name='userplayer',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.playercard'),
        ),
    ]
