# Generated by Django 4.0.4 on 2022-09-19 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('players', '0013_playercharacteristicsrows_playercharacteristicuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playercharacteristicsrows',
            name='exercise_user',
        ),
        migrations.AddField(
            model_name='playercharacteristicsrows',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
