# Generated by Django 4.0.4 on 2022-09-21 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('players', '0014_remove_playercharacteristicsrows_exercise_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerQuestionnairesRows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.JSONField(blank=True, null=True)),
                ('is_nfb', models.BooleanField(default=False, help_text='NFB шаблон для примера')),
                ('parent', models.IntegerField(blank=True, help_text='Ид раздела родителя', null=True)),
                ('visible', models.BooleanField(default=True, help_text='Показывать раздел пользователю или нет')),
                ('short_name', models.CharField(blank=True, help_text='Короткий ключ для поиска', max_length=10, null=True)),
                ('order', models.IntegerField(default=0, help_text='Индекс сортировки')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PlayerQuestionnaireUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.userplayer')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.playerquestionnairesrows')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerQuestionnaireClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.clubplayer')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.playerquestionnairesrows')),
            ],
        ),
    ]
