# Generated by Django 4.0.4 on 2022-10-17 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0014_playerprotocolstatus_tags'),
        ('players', '0015_playerquestionnairesrows_playerquestionnaireuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playercard',
            name='ref_foot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='references.playerfoot'),
        ),
        migrations.AlterField(
            model_name='playercard',
            name='ref_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='references.playerlevel'),
        ),
        migrations.AlterField(
            model_name='playercard',
            name='ref_player_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='references.playerplayerstatus'),
        ),
        migrations.AlterField(
            model_name='playercard',
            name='ref_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='references.playerposition'),
        ),
        migrations.AlterField(
            model_name='playercard',
            name='ref_team_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='references.playerteamstatus'),
        ),
    ]
