# Generated by Django 4.0.4 on 2022-11-23 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_alter_club_options'),
        ('players', '0016_alter_playercard_ref_foot_alter_playercard_ref_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playercharacteristicclub',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.club'),
        ),
        migrations.AddField(
            model_name='playerquestionnaireclub',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.club'),
        ),
    ]
