# Generated by Django 4.0.4 on 2022-12-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0019_playerquestionnairesrows_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='playercard',
            name='contract_by',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playercard',
            name='contract_with',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playercard',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='playercard',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='playercard',
            name='phone_2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
