# Generated by Django 4.0.4 on 2022-12-20 10:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0020_playercard_contract_by_playercard_contract_with_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('record', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='playercard',
            name='records',
            field=models.ManyToManyField(to='players.playerrecord'),
        ),
    ]
