# Generated by Django 4.0.4 on 2023-01-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0021_playerrecord_playercard_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='playercard',
            name='is_captain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playercard',
            name='is_goalkeeper',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playercard',
            name='is_vice_captain',
            field=models.BooleanField(default=False),
        ),
    ]
