# Generated by Django 4.0.4 on 2023-01-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0022_playercard_is_captain_playercard_is_goalkeeper_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstablecolumns',
            name='short_name',
            field=models.CharField(blank=True, help_text='Короткий ключ для поиска', max_length=50, null=True),
        ),
    ]
