# Generated by Django 4.0.4 on 2023-01-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0023_alter_playerstablecolumns_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstablecolumns',
            name='short_name',
            field=models.CharField(blank=True, help_text='Короткий ключ для поиска', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='playerstablecolumns',
            name='text_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
