# Generated by Django 4.0.4 on 2023-03-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0024_alter_playerstablecolumns_short_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playercard',
            name='field_labels',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
