# Generated by Django 4.0.4 on 2023-07-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0025_playercard_field_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubplayer',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userplayer',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
