# Generated by Django 4.0.4 on 2023-10-15 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0026_clubplayer_is_archive_userplayer_is_archive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubplayer',
            options={'ordering': ['surname', 'name', 'patronymic'], 'permissions': [('view_parents', 'View section <Parents>')]},
        ),
        migrations.AlterModelOptions(
            name='userplayer',
            options={'ordering': ['surname', 'name', 'patronymic'], 'permissions': [('view_parents', 'View section <Parents>')]},
        ),
    ]
