# Generated by Django 4.0.4 on 2024-04-04 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_club_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('players', '0028_alter_playerrecord_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=30)),
                ('order', models.IntegerField(default=0, help_text='Индекс сортировки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClubDocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=30)),
                ('order', models.IntegerField(default=0, help_text='Индекс сортировки')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
