# Generated by Django 4.0.4 on 2024-04-04 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0029_userdocumenttype_clubdocumenttype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubdocumenttype',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='userdocumenttype',
            options={'ordering': ['order']},
        ),
    ]
