# Generated by Django 4.0.4 on 2024-04-04 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_club_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('players', '0030_alter_clubdocumenttype_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlayerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('doc_text', models.CharField(blank=True, max_length=255, null=True)),
                ('doc', models.FileField(blank=True, null=True, upload_to='players/docs/uploads')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.userplayer')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_creation'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClubPlayerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('doc_text', models.CharField(blank=True, max_length=255, null=True)),
                ('doc', models.FileField(blank=True, null=True, upload_to='players/docs/uploads')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.clubplayer')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_creation'],
                'abstract': False,
            },
        ),
    ]
