# Generated by Django 4.0.4 on 2024-04-04 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0031_userplayerdocument_clubplayerdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubplayerdocument',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.clubdocumenttype'),
        ),
        migrations.AddField(
            model_name='userplayerdocument',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.userdocumenttype'),
        ),
    ]
