# Generated by Django 4.0.4 on 2024-04-04 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0032_clubplayerdocument_type_userplayerdocument_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubplayerdocument',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='players/docs/uploads', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'gif', 'webp', 'tiff', 'tif', 'bmp', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='userplayerdocument',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='players/docs/uploads', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'gif', 'webp', 'tiff', 'tif', 'bmp', 'svg'])]),
        ),
    ]
