# Generated by Django 4.0.4 on 2024-04-04 16:12

from django.db import migrations, models
import players.models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0033_alter_clubplayerdocument_doc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubplayerdocument',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='players/docs/uploads', validators=[players.models.file_size]),
        ),
        migrations.AlterField(
            model_name='userplayerdocument',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='players/docs/uploads', validators=[players.models.file_size]),
        ),
    ]
