# Generated by Django 4.0.4 on 2025-02-11 10:04

from django.db import migrations, models

def copy_player_data(apps, schema_editor):
    AbstractPlayer = apps.get_model('players', 'AbstractPlayer')
    for player in AbstractPlayer.objects.all():
        player_card = player.card
        player_card.surname = player.surname
        player_card.name = player.name
        player_card.patronymic = player.patronymic
        player_card.save()

class Migration(migrations.Migration):

    dependencies = [
        ('players', '0034_alter_clubplayerdocument_doc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playercard',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='playercard',
            name='patronymic',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='playercard',
            name='surname',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.RunPython(copy_player_data),
    ]
