# Generated by Django 4.0.4 on 2022-05-20 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Импортируемое название источника', max_length=255, null=True)),
                ('short_name', models.CharField(help_text='Короткий ключ для поиска', max_length=10)),
                ('order', models.IntegerField(help_text='Индекс сортировки')),
                ('link', models.TextField(blank=True, help_text='Ссылка на источник', null=True)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Импортируемое название источника', max_length=255, null=True)),
                ('short_name', models.CharField(help_text='Короткий ключ для поиска', max_length=10)),
                ('order', models.IntegerField(help_text='Индекс сортировки')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
    ]
