# Generated by Django 4.0.4 on 2022-07-12 09:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
import references.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Imported source name', max_length=255, null=True, verbose_name='title')),
                ('short_name', models.CharField(default='Empty', help_text='Short name no more than 10 characters', max_length=10, verbose_name='short name')),
                ('order', models.IntegerField(default=0, help_text='Sorting index', verbose_name='order')),
                ('date_with', models.DateField(default=datetime.date(2022, 1, 1), help_text='Start date of the season.', verbose_name='start date')),
                ('date_by', models.DateField(default=datetime.date(2022, 12, 31), help_text='End date of the season.', verbose_name='end date')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClubTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Imported source name', max_length=255, null=True, verbose_name='title')),
                ('short_name', models.CharField(default='Empty', help_text='Short name no more than 10 characters', max_length=10, verbose_name='short name')),
                ('order', models.IntegerField(default=0, help_text='Sorting index', verbose_name='order')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExsAgeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Imported source name', max_length=255, null=True, verbose_name='title')),
                ('short_name', models.CharField(default='Empty', help_text='Short name no more than 10 characters', max_length=10, verbose_name='short name')),
                ('order', models.IntegerField(default=0, help_text='Sorting index', verbose_name='order')),
                ('translation_names', models.JSONField(blank=True, help_text='Translations of reference books', null=True, verbose_name='translated title')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExsBall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Imported source name', max_length=255, null=True, verbose_name='title')),
                ('short_name', models.CharField(default='Empty', help_text='Short name no more than 10 characters', max_length=10, verbose_name='short name')),
                ('order', models.IntegerField(default=0, help_text='Sorting index', verbose_name='order')),
                ('translation_names', models.JSONField(blank=True, help_text='Translations of reference books', null=True, verbose_name='translated title')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExsCognitiveLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Imported source name', max_length=255, null=True, verbose_name='title')),
                ('short_name', models.CharField(default='Empty', help_text='Short name no more than 10 characters', max_length=10, verbose_name='short name')),
                ('order', models.IntegerField(default=0, help_text='Sorting index', verbose_name='order')),
                ('translation_names', models.JSONField(blank=True, help_text='Translations of reference books', null=True, verbose_name='translated title')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExsGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Imported source name', max_length=255, null=True, verbose_name='title')),
                ('short_name', models.CharField(default='Empty', help_text='Short name no more than 10 characters', max_length=10, verbose_name='short name')),
                ('order', models.IntegerField(default=0, help_text='Sorting index', verbose_name='order')),
                ('translation_names', models.JSONField(blank=True, help_text='Translations of reference books', null=True, verbose_name='translated title')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Imported source name', max_length=255, null=True, verbose_name='title')),
                ('short_name', models.CharField(default='Empty', help_text='Short name no more than 10 characters', max_length=10, verbose_name='short name')),
                ('order', models.IntegerField(default=0, help_text='Sorting index', verbose_name='order')),
                ('translation_names', models.JSONField(blank=True, help_text='Translations of reference books', null=True, verbose_name='translated title')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExsWorkoutPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Imported source name', max_length=255, null=True, verbose_name='title')),
                ('short_name', models.CharField(default='Empty', help_text='Short name no more than 10 characters', max_length=10, verbose_name='short name')),
                ('order', models.IntegerField(default=0, help_text='Sorting index', verbose_name='order')),
                ('translation_names', models.JSONField(blank=True, help_text='Translations of reference books', null=True, verbose_name='translated title')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Imported source name', max_length=255, null=True, verbose_name='title')),
                ('short_name', models.CharField(default='Empty', help_text='Short name no more than 10 characters', max_length=10, verbose_name='short name')),
                ('order', models.IntegerField(default=0, help_text='Sorting index', verbose_name='order')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Imported source name', max_length=255, null=True, verbose_name='title')),
                ('short_name', models.CharField(default='Empty', help_text='Short name no more than 10 characters', max_length=10, verbose_name='short name')),
                ('order', models.IntegerField(default=0, help_text='Sorting index', verbose_name='order')),
                ('date_with', models.DateField(default=datetime.date(2022, 1, 1), help_text='Start date of the season.', verbose_name='start date')),
                ('date_by', models.DateField(default=datetime.date(2022, 12, 31), help_text='End date of the season.', verbose_name='end date')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Imported source name', max_length=255, null=True, verbose_name='title')),
                ('short_name', models.CharField(default='Empty', help_text='Short name no more than 10 characters', max_length=10, verbose_name='short name')),
                ('order', models.IntegerField(default=0, help_text='Sorting index', verbose_name='order')),
                ('link', models.TextField(blank=True, help_text='Link to the source', null=True, verbose_name='link')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Imported source name', max_length=255, null=True, verbose_name='title')),
                ('short_name', models.CharField(default='Empty', help_text='Short name no more than 10 characters', max_length=10, verbose_name='short name')),
                ('order', models.IntegerField(default=0, help_text='Sorting index', verbose_name='order')),
                ('ref_team_status', models.ForeignKey(default=references.models.TeamStatus.get_default_pk, help_text='Team status.', on_delete=django.db.models.deletion.SET_DEFAULT, to='references.teamstatus', verbose_name='team status')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
    ]
