# Generated by Django 4.0.4 on 2022-06-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreference',
            name='order',
            field=models.IntegerField(blank=True, default=0, help_text='Индекс сортировки'),
        ),
        migrations.AlterField(
            model_name='videosource',
            name='order',
            field=models.IntegerField(blank=True, default=0, help_text='Индекс сортировки'),
        ),
    ]
