# Generated by Django 4.0.4 on 2022-07-19 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExsSource',
        ),
        migrations.DeleteModel(
            name='ExsWorkoutPart',
        ),
    ]
