# Generated by Django 4.0.4 on 2022-06-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_alter_userreference_order_alter_videosource_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreference',
            name='order',
            field=models.IntegerField(default=0, help_text='Индекс сортировки'),
        ),
        migrations.AlterField(
            model_name='userreference',
            name='short_name',
            field=models.CharField(default='Empty', help_text='Короткий ключ для поиска', max_length=10),
        ),
        migrations.AlterField(
            model_name='videosource',
            name='order',
            field=models.IntegerField(default=0, help_text='Индекс сортировки'),
        ),
        migrations.AlterField(
            model_name='videosource',
            name='short_name',
            field=models.CharField(default='Empty', help_text='Короткий ключ для поиска', max_length=10),
        ),
    ]
