# Generated by Django 4.0.4 on 2022-06-09 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('references', '0003_alter_userreference_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractUserReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Imported source name', max_length=255, null=True, verbose_name='title')),
                ('short_name', models.CharField(default='Empty', help_text='Short name no more than 10 characters', max_length=10, verbose_name='short name')),
                ('order', models.IntegerField(default=0, help_text='Sorting index', verbose_name='order')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='videosource',
            name='link',
            field=models.TextField(blank=True, help_text='Link to the source', null=True, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='videosource',
            name='name',
            field=models.CharField(blank=True, help_text='Imported source name', max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='videosource',
            name='order',
            field=models.IntegerField(default=0, help_text='Sorting index', verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='videosource',
            name='short_name',
            field=models.CharField(default='Empty', help_text='Short name no more than 10 characters', max_length=10, verbose_name='short name'),
        ),
        migrations.DeleteModel(
            name='UserReference',
        ),
    ]
