# Generated by Django 4.0.4 on 2022-06-09 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0004_abstractuserreference_alter_videosource_link_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AbstractUserReference',
        ),
    ]
