# Generated by Django 4.0.4 on 2022-06-28 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0009_alter_exsball_options_exsball_translation_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exsball',
            options={'ordering': ['order']},
        ),
    ]
