# Generated by Django 4.0.4 on 2022-06-29 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('references', '0011_exspurpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExsStressType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Imported source name', max_length=255, null=True, verbose_name='title')),
                ('short_name', models.CharField(default='Empty', help_text='Short name no more than 10 characters', max_length=10, verbose_name='short name')),
                ('order', models.IntegerField(default=0, help_text='Sorting index', verbose_name='order')),
                ('translation_names', models.JSONField(blank=True, help_text='Translations of reference books', null=True, verbose_name='translated title')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExsCoaching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Imported source name', max_length=255, null=True, verbose_name='title')),
                ('short_name', models.CharField(default='Empty', help_text='Short name no more than 10 characters', max_length=10, verbose_name='short name')),
                ('order', models.IntegerField(default=0, help_text='Sorting index', verbose_name='order')),
                ('translation_names', models.JSONField(blank=True, help_text='Translations of reference books', null=True, verbose_name='translated title')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
    ]
