# Generated by Django 4.0.4 on 2022-10-21 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0014_playerprotocolstatus_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubseason',
            options={'verbose_name': 'Club Season', 'verbose_name_plural': 'Club Seasons'},
        ),
        migrations.AlterModelOptions(
            name='clubteam',
            options={'verbose_name': 'Club Team', 'verbose_name_plural': 'Club Teams'},
        ),
        migrations.AlterModelOptions(
            name='exsadditionaldata',
            options={'ordering': ['order'], 'verbose_name': 'Exercise additional data', 'verbose_name_plural': 'Exercise additional data'},
        ),
        migrations.AlterModelOptions(
            name='exsagecategory',
            options={'ordering': ['order'], 'verbose_name': 'Exercise age category', 'verbose_name_plural': 'Exercise age categories'},
        ),
        migrations.AlterModelOptions(
            name='exsball',
            options={'ordering': ['order'], 'verbose_name': 'Exercise with a ball', 'verbose_name_plural': 'Exercise with a ball'},
        ),
        migrations.AlterModelOptions(
            name='exscategory',
            options={'ordering': ['order'], 'verbose_name': 'Exercise category', 'verbose_name_plural': 'Exercise categories'},
        ),
        migrations.AlterModelOptions(
            name='exscoaching',
            options={'ordering': ['order'], 'verbose_name': 'Exercise coaching', 'verbose_name_plural': 'Exercise coaching'},
        ),
        migrations.AlterModelOptions(
            name='exscognitiveload',
            options={'ordering': ['order'], 'verbose_name': 'Exercise cognitive load', 'verbose_name_plural': 'Exercise cognitive loads'},
        ),
        migrations.AlterModelOptions(
            name='exsgoal',
            options={'ordering': ['order'], 'verbose_name': 'Exercise goal', 'verbose_name_plural': 'Exercise goals'},
        ),
        migrations.AlterModelOptions(
            name='exskeyword',
            options={'ordering': ['order'], 'verbose_name': 'Exercise keyword', 'verbose_name_plural': 'Exercise keywords'},
        ),
        migrations.AlterModelOptions(
            name='exspurpose',
            options={'ordering': ['order'], 'verbose_name': 'Exercise purpose', 'verbose_name_plural': 'Exercise purposes'},
        ),
        migrations.AlterModelOptions(
            name='exsstresstype',
            options={'ordering': ['order'], 'verbose_name': 'Exercise stress type', 'verbose_name_plural': 'Exercise stress types'},
        ),
        migrations.AlterModelOptions(
            name='exsteamcategory',
            options={'ordering': ['order'], 'verbose_name': 'Exercise team category', 'verbose_name_plural': 'Exercise team categories'},
        ),
        migrations.AlterModelOptions(
            name='exstitlename',
            options={'ordering': ['order'], 'verbose_name': 'Exercise title name', 'verbose_name_plural': 'Exercise title names'},
        ),
        migrations.AlterModelOptions(
            name='exstrainpart',
            options={'ordering': ['order'], 'verbose_name': 'Exercise part of the training', 'verbose_name_plural': 'Exercise parts of the training'},
        ),
        migrations.AlterModelOptions(
            name='playerfoot',
            options={'ordering': ['order'], 'verbose_name': 'Player leg', 'verbose_name_plural': 'Player legs'},
        ),
        migrations.AlterModelOptions(
            name='playerlevel',
            options={'ordering': ['order'], 'verbose_name': 'Player level', 'verbose_name_plural': 'Player levels'},
        ),
        migrations.AlterModelOptions(
            name='playerplayerstatus',
            options={'ordering': ['order'], 'verbose_name': 'Player status', 'verbose_name_plural': 'Player statuses'},
        ),
        migrations.AlterModelOptions(
            name='playerposition',
            options={'ordering': ['order'], 'verbose_name': 'Player position', 'verbose_name_plural': 'Player positions'},
        ),
        migrations.AlterModelOptions(
            name='playerprotocolstatus',
            options={'ordering': ['order'], 'verbose_name': 'Player protocol status', 'verbose_name_plural': 'Player protocol statuses'},
        ),
        migrations.AlterModelOptions(
            name='playerteamstatus',
            options={'ordering': ['order'], 'verbose_name': 'Player team status', 'verbose_name_plural': 'Player team statuses'},
        ),
        migrations.AlterModelOptions(
            name='teamstatus',
            options={'ordering': ['order'], 'verbose_name': 'Team status', 'verbose_name_plural': 'Team statuses'},
        ),
        migrations.AlterModelOptions(
            name='userseason',
            options={'verbose_name': 'User Season', 'verbose_name_plural': 'User Seasons'},
        ),
        migrations.AlterModelOptions(
            name='userteam',
            options={'verbose_name': 'User Team', 'verbose_name_plural': 'User Teams'},
        ),
        migrations.AlterModelOptions(
            name='videosource',
            options={'ordering': ['order'], 'verbose_name': 'Video source', 'verbose_name_plural': 'Video sources'},
        ),
    ]
