# Generated by Django 4.0.4 on 2022-10-25 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0015_alter_clubseason_options_alter_clubteam_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubseason',
            old_name='user_id',
            new_name='club_id',
        ),
        migrations.RenameField(
            model_name='clubteam',
            old_name='user_id',
            new_name='club_id',
        ),
    ]
