# Generated by Django 4.0.4 on 2022-10-26 10:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('references', '0016_rename_user_id_clubseason_club_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubteam',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='Users who have access to the team', null=True, to=settings.AUTH_USER_MODEL, verbose_name='users'),
        ),
    ]
