# Generated by Django 4.0.4 on 2023-02-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0022_exsdescriptiontemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubteam',
            name='age_key',
            field=models.CharField(default='Empty', help_text='Age key no more than 10 characters', max_length=10, verbose_name='age key'),
        ),
        migrations.AddField(
            model_name='clubteam',
            name='u_key',
            field=models.CharField(default='Empty', help_text='U key no more than 10 characters', max_length=10, verbose_name='U key'),
        ),
        migrations.AddField(
            model_name='userteam',
            name='age_key',
            field=models.CharField(default='Empty', help_text='Age key no more than 10 characters', max_length=10, verbose_name='age key'),
        ),
        migrations.AddField(
            model_name='userteam',
            name='u_key',
            field=models.CharField(default='Empty', help_text='U key no more than 10 characters', max_length=10, verbose_name='U key'),
        ),
    ]
