# Generated by Django 4.0.4 on 2023-02-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0024_exskeyword_keycode'),
    ]

    operations = [
        migrations.AddField(
            model_name='exscategory',
            name='keycode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
