# Generated by Django 4.0.4 on 2023-02-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0025_exscategory_keycode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExsPhysicalQualities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Imported source name', max_length=255, null=True, verbose_name='title')),
                ('short_name', models.CharField(default='Empty', help_text='Short name no more than 10 characters', max_length=10, verbose_name='short name')),
                ('order', models.IntegerField(default=0, help_text='Sorting index', verbose_name='order')),
                ('translation_names', models.JSONField(blank=True, help_text='Translations of reference books', null=True, verbose_name='translated title')),
                ('icon_id', models.CharField(blank=True, max_length=255, null=True)),
                ('keycode', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Exercise types',
                'verbose_name_plural': 'Exercise types',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Imported source name', max_length=255, null=True, verbose_name='title')),
                ('short_name', models.CharField(default='Empty', help_text='Short name no more than 10 characters', max_length=10, verbose_name='short name')),
                ('order', models.IntegerField(default=0, help_text='Sorting index', verbose_name='order')),
                ('translation_names', models.JSONField(blank=True, help_text='Translations of reference books', null=True, verbose_name='translated title')),
                ('keycode', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Exercise types',
                'verbose_name_plural': 'Exercise types',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
    ]
