# Generated by Django 4.0.4 on 2023-02-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0026_exsphysicalqualities_exstype'),
    ]

    operations = [
        migrations.AddField(
            model_name='exscognitiveload',
            name='keycode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
