# Generated by Django 4.0.4 on 2023-02-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0027_exscognitiveload_keycode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exsphysicalqualities',
            options={'ordering': ['order'], 'verbose_name': 'Exercise physical qualities', 'verbose_name_plural': 'Exercise physical qualities'},
        ),
        migrations.AlterField(
            model_name='exsphysicalqualities',
            name='keycode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
