# Generated by Django 4.0.4 on 2023-03-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0028_alter_exsphysicalqualities_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubteam',
            name='u_key',
            field=models.CharField(default='U', help_text='U key no more than 10 characters', max_length=10, verbose_name='U key'),
        ),
        migrations.AlterField(
            model_name='userteam',
            name='u_key',
            field=models.CharField(default='U', help_text='U key no more than 10 characters', max_length=10, verbose_name='U key'),
        ),
    ]
