# Generated by Django 4.0.4 on 2023-03-20 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_remove_club_limits_club_player_limit_club_team_limit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('references', '0029_alter_clubteam_u_key_alter_userteam_u_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExsAdditionalData',
            fields=[
                ('exsadditionaldata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='references.exsadditionaldata')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User exercise additional data',
                'verbose_name_plural': 'User exercise additional data',
                'ordering': ['order'],
                'abstract': False,
            },
            bases=('references.exsadditionaldata', models.Model),
        ),
        migrations.CreateModel(
            name='ClubExsAdditionalData',
            fields=[
                ('exsadditionaldata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='references.exsadditionaldata')),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
            ],
            options={
                'verbose_name': 'Club exercise additional data',
                'verbose_name_plural': 'Club exercise additional data',
                'ordering': ['order'],
                'abstract': False,
            },
            bases=('references.exsadditionaldata', models.Model),
        ),
    ]
