# Generated by Django 4.0.4 on 2023-06-01 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0030_userexsadditionaldata_clubexsadditionaldata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubteam',
            options={'ordering': ['name'], 'verbose_name': 'Club Team', 'verbose_name_plural': 'Club Teams'},
        ),
        migrations.AlterModelOptions(
            name='userteam',
            options={'ordering': ['name'], 'verbose_name': 'User Team', 'verbose_name_plural': 'User Teams'},
        ),
    ]
