# Generated by Django 4.0.4 on 2023-06-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0032_alter_clubteam_u_key_alter_userteam_u_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamstatus',
            name='translation_names',
            field=models.JSONField(blank=True, help_text='Translations of reference books', null=True, verbose_name='translated title'),
        ),
    ]
