# Generated by Django 4.0.4 on 2023-12-04 11:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0007_club_image'),
        ('references', '0037_medicinediseasespecificuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPaymentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.DecimalField(decimal_places=2, default=0.0, help_text='Payment in foreign currency', max_digits=8, verbose_name='Payment')),
                ('discount', models.PositiveSmallIntegerField(default=0, help_text='Percent discount (0-100%)', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Discount')),
                ('date', models.DateField(help_text='Date when the user paid', verbose_name='Date of payment')),
                ('payment_before', models.DateField(help_text='The date before which the program was paid for', verbose_name='Date of payment before')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Payment',
                'verbose_name_plural': 'User Payments',
            },
        ),
        migrations.CreateModel(
            name='ClubPaymentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.DecimalField(decimal_places=2, default=0.0, help_text='Payment in foreign currency', max_digits=8, verbose_name='Payment')),
                ('discount', models.PositiveSmallIntegerField(default=0, help_text='Percent discount (0-100%)', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Discount')),
                ('date', models.DateField(help_text='Date when the user paid', verbose_name='Date of payment')),
                ('payment_before', models.DateField(help_text='The date before which the program was paid for', verbose_name='Date of payment before')),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
            ],
            options={
                'verbose_name': 'Club Payment',
                'verbose_name_plural': 'Club Payments',
            },
        ),
    ]
