# Generated by Django 4.0.4 on 2023-12-15 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0007_club_image'),
        ('references', '0038_userpaymentinformation_clubpaymentinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExsFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Imported source name', max_length=255, null=True, verbose_name='title')),
                ('short_name', models.CharField(default='Empty', help_text='Short name no more than 10 characters', max_length=10, verbose_name='short name')),
                ('order', models.IntegerField(default=0, help_text='Sorting index', verbose_name='order')),
                ('translation_names', models.JSONField(blank=True, help_text='Translations of reference books', null=True, verbose_name='translated title')),
            ],
            options={
                'verbose_name': 'Exercise feature data',
                'verbose_name_plural': 'Exercise feature data',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserExsFeatures',
            fields=[
                ('exsfeatures_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='references.exsfeatures')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User exercise feature data',
                'verbose_name_plural': 'User exercise feature data',
                'ordering': ['order'],
                'abstract': False,
            },
            bases=('references.exsfeatures', models.Model),
        ),
        migrations.CreateModel(
            name='ClubExsFeatures',
            fields=[
                ('exsfeatures_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='references.exsfeatures')),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
            ],
            options={
                'verbose_name': 'Club exercise feature data',
                'verbose_name_plural': 'Club exercise feature data',
                'ordering': ['order'],
                'abstract': False,
            },
            bases=('references.exsfeatures', models.Model),
        ),
    ]
