# Generated by Django 4.0.4 on 2023-12-19 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0039_clubteam_players_json_userteam_players_json'),
        ('references', '0039_exsfeatures_userexsfeatures_clubexsfeatures'),
    ]

    operations = [
    ]
