# Generated by Django 4.0.4 on 2024-01-11 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0040_merge_20231219_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubseason',
            name='date_by',
            field=models.DateField(default=datetime.date(2024, 12, 31), help_text='End date of the season.', verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='clubseason',
            name='date_with',
            field=models.DateField(default=datetime.date(2024, 1, 1), help_text='Start date of the season.', verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='userseason',
            name='date_by',
            field=models.DateField(default=datetime.date(2024, 12, 31), help_text='End date of the season.', verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='userseason',
            name='date_with',
            field=models.DateField(default=datetime.date(2024, 1, 1), help_text='Start date of the season.', verbose_name='start date'),
        ),
    ]
