# Generated by Django 4.0.4 on 2024-10-25 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('references', '0041_alter_clubseason_date_by_alter_clubseason_date_with_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubteam',
            name='user_trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_trainer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userteam',
            name='user_trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_trainer', to=settings.AUTH_USER_MODEL),
        ),
    ]
