# Generated by Django 4.0.4 on 2023-11-01 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0043_user_player_limit_user_team_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_receiving', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when the user will receive the notification', verbose_name='date of receiving')),
                ('date_update', models.DateTimeField(auto_now=True, help_text='Notice last updated date', verbose_name='update date')),
                ('title', models.CharField(help_text='Notification subject for users', max_length=255, verbose_name='notification subject')),
                ('content', models.TextField(blank=True, help_text='Notification content for users', null=True, verbose_name='notification content')),
            ],
            options={
                'ordering': ['date_receiving', 'date_update'],
            },
        ),
        migrations.CreateModel(
            name='NotificationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed', models.BooleanField(default=False)),
                ('favorites', models.BooleanField(default=False)),
                ('notification', models.ForeignKey(help_text='Notification that was sent', on_delete=django.db.models.deletion.CASCADE, to='notifications.notification', verbose_name='notification')),
                ('user', models.ForeignKey(help_text='User to whom it was sent', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'ordering': ['notification__date_receiving', 'viewed'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='Users who will receive the notification', through='notifications.NotificationUser', to=settings.AUTH_USER_MODEL, verbose_name='users'),
        ),
    ]
