# Generated by Django 4.0.4 on 2023-11-01 10:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['date_update']},
        ),
        migrations.AlterModelOptions(
            name='notificationuser',
            options={'ordering': ['date_receiving', 'notification__date_update', 'viewed']},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='date_receiving',
        ),
        migrations.AddField(
            model_name='notificationuser',
            name='date_receiving',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date when the user will receive the notification', verbose_name='date of receiving'),
        ),
    ]
