# Generated by Django 4.0.4 on 2023-11-02 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-date_update']},
        ),
        migrations.AlterModelOptions(
            name='notificationuser',
            options={'ordering': ['-date_receiving', '-notification__date_update', 'viewed']},
        ),
    ]
