# Generated by Django 4.0.4 on 2023-11-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date_update',
            field=models.DateTimeField(auto_now=True, help_text='Notification last updated date', verbose_name='update date'),
        ),
    ]
